temporalio/sdk-java

- build.gradle
- src/main/java/io/temporal/internal/common/InternalUtils.java
- src/test/java/io/temporal/internal/testing/ActivityTestingTest.java
- src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
- src/test/java/io/temporal/worker/WorkerStressTests.java
- src/test/java/io/temporal/workflow/MetricsTest.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
- src/test/resources/resetWorkflowHistory.json
- src/test/resources/testAsyncActivityRetryHistory.json
- src/test/resources/testChildWorkflowRetryHistory.json
- src/test/resources/testMutableSideEffectBackwardCompatibility.json
- src/test/resources/timerfiring.json
The activity and workflow names are used in metrics reporting. Prometheus has pretty strict restrictions around the names. So replacing "::" separator with "_".
> Replaced double colon with underscore in workflow and activity names

- src/main/java/io/temporal/client/WorkflowClientOptions.java
- src/main/java/io/temporal/internal/sync/TestWorkflowEnvironmentInternal.java
- src/main/java/io/temporal/worker/WorkerFactory.java
- src/test/java/io/temporal/worker/StickyWorkerTest.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
The default identity logic that calls ManagementFactory.getRuntimeMXBean().getName() creates very bad user experience on Mac which takes 5+ seconds to return.  This change skips this call on mac. If a mac user wants to set identity he can always set ClientOptions.idenity property himself.
> Added logic to skip localhost name lookup on mac

- build.gradle
Without this dependency the freshly cloned repo fails to build.
> Added missing updateSubmodules build dependency

- src/main/java/io/temporal/common/interceptors/WorkflowCallsInterceptor.java
- src/main/java/io/temporal/common/interceptors/WorkflowCallsInterceptorBase.java
- src/main/java/io/temporal/internal/external/GenericWorkflowClientExternalImpl.java
- src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- src/main/java/io/temporal/internal/sync/SyncDecisionContext.java
- src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- src/main/java/io/temporal/internal/sync/SyncWorkflowDefinition.java
- src/main/java/io/temporal/internal/sync/TestActivityEnvironmentInternal.java
- src/main/java/io/temporal/internal/sync/WorkflowExecuteRunnable.java
- src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- src/main/java/io/temporal/workflow/Workflow.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
- src/test/java/io/temporal/workflow/interceptors/SignalWorkflowCallsInterceptor.java
After this change it is possible to add a signal and query listener from a workflow code as:
```
@WorkflowInterface
public interface SignalQueryBase {
@SignalMethod
void signal(String arg);
@QueryMethod
String getSignal();
}
public static class TestSignalAndQueryListenerWorkflowImpl
implements TestSignalAndQueryListenerWorkflow {
private List<String> signals = new ArrayList<>();
@Override
public void execute() {
Workflow.registerListener(
new SignalQueryBase() {
@Override
public void signal(String arg) {
signals.add(arg);
}
@Override
public String getSignal() {
return String.join(", ", signals);
}
});
...
...
}
}
```
> Added ability to register signal listener from workflow code

- docker/buildkite/docker-compose.yaml
- src/main/java/io/temporal/activity/ActivityInterface.java
- src/main/java/io/temporal/activity/ActivityMethod.java
- src/main/java/io/temporal/internal/sync/POJOActivityImplMetadata.java
- src/main/java/io/temporal/internal/sync/POJOActivityInterfaceMetadata.java
- src/main/java/io/temporal/internal/sync/POJOActivityMethodMetadata.java
- src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- src/main/java/io/temporal/internal/sync/POJOWorkflowMethodMetadata.java
- src/main/java/io/temporal/internal/testservice/StateMachine.java
- src/main/java/io/temporal/internal/testservice/StateMachines.java
- src/main/java/io/temporal/workflow/QueryMethod.java
- src/main/java/io/temporal/workflow/SignalMethod.java
- src/main/java/io/temporal/workflow/WorkflowMethod.java
- src/test/java/io/temporal/internal/sync/POJOActivityMetadataTest.java
- src/test/java/io/temporal/internal/sync/POJOWorkflowMetadataTest.java
- src/test/java/io/temporal/internal/testing/ActivityTestingTest.java
- src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
- src/test/java/io/temporal/worker/WorkerStressTests.java
- src/test/java/io/temporal/workflow/MetricsTest.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
- src/test/resources/resetWorkflowHistory.json
- src/test/resources/testAsyncActivityRetryHistory.json
- src/test/resources/testChildWorkflowRetryHistory.json
- src/test/resources/testMutableSideEffectBackwardCompatibility.json
Before this change the default names of workflow and activity types as well as query and signal handlers are in the form <short interface class name>_<method_name>.
These names are too long and are not user friendly. So the most users end up redefining them using annotations. This change changes the default names to:
Note that query and signal are always scoped to a specific workflow instance. So prefix in their name is not that useful. At the same time the workflow type is usually pretty unique and adding its main method name is not really necessary.
- workflow type is <short interface class name>
- query type is <method name>
- signal type is <method name>
Activity names are by default become just method name of the activity method. It is possible to add a prefix to all the activity …
> Changes to names of workflow and activity type as well as signal and query methods

- src/main/java/io/temporal/client/WorkflowOptions.java
- src/main/java/io/temporal/internal/external/GenericWorkflowClientExternalImpl.java
- src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java
- src/main/java/io/temporal/internal/testservice/TestWorkflowMutableState.java
- src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- src/main/java/io/temporal/worker/WorkflowImplementationOptions.java
- src/main/java/io/temporal/workflow/WorkflowMethod.java
- src/test/java/io/temporal/worker/StickyWorkerTest.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
TestService: Fixed signalWithStart failure on closed workflow even if AllowDuplicate policy is specified
Changed the default idReusePolicy to the correct service side default of (AllowDuplicate).
> Fixed signalWithStart in the test service

- src/main/java/io/temporal/internal/replay/ClockDecisionContext.java
- src/main/java/io/temporal/internal/replay/DecisionsHelper.java
- src/main/java/io/temporal/internal/replay/ReplayDecisionTaskHandler.java
- src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- src/main/java/io/temporal/worker/WorkerFactoryOptions.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
Fixes https://github.com/temporalio/temporal-java-sdk/issues/80
> Fixed getVersion removal and addition

- .gitmodules
Users cannot clone and build without an ssh key due to remote being referenced via ssh url and not https.
> Move submodule to https

- src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
It was printing the whole workflow history on a bening exception.
> Removed diagnostics from exception message

- build.gradle
- src/main/java/io/temporal/activity/ActivityOptions.java
- src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- src/test/java/io/temporal/internal/sync/PromiseTest.java
- src/test/java/io/temporal/worker/StickyWorkerTest.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
The same error was logged multiple times before this change.
> Fixed root workflow thread names and removed excessive error logging

- src/main/java/io/temporal/internal/sync/TestWorkflowEnvironmentInternal.java
- src/main/java/io/temporal/internal/testservice/RequestContext.java
- src/main/java/io/temporal/internal/testservice/SelfAdvancingTimer.java
- src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java
- src/main/java/io/temporal/internal/testservice/StateMachines.java
- src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
The TestWorkflowEnvironment has an unobvious assumption that only one blocking call to a workflow stub at a time is made. 
This didn't work with the scenario when a workflow was executed from activity in a blocking manner. This PR fixes this situation.
> Fixed time skipping when using workflow client from an activity

- src/main/java/io/temporal/common/converter/EncodedValue.java
- src/test/java/io/temporal/common/converter/EncodedValueTest.java
Exception encountered:
{Failure:{Message:converter not set, Source:JavaSDK,                                                                      
StackTrace:io.temporal.common.converter.EncodedValue.toPayloads(EncodedValue.java:46)                                     
io.temporal.failure.FailureConvert er.exceptio nToFailureNoUnwrapping(FailureConverter.java:218)                          
io.temporal.failure.Fail ... r.run(ThreadPoolExecutor.java:628) java.base/java.lang.Thread.run(Thread. java:835) ,        
FailureInfo:&Failure_ApplicationFailureInfo{ApplicationFailureInfo:&ApplicationFailureInfo{Type:java.lang.IllegalStateEx  
ception,NonR etryable:false,Details:nil,},}},
Problem: A timeout exception with no heartbeat details will not have a converter set by definition. This causes an …
> Fixes bug where timeout exception with no heartbeat details causes an Illegal State exception

- src/main/java/io/temporal/common/converter/DataConverter.java
- src/main/java/io/temporal/common/converter/DefaultDataConverter.java
- src/main/java/io/temporal/common/converter/EncodedValues.java
- src/main/java/io/temporal/common/converter/Values.java
- src/main/java/io/temporal/failure/ApplicationFailure.java
- src/main/java/io/temporal/failure/CanceledFailure.java
- src/main/java/io/temporal/failure/FailureConverter.java
- src/main/java/io/temporal/failure/TimeoutFailure.java
- src/main/java/io/temporal/internal/common/LocalActivityMarkerData.java
- src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- src/main/java/io/temporal/internal/replay/MarkerHandler.java
- src/main/java/io/temporal/internal/replay/ReplayChildWorkflowContext.java
- src/main/java/io/temporal/internal/replay/ReplayClockContext.java
- src/main/java/io/temporal/internal/sync/ActivityExecutionContextImpl.java
- src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- src/main/java/io/temporal/internal/sync/TestActivityEnvironmentInternal.java
- src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java
- src/test/java/io/temporal/common/converter/EncodedValuesTest.java
- src/test/java/io/temporal/common/converter/JsonDataConverterTest.java
- src/test/java/io/temporal/common/converter/ProtoPayloadConverterTest.java
- src/test/java/io/temporal/worker/CleanWorkerShutdownTest.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
* Updated DataConverter API to support extracting individual values from the serialized list.
* Renamed EncodedValue to EncodedValues.
* Added ApplicationFailure factories for clarity.
> Renamed EncodedValue to EncodedValues to support multiple details

- src/main/java/io/temporal/internal/sync/POJOActivityInterfaceMetadata.java
- src/main/java/io/temporal/internal/sync/POJOWorkflowImplMetadata.java
- src/main/java/io/temporal/internal/sync/POJOWorkflowInterfaceMetadata.java
- src/main/java/io/temporal/internal/sync/POJOWorkflowMethodMetadata.java
- src/test/java/io/temporal/internal/sync/POJOActivityMetadataTest.java
- src/test/java/io/temporal/internal/sync/POJOWorkflowMetadataTest.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
- Fails registration if there are Activity/Workflow interfaces which are non-public
- Does not perform validation on interfaces that would not be leveraged / used by the Temporal SDK
> Fixes overzealous validation logic and adds specific check for public interfaces on registration

- build.gradle
- src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
Uses JSR250 javax.annotation-api as an implementation dependency
instead of the default-off java.xml.ws.annotation module in JDK9 onwards.
Differentiates use of yield identifier from the JDK14 yield keyword.
Stops using Integer(int) constructors (deprecated in JDK9).
> Support building with JDK9 and up (#176)

- src/main/java/io/temporal/common/RetryOptions.java
- src/main/java/io/temporal/failure/FailureConverter.java
- src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- src/main/java/io/temporal/internal/sync/WorkflowRetryerInternal.java
- src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
Fix for https://github.com/temporalio/java-sdk/issues/174.
The validation and defaulting of RetryOptions are removed when scheduling activities and child workflows. The service is expected to perform validation as well as provide defaults for them.
Added validation and defaulting of RetryOptions for local activities as service is not involved in their execution.
> Retry options

- src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- src/main/java/io/temporal/internal/replay/WorkflowContext.java
- src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- src/main/java/io/temporal/internal/testservice/StateMachines.java
- src/main/java/io/temporal/workflow/WorkflowInfo.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
This change adds feature parity with Go SDK which has attempt field in the workflow info, which comes from the workflow start event attributes.
> Adding attempt to workflow info

- build.gradle
New dependency version: io.grpc:grpc-netty-shaded: 1.31.1 -> 1.32.1
New dependency version: io.grpc:grpc-protobuf: 1.31.1 -> 1.32.1
New dependency version: io.grpc:grpc-stub: 1.31.1 -> 1.32.1
New dependency version: io.grpc:protoc-gen-grpc-java: 1.31.1 -> 1.32.1
> Update grpc from 1.31.1 -> 1.32.1

- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
Stop ignoring  `maxConcurrentWorkflowTaskExecutionSize` and `maxConcurrentActivityExecutionSize`
> Fixed WorkerOptions

- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowHistoryIterator.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/WorkflowHistoryIteratorTest.java
Next page token may point to an empty page. This results in a possibility that hasNext() may return true and then next() throws NoSuchElementException. This sequence is invalid and breaks iterator contract.
Here is example of an exception that we've observed:
```
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: java.util.NoSuchElementException
at java.base/java.util.Collections$EmptyIterator.next(Collections.java:4277)
at io.temporal.internal.replay.WorkflowHistoryIterator.next(WorkflowHistoryIterator.java:116)
at io.temporal.internal.replay.WorkflowHistoryIterator.next(WorkflowHistoryIterator.java:40)
at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:179)
at …
```
> Verify that next page is not empty in the history iterator

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
This change adds an action that would reset exponential backoff regularly. (Default is every 10 seconds)
Opt-out is possible by setting null value in the WorkflowServiceStubsOptions.connectionBackoffResetFrequency
> Add gRPC backoff resetter

- temporal-sdk/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTest.java
This should address #203 by copying non retryable errors in the test service.
> Copy non retryable error types list in ensureDefaultFieldsForActivity

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
This PR contains changes required to populate headers on grpc requests to the server.
Previously headers set on factory options were simply ignored, here we fix it.
> Copy headers from factory options into grpc requests

- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowExecutorCache.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerCacheTests.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerTaskHandlerTests.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
This PR addresses an issue with overly aggressive calls to reset sticky during cache invalidation.
Instead we are only going to reset sticky tasklist when exceptions occur.
> Remove reset sticky call from cache invalidation

- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactoryOptions.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTest.java
This change sets default value for schedule to start timeout option property to 5 seconds. This behavior is similar to what we have in go sdk:
https://github.com/temporalio/sdk-go/blob/d2bd562a1e775d645ab3205248c45d96bda3fc0c/internal/internal_task_pollers.go#L60
> Default schedule to start timeout

- temporal-sdk/src/main/java/io/temporal/common/reporter/MicrometerClientStatsReporter.java
This PR introduces two changes that make metrics reporting similar to Go.
Firstly we've reported timer metrics as plain numbers and not histograms, which meant that we didn't have all the bucket data and were unable to use percentiles, that we heavily rely up on in our SDK dashboard. Here we fix this issue by setting report histogram tag on metric reporter.
Secondly unlike in go we've used default prometheus naming convention which set time unit at the end of every latency metric resulting in diverging names. We fix it too here by applying snake_case metric convention.
> Report timers as histograms and use snake case naming convention

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
Recently we've added a connection backoff resetter as a way to mitigate long gRPC backoff intervals (look [here](https://github.com/grpc/grpc-java/issues/7456) for details).
The way resetter works is that we have a thread pool that periodically resets connection backoff allowing threads to detect backends faster.
Initially those threads in the thread pool used default thread factory resulting in creation of user threads (as opposed to daemon threads) and were blocking JVM shutdown in case of failure in main program.
This caused unwanted behavior and displayed on our java canary as a "stuck jvm" with crashed main in case if the process was unable to startup properly (e.g. register the namespace).
With this change threads are made daemon threads and will no longer block jvm exit.
Example …
> Use daemon threads for connection backoff resetter

- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
Previously we've used to always initialize a sticky task queue dispatcher and start a sticky poller.
This caused problems like:
```
java.lang.NullPointerException: null
at io.temporal.internal.worker.WorkflowWorker.apply(WorkflowWorker.java:272) ~[service-1.0.jar:?]
at io.temporal.internal.sync.SyncWorkflowWorker.apply(SyncWorkflowWorker.java:215) ~[service-1.0.jar:?]
at io.temporal.internal.sync.SyncWorkflowWorker.apply(SyncWorkflowWorker.java:51) ~[service-1.0.jar:?]
at io.temporal.internal.worker.PollWorkflowTaskDispatcher.process(PollWorkflowTaskDispatcher.java:75) ~[service-1.0.jar:?]
at io.temporal.internal.worker.PollWorkflowTaskDispatcher.process(PollWorkflowTaskDispatcher.java:40) ~[service-1.0.jar:?]
at io.temporal.internal.worker.Poller$PollExecutionTask.run(Poller.java:277) …
```
> Fix NPE in sticky poller

- temporal-sdk/src/test/java/io/temporal/worker/StickyWorkerTest.java
Common flaky test that we've seen so far was StickyWorkerTest:
```
io.temporal.worker.StickyWorkerTest > whenStickyIsEnabledThenTheWorkflowIsCachedChildWorkflows[Docker] FAILED
java.lang.AssertionError: 1 expected:<2> but was:<1>
```
This test has been relying on sleep in order to wait for the metric reporter to send metrics.
Instead we should just close metric scope, which closes reporter, flushing all metrics.
Verified multiple times locally that tests pass.
> Fix flaky test that was relying on sleep

- temporal-sdk/src/main/java/io/temporal/failure/FailureConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/common/CheckedExceptionWrapper.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/internal/common/RetryerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/CheckedExceptionWrapperTest.java
- temporal-sdk/src/test/java/io/temporal/worker/StickyWorkerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTest.java
This change removes illegal reflective access to the cause field in the `CheckedExceptionWrapper` replacing it with shallow unwrapping of the exception plus full unwrapping during serialization.
The reason we need to keep shallow unwrapping instead of getting rid of it entirely is because there are a few places in the pre-serialization code that either log or conduct actions based on the client exception. Look at [POJOWorkflowImplementationFactory](https://github.com/temporalio/sdk-java/blob/30420212a26283cf7cbe6339512058a3186074e8/temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java#L297) and [POJOActivityTaskHandler](https://github.com/temporalio/sdk-java/blob/8fba0454392a79d7371f103bc8fb084c1be8ae68/temporal-sdk/src/main/java/io/temporal/internal/s …
> Stop using illegal reflective access for setting cause during exception

- build.gradle
We've ran into a confusing situation when generated files were left over after upgrading to a new version of protobuf files. Running clean from the root project didn't help either as generated code is located under `temporal-serviceclient/build`.
This change makes top level clean to also clean sub-projects.
> Add a gradle task that cleans all sub-projects

- gradle/wrapper/gradle-wrapper.properties
- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
Before:
```
❯ ./gradlew checkUpdates
> Task :temporal-sdk:checkDependencyUpdates
New dependency version: com.cronutils:cron-utils: 9.1.1 -> 9.1.3
New dependency version: com.fasterxml.jackson.core:jackson-databind: 2.11.3 -> 2.12.0
New dependency version: com.fasterxml.jackson.datatype:jackson-datatype-jsr310: 2.11.3 -> 2.12.0
New dependency version: io.micrometer:micrometer-core: 1.6.0 -> 1.6.2
New dependency version: name.remal.check-updates:name.remal.check-updates.gradle.plugin: 1.1.4 -> 1.1.6
> Task :temporal-sdk:checkGradleUpdates
New Gradle version is available: 6.7.1 (downloadUrl: https://services.gradle.org/distributions/gradle-6.7.1-bin.zip)
> Task :temporal-serviceclient:checkDependencyUpdates
New dependency version: com.google.protobuf:com.google.protobuf.gradle.plugin: 0.8.13 …
```
> Upgrade dependencies and gradle version

- temporal-sdk/src/main/java/io/temporal/internal/external/ManualActivityCompletionClientFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollWorkflowTaskDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/PollWorkflowTaskDispatcherTests.java
Similarly to [this PR](https://github.com/temporalio/sdk-go/pull/304) in go SDK, we are populating namespace field where it was missing.
Related proto changes in the API repo are [#101](https://github.com/temporalio/api/pull/101) and [#102](https://github.com/temporalio/api/pull/102).
> Add namespace to requests where it was missing

- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
Before:
```
❯ ./gradlew checkUpdates
> Task :temporal-sdk:checkDependencyUpdates
New dependency version: com.google.guava:guava: 30.0-jre -> 30.1-jre
> Task :temporal-serviceclient:checkDependencyUpdates
New dependency version: com.uber.m3:tally-core: 0.6.1 -> 0.9.1
New dependency version: io.grpc:grpc-core: 1.34.0 -> 1.34.1
New dependency version: io.grpc:grpc-netty-shaded: 1.34.0 -> 1.34.1
New dependency version: io.grpc:grpc-protobuf: 1.34.0 -> 1.34.1
New dependency version: io.grpc:grpc-stub: 1.34.0 -> 1.34.1
New dependency version: io.grpc:protoc-gen-grpc-java: 1.34.0 -> 1.34.1
```
After:
```
❯ ./gradlew checkUpdates
> Task :temporal-serviceclient:checkDependencyUpdates
New dependency version: com.uber.m3:tally-core: 0.6.1 -> 0.9.1
```
> Updating dependencies to the latest

- temporal-sdk/src/main/java/io/temporal/internal/sync/CompletablePromiseImpl.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
See [this thread](https://community.temporal.io/t/completablepromiseimpl-cancellablegetimpl-ignores-timeunit-parameter/1210) for more context.
> Apply time unit in cancellable scope

- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/TestActivityEnvironmentInternal.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/ActivityTestingTest.java
Do not clear the list of registered activities on each `Worker.registerActivitiesImplementations` call.
Fixes https://github.com/temporalio/sdk-java/issues/20
> Fixed activity registration with multiple calls

- temporal-sdk/src/main/java/io/temporal/activity/ActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/ActivityExecutionContextBase.java
- temporal-sdk/src/main/java/io/temporal/internal/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/LocalActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/TestActivityEnvironmentInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowClientInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/LocalActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/LocalAsyncCompletionWorkflowTest.java
This PR introduces a new method `useLocalManualCompletion` in the activity context, which marks activity execution as async and returns `ActivityCompletionClient`. By doing so we expect user to manually complete activity execution on the same machine.
Also we do pass a completion handle down to the `ActivityCompletionClientImpl` and execute it only when user triggers the completion. This means that semaphore limit set by `setMaxConcurrentActivityExecutionSize` for activity polling will be respected for async activities.
Behavior is verified by `LocalAsyncCompletionWorkflowTest`.
> Add support for MaxConcurrentActivityExecutionSize for async activities

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/PromiseTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalQueueTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/DeadlockDetectorTest.java
We've recently added deadlock detector, which fails workflow tasks that run longer than 1 second.
This is great for production use, but it can be very annoying when debugging your application or tests.
Added environment variable `TEMPORAL_DEBUG_MODE` which can be set to true during debugging.
Current implementation simply disables deadlock detector, in future we might also adjust some timeouts automatically.
> Adding debug mode

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/StateMachineDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/test/java/io/temporal/workflow/DeadlockDetectorTest.java
Making behavior same as in go, renaming env var to `TEMPORAL_DEBUG` and making it take effect when set to non-empty as opposed to requiring `true` value being passed.
> Rename debug mode env var

- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTest.java
- temporal-sdk/src/test/resources/testAsyncActivityRetryHistory.json
- temporal-sdk/src/test/resources/testChildWorkflowRetryHistory.json
Allow `Worker.replayWorkflowExecution()` to throw an exception if the workflow history replay fails due to event mismatch.
Also includes a minimal set of changes to `testAsyncActivityRetryHistory.json` and `testChildWorkflowRetryHistory.json` so `WorkflowTest.testAsyncActivityRetryReplay` and `WorkflowTest.testChildWorkflowRetryReplay` to pass - seems like the replays used to fail before due to some expected history changes but tests still succeeded due to exception swallow block.
Fixes #301
> Don't swallow replay workflow exceptions

- gradle/wrapper/gradle-wrapper.properties
- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
- temporal-testing/build.gradle
```
❯ ./gradlew checkUpdates
> Configure project :temporal-sdk
project ':temporal-sdk': Plugin name.remal.check-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc...
project ':temporal-sdk': Plugin name.remal.check-dependency-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc...
project ':temporal-sdk': Plugin name.remal.check-gradle-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc...
> Configure project :temporal-serviceclient
project ':temporal-serviceclient': Plugin name.remal.check-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc...
project ':temporal-serviceclient': Plugin …
```
> Updating java sdk dependencies

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/MetricsTag.java
Bring tag names inline with prometheus naming conventions and go sdk/dashboards.
> Rename metric tags

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/SimpleSslContextBuilder.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/TemporalSslContextBuilder.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
Previously users were required to set verbose configuration for the SSL context in order to communicate with temporal backend in the cloud, e.g.
```
SslContext sslContext =
SslContextBuilder.forClient()
.keyManager(clientCert, clientCertKey))
.trustManager(
InsecureTrustManagerFactory.INSTANCE)
.applicationProtocolConfig(
new ApplicationProtocolConfig(
ApplicationProtocolConfig.Protocol.ALPN,
ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
"h2"))
.build();
WorkflowServiceStubs service =
WorkflowServiceStubs.newInstance(
WorkflowServiceStubsOptions.newBuilder()
.setSslContext(sslContext)
.setTarget(temporalServerAddr)
.build());
```
This change greatly simplifies the experience allowing users to simply do: …
> Add helper methods for setting cloud sslContext

- temporal-serviceclient/build.gradle
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/SimpleSslContextBuilder.java
Makes SimpleSslContextBuilder  an actual builder by returning reference to "this".
Also promoting netty dependency to the api from implementation so that clients can use SslContext without having to declare explicit dependency on `grpc-netty-shaded`
> Return ref to this in SimpleSslContextBuilder

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/UnableToAcquireLockException.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
User [reported an issue](https://community.temporal.io/t/timeout-issues-after-upgrading-to-1-6-3-temporal-and-1-0-5-java-client/1446) on our community forum where workers were leaking threads. 
It turns out that root cause was a deadlock condition in our code:
Workflow task event loop was trying to close (after signal failure) without releasing a lock, close function was waiting for a workflow method to finish, while workflow method was trying to yield, but needed a lock to get current workflow status.
As a result workflow task was stuck, occupying a thread and a lock for the run id. This resulted in all subsequent attempts for the same workflow task to also be stuck, occupying threads, ultimately using up all available threads in the thread pool (since we retry workflow tasks …
> Release lock before running close and use tryLock in the WorkflowWorker

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
gRPC abstracts away connection management from the user allowing interactions only on the level of the channel.
One of our issues was that all connections that gRPC is using are long living and would last as long as the server responds on keep alive requests (which practically can mean forever). This results in us being unable to properly load balance connections to the temporal front ends over time.
Consider a simple example:
```
Let's say we have 2 frontend hosts running and 20 workers 
connect to them. At the beginning, since we are using round-robing 
load balancer connections will be distributed evenly (or close to that), 
so we'll have 10 and 10 connections to each front end host on average. 
Now let's assume these front end hosts reboot one after another. 
What would happen is that …
```
> Move gRPC connections to idle periodically in order to trigger LB

- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing-junit5/src/main/java/io/temporal/testing/TestWorkflowExtension.java
Extend `TestWorkflowRule` and `TestWorkflowExtension` to expose control over `WorkflowClientOptions`. If set, it takes precedence over configured test `namespace`.
I tried to use Kotlin data classes as workflow input and output types. That required overriding `ObjectMapper` used by `DataConverter` under the hood in order to add special [`KotlinModule`](https://github.com/FasterXML/jackson-module-kotlin). Unfortunately, that's not possible now with `TestWorkflowRule` or `TestWorkflowExtension` as they don't expose any property of `WorkflowClientOptions` other than `namespace`.
> Expose WorkflowClientOptions via test extensions

- gradle/wrapper/gradle-wrapper.properties
- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
- temporal-testing-junit4/build.gradle
Addressing
```
❯ ./gradlew checkUpdates
Starting a Gradle Daemon (subsequent builds will be faster)
> Configure project :temporal-sdk
project ':temporal-sdk': Plugin name.remal.check-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc...
project ':temporal-sdk': Plugin name.remal.check-dependency-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc...
project ':temporal-sdk': Plugin name.remal.check-gradle-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc...
> Configure project :temporal-serviceclient
project ':temporal-serviceclient': Plugin name.remal.check-updates is deprecated: Use automatic dependency updates software like Renovate, Dependabot, etc... …
```
> Updating dependencies

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
Similarly to [this PR](https://github.com/temporalio/sdk-go/pull/370) in go SDK adds [keep alive](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) to java sdk. For more details please read summary of the above mentioned PR.
> Add keep alive to gRPC connection

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
This approach should make it safer for our users and allow us time to test the feature before we enable it by default.
> Make keep alive configurable and opt-in

- temporal-sdk/src/test/java/io/temporal/workflow/AsyncRetryOptionsChangeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/AsyncRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/AwaitTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildAsyncLambdaWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildAsyncWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowAsyncRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowCancellationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowExecutionPromiseHandlerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowTimeoutTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowWithCronScheduleTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/NamedChildTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/NonSerializableExceptionInChildWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/StartChildWorkflowWithCancellationScopeAndCancelParentTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/UntypedChildStubWorkflowAsyncInvokeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/UntypedChildStubWorkflowAsyncTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/UntypedChildStubWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowWithCronScheduleTest.java
Part of Workflowtest Refactor task: This test file was 7k lines long and contained dozens of tests. 
In addition to readability breaking it up will also enable Gradle to run all those tests in parallel.
> Workflowtest Refactoring: Child tests and a few others

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowClientInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/ChildWorkflowRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTest.java
PR #382 had a typo with method ```#workflowClientCallsInterceptor``` named ```workflowClientClassInterceptor```. 
This PR fixes the mistake.
> Fix a typo in workflowClientCallsInterceptor() method name introduced in #382

- temporal-sdk/src/main/java/io/temporal/common/interceptors/ActivityInboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ChildWorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
This PR moves generation of child `workflowId` into `ChildWorkflowStubImpl` the same way it's done in WorkflowStubImpl: 
https://github.com/temporalio/sdk-java/blob/c802327089fe63694e1baca059a750e970d90b72/temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java#L109
This makes child workflowId known and available for Outbound Interceptors
> Make child workflowId available for Interceptors

- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
`TestWorkflowRule#Builder#setWorkerFactoryOptions` right now returns void which is a valid setter, but it supposes to be a builder method. This PR fixes the signature of this method in compliance with Builder contract and to be consistent with other setters of TestWorkflowRule#Builder.
> Fix TestWorkflowRule#Builder#setWorkerFactoryOptions method signature in accordance with Builder interface

- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
`TestWorkflowService#continueAsNew` now uses header from the original `StartWorkflowExecutionRequest` for the new `StartWorkflowRequest`.
Headers are kinda hidden input parameters (or a context) of the workflow and should be transferred into the new execution without omitting.
Issue #420
> Make TestWorkflowService#continueAsNew respect headers of the original StartWorkflowExecutionRequest

- temporal-sdk/src/main/java/io/temporal/client/WorkflowException.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowServiceException.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/interceptorsTests/InterceptorsExceptionsTests.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
Address the problem with `WorkflowStubImpl#startWithOptions` and `WorkflowStubImpl#signalWithStartWithOptions` passing `workflowExecution` that could be not initialized into NotNull `workflowExecution` param of `WorkflowServiceException` constructor
Preserves an original exception from an Interceptor if it happens instead of replacing it with a meaningless NullPointer.
> Fix a potential NullPointer in exception processing inside WorkflowStubImpl

- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowClientCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/LocalActivityTest.java
- temporal-opentracing/src/test/resources/logback-test.xml
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java
Add a test for tracing LocalActivity
Activate start spans in outbound interceptors to bind with underlying GRPC spans if GRPC client is instrumented
If GRPC client is instrumented with OpenTracing - we don't want to lose its spans.
> Activate OpenTracing Start Spans to bind with potential underlying GRPC spans

- temporal-sdk/src/test/java/io/temporal/workflow/LocalAsyncCompletionWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MultipleTimersTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/StartChildWorkflowWithCancellationScopeAndCancelParentTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTest.java
We've accumulated a number of flaky tests in here, while we should investigate and fix them properly, it would take some time and having them enabled is counter productive.
I suggest we disable most influencing ones and create a task for the follow up.
We should be able to reproduce these failures locally using docker compose configuration for inducing network delays that was recently added in our core images.
> Disable flaky tests until they are fixed

- temporal-sdk/src/main/java/io/temporal/common/reporter/MicrometerClientStatsReporter.java
`MicrometerClientStatsReporter` no longer sets `namingConvention` on the `MeterRegistry` passed to it.
The `MeterRegistry` passed to the `MicrometerClientStatsReporter` might have some naming convention already set, and the creation of `MicrometerClientStatsReporter` would override it.
Also, the `snakeCase` convention is the default one for any `MeterRegistry`, so an explicit set would only be required if specific registry sets some other convention, in which case it might make sense to keep it as it.
1. Closes issue: fixes #432
2. How was this tested: unit test; ran client application with the altered version of `MicrometerClientStatsReporter`.
> Do not override Micrometer's naming conventions

- temporal-sdk/src/main/java/io/temporal/activity/LocalActivityOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ExecuteLocalActivityParameters.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/LocalActivityStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/LocalActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/BinaryChecksumSetWhenTaskCompletedTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/UpsertSearchAttributesTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTaskFailureBackoffTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTaskNPEBackoffTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AbandonOnCancelActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityAndQueryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowCancellationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/StartChildWorkflowWithCancellationScopeAndCancelParentTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/SDKTestWorkflowRule.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionSameIdOnReplayTest.java
Changes to the MarkerRecordedEvent details map.
1. Added "input" that contains activity arguments. Can be disabled through `LocalActivityOptions.doNotIncludeArgumentsIntoMarker` to reduce history size.
2. Added "type" that contains the activity type name.
3. Renamed "data" to "result" for activity result.
Also did refactoring of unit tests to reduce repetitive code.
Debugging local activities is hard as their type and arguments are not part of the event history.
Fix for https://github.com/temporalio/sdk-java/issues/135.
Looking for the "input" field in the UI.
> Local type

- .buildkite/pipeline.yml
- .gitmodules
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionAndTimerTest.java
This should address the problem described [here](https://github.com/temporalio/sdk-java/pull/447#issuecomment-828912253) by setting current workflow time before command processing happens. Before this change it was possible to trigger event loop before correct time was set, which means that workflow code would see the previous time instead of a new one.
Here we simply move `setCurrentTimeMillis(currentTimeMillis)` to the top of the `workflowTaskStarted` function. Thanks to  @GreyTeardrop for contributing a test that reproduces an issue, which I've included here.
> Set current time before processing commands

- temporal-testing/build.gradle
- temporal-testing/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java
- temporal-testing/src/test/java/resources/logback-test.xml
The unit test time skipping was double-locking clock when scheduling a workflow task if there was already an outstanding workflow task.
Fixes https://github.com/temporalio/sdk-java/issues/459.
A unit test that reproduced the problem was added.
> Test env sleep

- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
Execution flow in `WorkflowExecutionUtils#getInstanceCloseEvent` has been fixed to don't allow falling into an infinite `continue` cycle described in Issue #471.
Issue #471
> Fixed implementation of WorkflowExecutionUtils#getInstanceCloseEvent that previously could get into infinite loop after a timeout

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
Code in Worker's `Poller` and `PollerTask`s was cleaned up to one unified way of handling `InterruptedException`.
Before `LocalActivityPollTask` and `ActivityPollTask` had a full mix of correct and incorrect handling of `InterruptedException`:
- It was swallowed and ignored
- it was replaced with RuntimeException
- interrupted flag was raised (the only correct way and Pollers got it through GRPC stub implementation)
See [the article](https://dzone.com/articles/how-to-handle-the-interruptedexception for more context.) for more context about appropriate ways of handling `InterruptedException`.
Now `PollerTask`s are refactored to one approach (same as GRPC) - raising interrupted flag. And `Poller` was refactored to the more explicit way of handling interruptions.
This PR also includes a …
> Cleanup the way Pollers handle InterruptedExceptions

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/common/HeaderUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/internal/common/InternalUtilsTest.java
- temporal-sdk/src/test/java/io/temporal/internal/common/SearchAttributesUtilTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/SyncWorkflowContextTest.java
Custom data converters used with search attributes and memo result in failures down the line when we try to put data into ES.
Proposal that may address https://github.com/temporalio/sdk-java/issues/468
> Use default data converter for search attributes and memo

- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing-junit5/src/main/java/io/temporal/testing/TestWorkflowExtension.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-testing/src/main/java/io/temporal/testing/TestEnvironmentOptions.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentInitialTimeTest.java
Add a new `initialTime` attribute to the `TestEnvironmentOptions` and expose it via `TestWorkflowRule` and `TestWorkflowExtension`. If set, that attribute specifies the initial time to use for the workflow virtual clock.
The current behavior to use current system time as the initial workflow time is kept as a default.
This change enables testing wall clock time-sensitive workflow logic, specifically workflows that are sensitive to the time they are started at. At the moment the time skipping is locked until the workflow is started, and the time the workflow time is set to the current system time, so there's no easy way to test how the workflow behaves if it's e.g. started at the midnight etc.
1. Closes issue: -
2. How was this tested: unit test.
3. Any docs updates needed? Javadocs are …
> Option to set initial time for workflow test

- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
Before:
```
> Task :temporal-sdk:checkDependencyUpdates
New dependency version: com.google.code.gson:gson: 2.8.6 -> 2.8.7
> Task :temporal-serviceclient:checkDependencyUpdates
New dependency version: com.google.protobuf:protobuf-java-util: 3.17.0 -> 3.17.1
New dependency version: com.google.protobuf:protoc: 3.17.0 -> 3.17.2
New dependency version: com.uber.m3:tally-core: 0.6.1 -> 0.10.0
New dependency version: io.grpc:grpc-core: 1.37.1 -> 1.38.0
New dependency version: io.grpc:grpc-netty-shaded: 1.37.1 -> 1.38.0
New dependency version: io.grpc:grpc-protobuf: 1.37.1 -> 1.38.0
New dependency version: io.grpc:grpc-stub: 1.37.1 -> 1.38.0
New dependency version: io.grpc:protoc-gen-grpc-java: 1.37.1 -> 1.38.0
```
After:
```
> Task :temporal-serviceclient:checkDependencyUpdates
New dependency …
```
> Update dependencies to latest

- releases/v1.0.8
Release v1.0.8 highlights:
- Option to set default ActivityOptions and per activityType. Can be done
- through the activityStub, WorkflowImplementationOptions, and on a workflow.
- Added context propagation for local activities
- Option to set initial time for workflow tests
- Implemented a Health Check. By default it's on and checks if the server is up
- every 5s. If the server is not up in 10s, the worker will not start.
> Release v1.0.8

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/HealthCheckTest.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
This PR fixes small typos and semantic issues with the health check feature introduced in version 1.0.8.
1. It seems like the property named `disableHealthCheck` actually enabled health checks. The `HealthCheckTest` used to pass as the `service.checkHealth("IncorrectServiceName")` method did nothing when `disableHealthCheck` was `false`.
2. There's a typo in `WorkflowServiceStubsOptions.Builder`'s method name for `healthCheckAttemptTimeout`.
3. `WorkflowServiceStubsOptions` checks wrong attribute for `null` before assigning default value for `healthCheckAttemptTimeout`.
4. In-memory service does not support health checks so `TestWorkflowService`, `TestWorkflowEnvironmentInternal`, and `TestActivityEnvironmentInternal` have to disable it.
I've noticed these issues while exposing new …
> Fix health check attributes

- temporal-testing-junit4/build.gradle
- temporal-testing/build.gradle
slf4j-simple was removed from the api scope of temporal-testing
The temporal-testing module was declaring slf4j-simple in api scope, resulting
in any consumers having slf4j on their compile and runtime classpaths. Previously
there was a gradle dependency configuration rule to remove that dependency, but
I mistakenly removed that during the gradle refactoring changes in 521a992 without
noticing it in the test classpaths.
This change moves the dependency to testRuntimeOnly so that temporal-testing has
logging configured for test execution, and adds it to temporal-testing-junit4 as
testRuntimeOnly as well.
Other consumers for temporal-testing were already explicitly declaring testImplementation
dependencies on logback-classic.
1. How was this tested:
* ensured sdk still builds and tests pass …
> Removes slf4j-simple from api scope of temporal-testing

- temporal-testing-junit5/build.gradle
- temporal-testing-junit5/src/main/java/io/temporal/testing/TestWorkflowExtension.java
* Add option to set `WorkerFactoryOptions` override to the JUnit 5 extension
* Re-enable JUnit 5 tests that were not executing after https://github.com/temporalio/sdk-java/pull/513
JUnit 4 rule has an option to set `WorkerFactoryOptions` but JUnit 5 extension does not. Discovered that while trying to test an activity interceptor.
1. Closes issue: -
2. How was this tested: locally + unit tests
3. Any docs updates needed? -
> Add workerFactoryOptions override to the JUnit 5 extension

- temporal-sdk/src/main/java/io/temporal/activity/Activity.java
- temporal-sdk/src/main/java/io/temporal/activity/ActivityCancellationType.java
- temporal-sdk/src/main/java/io/temporal/activity/ActivityInfo.java
- temporal-sdk/src/main/java/io/temporal/activity/ActivityMethod.java
- temporal-sdk/src/main/java/io/temporal/activity/LocalActivityOptions.java
Javadocs cleaned up in several classes in the Activity package
We didn't want implementation and duplicate docs (that exist in the main doc site) to be in the Javadocs as well.
https://www.notion.so/temporalio/Refresh-Java-SDK-reference-comments-819b790f4acd46c3a5d908dc0226aa15
Tested locally, looking at the Javadocs view feature in IntelliJ
There were a few small edits I made to the documentation page after comparing Javadocs and documentation
https://github.com/temporalio/documentation/pull/378
> Cleaning up Activity Javadocs

- temporal-sdk/src/main/java/io/temporal/internal/worker/NoopSuspendableWorker.java
`NoopSuspendableWorker` no longer throws `IllegalStateException`s when `suspendPolling()` or `resumePolling()` is called.
`LocalActivityWorker` does not create a "real" poller if no activity implementations are added to the parent worker.  It also does not guard against calling `suspendPolling()` or `resumePolling()` on the noop poller.  As this seems like an implementation detail that users of the library should not need to know about, throwing an exception is probably not the best move here; since it is a noop implementation, it should probably just do nothing.
Untested, but given the limited number of places where these methods are called, this seems like a safe change, unless there is a specific reason why this needs to throw that I'm not aware of.
> Avoid throwing IllegalStateException in NoopSuspendableWorker

- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Added getWorker method to TestWorkflowRule.
Currently if you have multiple tests where you want to register different activities (one might use real activities impl and another test might want to use a mock for example) you have to do:
TestWorkflowRule.newBuilder()
.setWorkflowTypes(GreetingWorkflowImpl.class)
.setDoNotStart(true)
.build();
and then in each test method to register activity:
workflowRule
.getTestEnvironment()
.getWorkerFactory()
.getWorker(workflowRule.getTaskQueue())
.registerActivitiesImplementations(new GreetingActivitiesImpl());
This adds a convenience getWorker method so registering activities in test methods can be just
workflowRule.getWorker().registerActivitiesImplementations(new GreetingActivitiesImpl());
1. …
> Add getWorker method to TestWorkflowRule

- temporal-opentracing/build.gradle
- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
> Task :temporal-opentracing:checkDependencyUpdates
New dependency version: org.mockito:mockito-core: 3.10.0 -> 3.11.0
> Task :temporal-sdk:checkDependencyUpdates
New dependency version: org.mockito:mockito-core: 3.10.0 -> 3.11.0
> Task :temporal-serviceclient:checkDependencyUpdates
New dependency version: com.google.protobuf:protobuf-java-util: 3.17.1 -> 3.17.3
New dependency version: com.google.protobuf:protoc: 3.17.2 -> 3.17.3
New dependency version: com.uber.m3:tally-core: 0.6.1 -> 0.10.0
New dependency version: org.mockito:mockito-core: 3.10.0 -> 3.11.0
> Dependency Update

- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
Poller logs InterruptedException only at debug-level.
Graceful worker shutdown should result in no errors in application logs.
1. Closes #521
> Change InterruptedException logs to debug-level.

- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
Polished handling of InterruptedExceptions of all kinds in Poller during shutdown.
Added exclusion of GRPC wrapped InterruptedExceptions logging in Poller during shutdown.
A follow-up to #533
Closes #521
> Added exclusion of GRPC wrapped InterruptedExceptions logging in Poller during shutdown

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/TerminatedWorkflowQueryTest.java
* Add test that reproduces the issue - set shorter workflowRunTimeout than the activity needs to complete.
* The EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT seems harmless, so exception is suppressed.
Added a test that reproduces the issue.
Modified `WorkflowStateMachines` to ignore `EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT` instead of throwing the exception (inspired by go-sdk that generally "does not fail to be forward compatible with new events").
I encountered this issue myself and found out it's already on github.
It happens when `@QueryMethod` is called on a terminated workflow. In my case the workflow has been terminated, because `workflowRunTimeout` has expired when activity was still running.
I decided to ignore the event instead of throwing an exception, because go-sdk does not …
> Query failure on terminated workflow (#391)

- temporal-sdk/src/main/java/io/temporal/worker/WorkflowImplementationOptions.java
Added an annotation that fixes this warning in java-canary:
warning: [unchecked] unchecked generic array creation for varargs parameter of type Class<? extends Throwable>[]
.setFailWorkflowExceptionTypes(Throwable.class)
> Java-canary warning fix

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
Cancelation happens iff the workflow signaling is the parent.
1. Closes #501 
This bug is very difficult to reproduce - no test so far
> Cancel child fix

- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Issue #455 shows signs that we probably are loosing interrupted exceptions somewhere in the Pollers. This PR doesn't solve the problem completely, but adds some correct handling of InterruptedExceptions in obvious places.
This eliminates other potential problems and decreases the search space for the flaky test in Issue #455 for everybody.
> Add correct handling of interrupted exceptions in an attempt to improve problem of Issue #455

- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- maxWorkerActivitiesPerSecond
- maxConcurrentActivityExecutionSize
- maxConcurrentWorkflowTaskExecutionSize
- maxConcurrentLocalActivityExecutionSize
Zero is a valid default value for these configs, and not allowing zero to be passed here makes WorkerOptions both less extensibile and limits our ability to use dynamic configuration when tweaking these values
> Allow zero value on some worker options values

- temporal-sdk/src/main/java/io/temporal/internal/sync/PotentialDeadlockException.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
This PR improves javadocs as a follow up to PR #563 that changes acceptable values of `WorkerOptions.Builder`
> Cleanup javadoc as a follow-up to PR #563

- releases/v1.1.0.txt
Release v1.1.0 highlights:
- Add getWorker method to TestWorkflowRule
- Avoid throwing IllegalStateException in NoopSuspendableWorker
- mplement configurable DEFAULT_DEADLOCK_DETECTION_TIMEOUT
- Added exclusion of GRPC wrapped InterruptedExceptions logging in Poller during shutdown
- Pluggable span naming
- Cancel child fix
- Allow zero value on some worker options values
> Release v1.1.0

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowQueueImpl.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalQueueTest.java
`WorkflowQueue.take` does not preserve queue semantics by taking elements from the tail of the queue (the most recently added ones) instead of its head (the earliest added ones).
Let `WorkflowQueue` maintain the expected queue semantics.
1. Closes -
2. How was this tested: new unit test
3. Any docs updates needed? -
> WorkflowQueue.take takes element from the tail of the queue instead of its head

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowQueueDeprecatedImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalDeprecatedQueueTest.java
A follow-up to #569 to preserve backward compatibility with existing workflows.
New fixed implementation of `WorkflowQueue` is exposed in a new `Workflow.newWorkflowQueue` method preserving the behavior of the old `Workflow.newQueue` implementation, which is marked as deprecated now.
#569 fixes implementations of some methods of WorkflowQueueImpl but does it in a backward-incompatible way with existing workflows that could be not replayable after that.
> Expose a fixed implementation of WorkflowQueue as a new method of Workflow class

- temporal-sdk/src/main/java/io/temporal/workflow/QueueConsumer.java
`QueueConsumer#poll` and `QueueConsumer#peek` methods that don't accept Duration as an input have wording about "the specified waiting time" in their Javadoc, while no waiting time is specified for them. This fix makes the Javadoc consistent with the actual behavior of these methods.
> Fix "empty queue" section of javadoc on QueueConsumer#poll and QueueConsumer#peek

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowClientInternal.java
- temporal-sdk/src/test/java/io/temporal/workflow/ProhibitedCallsFromWorkflowTest.java
- temporal-serviceclient/src/main/java/io/temporal/conf/EnvironmentVariableNames.java
- temporal-serviceclient/src/main/java/io/temporal/internal/WorkflowThreadMarker.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubs.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DeterministicRunnerWrapper.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Now the usage of `WorkflowClient`, `ActivityCompletionClient`, and `WorkflowServiceStubs` is prohibited from workflow code.
It's an alternative PR to the original PR #550. 
The main difference is that this PR doesn't rely on magic thread names to understand that we are inside a workflow thread, but a marker utility class was implemented that is published by DeterministicRunner and available to serviceclient code.
It includes a fix for `TestActivityEnvironmentInternal` to execute activities code in a separate thread pool, not in a main thread of DeterministicRunnerImpl to emulate the behavior of our real worker setup and allow a correct work of implemented checks for ActivityCompletionClient (this class is actively used in activities code)
Also, this PR uses proxies to 
- ensure the right …
> Prohibit use of WorkflowClient from workflow code

- .buildkite/pipeline.yml
Now buildkite runs `./gradlew test` which misses checks step happening after tests. This changes it to `./gradlew check`
Now we are missing checks of license headers in buildkite.
> Makes buildkite run ./gradlew check instead of ./gradlew test

- docker/buildkite/docker-compose.yaml
After https://github.com/temporalio/temporal/pull/1740 `temporalio/auto-setup:latest` points to latest release not latest `master` commit.
> Change docker hub repo to temporaliotest

- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowInterfaceMetadata.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalMethodOverloadTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalMethodOverrideTest.java
Added name override from the annotation to equality check.
Previously workflows with overloaded signal functions were not allowed due to the fact that we only used function name as an equality key.
1. Closes #591
2. How was this tested: new unit test
no
> Use method annotation name override for equality check

- temporal-opentracing/build.gradle
- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
- temporal-testing-junit5/build.gradle
- temporal-testing/build.gradle
- temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimer.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java
Fixed an issue with time-skipping during timing out of a not-a-child workflow without a parent.
Also includes some refactorings to use `LockHandle` more extensively to clean up the internal state of `SelfAdvancingTimerImpl`. This makes debugging of time skipping issues easier.
#577
1. Closes #577
`TestWorkflowEnvironmentSleepTest#testWorkflowTimeoutDuringSleep`
> Fixed an issue with time skipping in case of timing out a root (not a child) workflow

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/BlockCallerPolicy.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollWorkflowTaskDispatcher.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowRunLockManagerTest.java
- temporal-sdk/src/test/java/io/temporal/worker/CleanWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerStressTests.java
- temporal-sdk/src/test/java/io/temporal/workflow/DeadlockDetectorTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncActivityRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/interceptorsTests/InterceptorExceptionTests.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/SDKTestWorkflowRule.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestActivities.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalDuringLastWorkflowTaskTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStore.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironment.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
Added a flag to signal that the poller thread was asked to shutdown and replaced the long poll with shorter polls that keep checking that flag.
Thread shutdown is not reliable
1. Closes #455
> Thread shutdown not working correctly in TestEnv

- temporal-testing-junit5/src/main/java/io/temporal/testing/TestActivityExtension.java
- temporal-testing-junit5/src/main/java/io/temporal/testing/TestWorkflowExtension.java
- temporal-testing-junit5/src/main/java/io/temporal/testing/WorkflowInitialTime.java
- temporal-testing-junit5/src/test/java/io/temporal/testing/TestActivityExtensionDynamicTest.java
- temporal-testing-junit5/src/test/java/io/temporal/testing/TestActivityExtensionTest.java
- temporal-testing-junit5/src/test/java/io/temporal/testing/TestWorkflowExtensionDynamicTest.java
- temporal-testing-junit5/src/test/java/io/temporal/testing/TestWorkflowExtensionTest.java
* The `TestWorkflowExtension` is changed to support per-test overrides for the virtual time used by the `TestWorkflowEnvironment`.
* Somewhat unrelated, the extension code is polished a bit: the whole `WorkflowOptions` is stored in the extension context instead of just the task queue name, to reduce some code duplication.
* Extend `TestWorkflowExtension` and `TestActivityExtension` to support dynamic workflow/activity scenarios.
One of our workflows has time-sensitive logic and we'd like to test it in multiple scenarios that differ in the initial workflow time. Right now we either have to fall back to manually managing `TestWorkflowEnvironment` or to split those scenarios into multiple test classes.
1. **Closes** —
2. **How was this tested:** extended existing unit test
3. **Any docs …
> Polish JUnit5 extension: per-test initial time, dynamic workflows and activities

- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowWithCronScheduleTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowWithCronScheduleTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflowWithCronScheduleImpl.java
- temporal-testing/build.gradle
Added an array that records lastCompletionResult for every run.
Couldn't guarantee how many runs the cron workflow would perform, hence relying on timers to get the lastCompletionResult of the correct run was not working consistently
> Flaky test: testChildWorkflowWithCronSchedule

- temporal-opentracing/src/main/java/io/temporal/opentracing/OpenTracingOptions.java
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Changed the signature of the OpenTracingOptions.SpanBuilderProvider setTracer method
This is done so we can use the builder approach to set both the tracer and the span builder provider (the same way)
1. Closes 
> Fix OpenTracingOptions.SpanBuilderProvider setTracer method

- releases/v1.2.0
Release v1.2.0 highlights:
- ProtobufJsonPayloadConverter is fixed to use custom printer provided in constructor (#552)
- Expose a fixed implementation of WorkflowQueue as a new method of Workflow class (#572)
- Forbid the usage of WorkflowClient, ActivityCompletionClient, and WorkflowServiceStubs from workflow code (#556)
- Polish JUnit5 extension: per-test initial time, dynamic workflows and activities (#581)
> Release v1.2.0

- temporal-opentracing/build.gradle
- temporal-opentracing/src/main/java/io/temporal/opentracing/OpenTracingClientInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/OpenTracingOptions.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/OpenTracingSpanContextCodec.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/OpenTracingWorkerInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/codec/TextMapCodec.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/codec/TextMapInjectExtractCodec.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ActionTypeAndNameSpanBuilderProvider.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ContextAccessor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingActivityInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowClientCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/provider/DataDogOpenTracingSpanBuilderProvider.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/integration/JaegerTest.java
Added configurable `OpenTracingSpanContextCodec` to `OpenTracingOptions` and two implementations. 
One default: `TextMapInjectExtractCodec` that implements the old original behavior
One new: `TextMapCodec` that implements encoding using OpenTracing's TEXT_MAP Format.
Jeager doesn't support `TEXT_MAP_INJECT` and `TEXT_MAP_EXTRACT` OpenTracing encoding formats. See https://github.com/jaegertracing/jaeger-client-java/issues/789
To provide a workaround we implement encoding using another strategy.
1. Closes
Issue #621
Jaeger-specific integration test
> Added configurable OpenTracingSpanContextCodec to OpenTracingOptions

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowInboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/AsyncInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/BaseRootWorkflowInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DynamicSyncWorkflowDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThread.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/PromiseTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalDeprecatedQueueTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalQueueTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/interceptors/SignalWorkflowOutboundCallsInterceptor.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/TracingWorkerInterceptor.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DeterministicRunnerWrapper.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Refactored workflow root thread into a separate code path making it explicitly different from workflow-method thread and child workflows.
Added WorkflowInboundCallsInterceptor#newWorkflowMethodThread intercepting creation of the main workflow-method thread.
Added WorkflowInboundCallsInterceptor#newCallbackThread intercepting creation of a callback thread.
WorkflowOutboundCallsInterceptor#newThread is renamed into WorkflowOutboundCallsInterceptor#newChildThread and now it intercepts only new workflow child threads and doesn't intercept creation of the main workflow-method thread.
Fixed situation that the same "workflow-method" name was used for workflow initializer thread (now called "workflow-root") and for the thread that is used to run a workflow method (continued to be …
> Rework how DeterministicRunnerImpl and SyncWorkflowContext handle creation of workflow root and method threads

- temporal-sdk/src/main/java/io/temporal/common/converter/DefaultDataConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- Clarification of javadocs around DataConverters and WorkflowContext classes
- Code style fixes
- Spelling/grammar errors
- Google formatting
> Code style improvements around DataConverters and WorkflowContext

- temporal-sdk/src/main/java/io/temporal/internal/common/DebugModeUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/test/java/io/temporal/workflow/DeadlockDetectorTest.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
We now don't apply `globalTimeout` in `TestWorkflowRule` in case an explicit `@Test(timeout)` is provided.
We now also don't enforce `globalTimeout` if TEMPORAL_DEBUG env variable is set.
Now during breakpoints-based debugging, there is no way to turn off the default 10 seconds limit which is annoying and hurts productivity.
Also, there is no reason to enforce global timeout if the test has a timeout specified on a test level, we always should prioritize more specific settings.
Resolves #632, resolves #612
> Stop enforcing TestWorkflowRule timeout when run in JVM debug mode, respect JUnit(timeout) over TestRule timeout

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
Fixed unsafe publishing and access to `WorkflowThreadImpl#thread` by refactoring it out and using `WorkflowThreadContext#currentThread`
`WorkflowThreadContext#currentThread` is published and exposed in a thread-safe way
Deadlock detection code checks the thread status after waking up to ensure that it's in a correct state and the state didn't change between the wait timeout and acquiring the lock back.
1. Closes #641
> Fix misc thread safety issues with WorkflowThreadContext

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/PromiseTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalDeprecatedQueueTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalQueueTest.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DeterministicRunnerWrapper.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Remove constructor of DeterministicRunner that creates a ThreadPool inside without ever closing it. This constructor was used in tests only.
Removes test-only code from the main codebase and improve resources management in tests
> Cleanup DeterministicRunner constructors to improve resource management

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/EntityStateMachineBase.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/MutableSideEffectStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/StateMachineCommandUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/VersionStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/AsyncWorkflowBuilder.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/AsyncWorkflowBuilderImpl.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/TestEntityManagerListenerBase.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/VersionStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestActivities.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionAfterScopeCancellationTest.java
`WorkflowStateMachines` now handles a situation with Versioning `EVENT_TYPE_MARKER_RECORDED` matching a commands buffer containing canceled commands correctly (by consuming and skipping them)
The current implementation fails to match a Versioning `EVENT_TYPE_MARKER_RECORDED` History Event with a right command if there are canceled commands before it in the commands sink. This is a root cause of an issue described in  Issue #583.
1. Closes
PR #583
Issue #615
> Fix handling of Version events in WorkflowStateMachines in case of cancelled commands in a queue

- temporal-sdk/src/main/java/io/temporal/failure/ApplicationFailure.java
ApplicationFailure#newFailureWithCause and ApplicationFailure#newNonRetryableFailureWithCause had been added.
ApplicationFailure supports having an underlying cause, but there is no public API to construct it with an underlying clause other than using `Throwable#initCause` after `ApplicationFailure` is already created.
1. Closes #647
> Add newFailureWithCause and newNonRetryableFailureWithCause to ApplicationFailure that allow to setup cause field

- temporal-sdk/src/main/java/io/temporal/activity/ActivityExecutionContext.java
* Correct Heartbeat spelling in ActivityExecutionContext
* Capitalize Heartbeat for consistency
missing `r`
> docs: Fix heartbeat spelling in ActivityExecutionContext

- temporal-kotlin/build.gradle
We should build temporal-kotlin with the lowest supported version of Kotlin to give maximum compatibility for our users.
> Downgrade Kotlin to 1.3 for SDK release

- temporal-sdk/src/test/java/io/temporal/authorization/AuthorizationTokenTest.java
- temporal-serviceclient/src/main/java/io/temporal/authorization/AuthorizationGrpcMetadataProvider.java
Just a cleanup of naming for AuthorizationGrpcMetadataProvider constant to make it not JWT specific.
> Cleanup naming inside AuthorizationGrpcMetadataProvider

- temporal-sdk/src/test/java/io/temporal/authorization/AuthorizationTokenTest.java
- temporal-serviceclient/src/main/java/io/temporal/authorization/AuthorizationTokenSupplier.java
Fix NullPointer in a new flaky AuthorizationTokenTest that I can explain only by memory synchronization issues.
> Ensure proper thread safety in AuthorizationTokenTest to fix flaky test

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/HealthCheckTest.java
Health check is now getting called on the intercepted channel, which allows attaching custom headers.
From what Emin Demirci wrote:
```
It seem that the newly introduced healthchecks are not honoring the configured stub interceptors. In case of server requires an authentication and those authentication tokens retrieved via client interceptors, healtcheck mechanism gets unauthorized request errors. 
My suggestion would be either:
* Exclude the healthcheck endpoint from the list of authenticated endpoints
* Change java-sdk to use the intercepted channels while setting up the healthcheck grpc stub instead of the plain one.
```
> Call health check on intercepted channel

- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivitiesWorkflowTaskHeartbeatTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LongLocalActivityWorkflowTaskHeartbeatTest.java
Removed pointless parallel workflows in `testLocalActivitiesWorkflowTaskHeartbeat` and decreased the number of sequential activities to improve the runtime of the test.
Add javadocs to `testLocalActivitiesWorkflowTaskHeartbeat` and `testLongLocalActivityWorkflowTaskHeartbeat`
Closes #693
> Improve testLocalActivitiesWorkflowTaskHeartbeat flakiness

- temporal-sdk/src/test/java/io/temporal/workflow/TerminatedWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/TimerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncRetryOptionsChangeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/StateUtils.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Issue #628 
Don't buffer events and wait till the completion of the workflow task if the workflow was terminated.
Right now if we get a termination request, the test service doesn't flush it to the history and adds to the buffered events.
Which causes #628
Closes #628
> Fix getResult hang after termination using test service

- temporal-sdk/src/main/java/io/temporal/common/converter/EncodingKeys.java
- temporal-sdk/src/main/java/io/temporal/common/converter/PayloadConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/common/HeaderUtils.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
`PayloadConverter` javadoc is improved to provide information about an important `EncodingKeys#METADATA_ENCODING_KEY` functionality that implementers of custom converters should keep in mind.
Minor fixes of formats of javadocs in other classes
`EncodingKeys#METADATA_ENCODING_KEY` made public
> Improve PayloadConverter javadoc regarding providing of EncodingKeys#METADATA_ENCODING_KEY

- temporal-sdk/src/main/java/io/temporal/common/converter/PayloadConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/common/HeaderUtils.java
- temporal-serviceclient/src/main/java/io/temporal/internal/AsyncBackoffThrottler.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryerUtils.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcSyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcAsyncRetryerTest.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcSyncRetryerTest.java
`GrpcRetryer` now retries underlying `DEADLINE_EXCEEDED` if the root gRPC context deadline is not expired
The behavior of `GrpcRetryer` has been changed in java-sdk#1.3.0 that causes potential regressions when `GrpcRetryer` is used with `DeadlineGrpcInterceptor` like described in #708
Closes #708
> GrpcRetryer now retries underlying DEADLINE_EXCEEDED if the root gRPC context deadline is not expired

- temporal-sdk/src/test/java/io/temporal/worker/CleanWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/LongRunningWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestActivities.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/internal/ActiveOnEnvVariableRule.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Test service now enforces 1 Minute timeout on long polls.
Temporal Server enforces 1 Minute timeout on long polls, after which it returns an empty result, and the client is expected to retry the request.
This PR brings Test Service implementation in sync with the main implementation on this aspect. 
Closes #707
`LongRunningWorkflowTest`
> Test service now enforces 1 Minute timeout on long polls

- releases/v1.3.1
Releasing a hotfix version of the SDK.
Includes fix related to handling DEADLINE_EXCEEDED gRPC exception - regression introduced in 1.3.0.
> Release v1.3.1

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollAsyncHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/workflow/MemoTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/SearchAttributesTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubServiceOperationRpcRetryOptions.java
`WorkflowExecutionUtils` is split into `WorkflowExecutionUtils`, `WorkflowClientHelper`, `WorkflowClientLongPollAsyncHelper`, `WorkflowClientLongPollHelper`.
`WorkflowExecutionUtils` is a large class without a single specific function.
`WorkflowExecutionUtils` is split to
- `WorkflowExecutionUtils` - utility methods helping with all kinds of statuses, internal structures, etc. Intended to be a collection of small static utility methods.
- `WorkflowClientLongPollAsyncHelper` and `WorkflowClientLongPollHelper` - Async and Sync implementations of Long Poll to hide inherent complexity of retries and other machinery of our workflow state polling. Used only by `RootWorkflowClientInvoker` and basically encapsulate pieces of `RootWorkflowClientInvoker`, so made package-local.
- …
> WorkflowExecutionUtils refactoring

- temporal-sdk/src/main/java/io/temporal/internal/common/DebugModeUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/common/env/EnvironmentVariablesProvider.java
- temporal-sdk/src/main/java/io/temporal/internal/common/env/SystemEnvironmentVariablesProvider.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThread.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/PromiseTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalDeprecatedQueueTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalQueueTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/DeadlockDetectorTest.java
Check for isTemporalDebugModeOn was moved down into `WorkflowThreadContext#runUntilBlocked` so it can't be forgotten by the calling code.
We have a missing check for `isTemporalDebugModeOn` in `SyncWorkflow#eventLoop`, so the main event loop doesn't overwrite deadline detection timeout when it should. Instead of fixing this one usage, it's a good idea to move the check to the lower level, so the calling code doesn't have to check the flag explicitly every time.
Closes #724
> Move check for isTemporalDebugModeOn down to WorkflowThreadContext#runUntilBlocked to avoid missing checks on the calling side

- temporal-sdk/build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/common/HistoryJsonUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/test/resources/testAsyncActivityRetryHistory.json
- temporal-sdk/src/test/resources/testChildWorkflowRetryHistory.json
- temporal-testing-junit4/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
Now WorkflowReplayer and other replaying functionality work with tctl format of the history.
Added transformation of "Proto Json" to our TCTL History Json and back.
To make JavaSDK compatible with the tctl version of history.
Closes #300
> Support tctl format of history

- temporal-sdk/src/test/java/io/temporal/internal/testservice/SelfAdvancingTimerImplTest.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
Switch SelfAdvancingTimerImplTest to use fixed clock to reduce flakes and improve the quality of checks
SelfAdvancingTimerImpl now updates the time before scheduling
Fixed mocked clock remove test flakes that could happen because of the load.
It also improves the quality of the test, switching to the fixed clock allowed to catch a problem that `SelfAdvancingTimerImpl#schedule` could use an outdated timestamp.
Closes #726
> Switch SelfAdvancingTimerImplTest to use fixed clock to reduce flakes and  improve the quality of checks

- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowExecuteRunnable.java
- temporal-sdk/src/test/java/io/temporal/workflow/DynamicWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LongLocalActivityWorkflowTaskHeartbeatFailureTest.java
DynamicWorkflow was missing appropriate error handling. Moved error handling from POJOWorkflowImplementationFactory to WorkflowExecuteRunnable to cover both POJO and DynamicWorkflow implementations.
1. Closes https://github.com/temporalio/sdk-java/issues/716
2. How was this tested: Added a unit test to check that DynamicWorkflow fails correctly.
> Add error handling for dynamic workflow failure

- temporal-sdk/src/test/java/io/temporal/workflow/LargeHistoryTest.java
`LargeHistoryTest` is unignored.
The test is ignored without an obvious reason for that.
> LargeHistoryTest is unignored

- temporal-kotlin/src/test/kotlin/io/temporal/workflow/KotlinAsyncChildWorkflowTest.kt
- temporal-kotlin/src/test/kotlin/io/temporal/workflow/KotlinAsyncCompanionFunctionTest.kt
- temporal-kotlin/src/test/kotlin/io/temporal/workflow/KotlinAsyncLambdaTest.kt
- temporal-opentracing/src/test/java/io/temporal/opentracing/ActivityFailureTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/CustomSpanNamingTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/LocalActivityTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/NoClientSpanTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/SpanContextPropagationTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/WorkflowReplayTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/WorkflowRetryTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/integration/JaegerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowRetryAfterActivityFailureTest.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/internal/SDKTestOptions.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
TestWorkflowRule#setTestTimeoutSeconds is deprecated and transformed to noop.
Existing timeout logic is moved to SDKTestWorkflowRule and should be used only in internal Temporal tests.
Also moved handy   `newWorkflowStub(Class<T> workflow)` and `newUntypedWorkflowStub(String workflow)` from SDK TestWorkflowRule to TestWorkflowRule, because they can be handy for our users.
As described in #634, Temporal Test rule shouldn't reimplement basic unit test framework functionality. And default timeout of 10 seconds could be annoying for users in some cases because users have to find a way to disable it.
1. Closes #634
> User-facing TestWorkflowRule doesn't enforce test timeouts anymore

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollAsyncHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollHelper.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LongLocalActivityWorkflowTaskHeartbeatFailureTest.java
Remove unused methods that are full duplicates of used methods
Reuse code and properties between Sync and Async versions to keep them consistent
Async version now calls the long poll with waitForNewEvents = true and updated retry options.
> Cleanup LongPoll code and update Async version

- temporal-kotlin/src/test/resources/logback-test.xml
During docker build the log is filled with netty output during the build of kotlin module.
Adding our standard test logback config to decrease verbosity of tempotal-kotlin build with docker.
> Add logback-test to kotlin module to decrease verbosity of building logs on docker from netty

- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionAfterScopeCancellationTest.java
`GetVersionAfterScopeCancellationTest` before was required time skipping and didn't work against the dockerized Temporal.
`GetVersionAfterScopeCancellationTest` is adjusted to succeed against dockerized Temporal.
> Adapt GetVersionAfterScopeCancellationTest so it runs against external docker without time skipping

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentCreationTest.java
Setting target to null when channel is set in the test workflow environment options.
When you call validateAndBuildWithDefaults on TestEnvironmentOptions builder it creates default service options with default target address, which then gets passed to the WorkflowServiceStubsImpl that also adds a channel for the in-memory service, which causes the error you are seeing (both target and channel set). 
1. Closes #749
Added a unit test similar to the one provided by the user.
No
> Remove target when setting channel in workflow test environment options

- temporal-sdk/src/main/java/io/temporal/activity/ActivityCancellationType.java
- temporal-sdk/src/main/java/io/temporal/activity/ActivityOptions.java
- temporal-sdk/src/test/java/io/temporal/workflow/DetachedScopeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/HeartbeatTimeoutDetailsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/SyncTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AbandonOnCancelActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncActivityWithCompletionClientTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncUsingActivityStubUntypedActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncUsingAsyncUntypedActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/TryCancelActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestActivities.java
Activities using completionClient and a thread pool for delayed execution were moved into a separate activities class `CompletionClientActivities` to optimize resource management in tests.
Add clean shutdown for this new activity instance in tests that use it.
Add guards checking that this new `CompletionClientActivities` is correctly initialized by tests code to prevent NullPointer flaky errors.
Closes #756
> Fix AbandonOnCancelActivityTest flake

- temporal-sdk/src/test/java/io/temporal/internal/sync/CheckedExceptionWrapperTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/failure/WorkflowFailureNonRetryableFlagTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/failure/WorkflowFailureNonStandardThrowableTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/CheckedExceptionWrapper.java
Adapt CheckedExceptionWrapper to Throwables that are not Exceptions and Errors
If workflow throws a Throwable that is not an exception or error, we get an internal failure instead of graceful processing.
Closes #744
Unit tests with a custom throwable
> Adapt CheckedExceptionWrapper to Throwables that are not Exceptions and Errors

- temporal-serviceclient/src/main/java/io/temporal/authorization/AuthorizationGrpcMetadataProvider.java
The constructor of `AuthorizationGrpcMetadataProvider` is made public so users can instantiate it. 
Closes #762
> Expose AuthorizationGrpcMetadataProvider constructor

- build.gradle
- temporal-sdk/build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/common/HistoryProtoTextUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
- temporal-testing/build.gradle
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
The current version of prettyPrint is very verbose and hard to navigate. This change makes test history print much more manageable.
> Beautify the output of prettyPrint for history to make test histories much easier to read

- temporal-sdk/src/main/java/io/temporal/internal/common/HistoryProtoTextUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/CancellableCommand.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/EntityStateMachineBase.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/EntityStateMachineInitialCommand.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/FixedTransitionAction.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/StateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/StateMachineDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/TimerStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowTaskStateMachine.java
- temporal-sdk/src/test/resources/logback-test.xml
- temporal-testing-junit4/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
- temporal-testing/src/main/java/io/temporal/testing/WorkflowReplayer.java
These changes are taken from the branch related to investigation and fixes of #648 to keep that branch and future PR clean and easy to follow.
This PR includes various helper logging and functions that could be helpful with state machine debugging.
Including:
- improved states transition logging
- included optional entityName into state machines for concise debug prints
- methods helping with getting a workflow history 
- methods helping with replaying workflow history in tests using TestRule
> Various debugging utils developed during state machine bug investigation

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/HealthCheckTest.java
`HealthCheckTest` assumes that Temporal server is available on default location only (127.0.0.1:7233)
This doesn't work with our buildkite setup where Temporal is available on temporal:7233
This PR uses `TEMPORAL_SERVICE_ADDRESS` env var to get Temporal Server URL in `HealthCheckTest` as it's done in other places.
> Fix HealthCheckTest to run with dockerized buildkite environment

- temporal-sdk/src/test/java/io/temporal/activity/DefaultActivityOptionsSetOnWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityThrowingErrorTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowWithCronScheduleTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionAndTimerTest.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/internal/SDKTestOptions.java
`ActivityThrowingErrorTest` flakes in a build with dockerized Temporal with a timeout.
Fix retry options to don't waste time in retries.
> Fix flaky ActivityThrowingErrorTest

- temporal-sdk/src/test/java/io/temporal/workflow/DescribeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/IdentityInPendingActivityTest.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Added test that demonstrates that identity is missing from pending activities.
identity is missing from pending activities -- probably server issue
1. Closes #766
> Identity for pending activity comes from pollRequest in TestService

- docker/buildkite/docker-compose.yaml
- temporal-sdk/src/test/java/io/temporal/workflow/IdentityInPendingActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncActivityRetryOptionsChangeTest.java
Enable IdentityInPendingActivityTest for Dockerized Temporal that was disabled by mistake in #784
Fix flaky AsyncActivityRetryOptionsChangeTest for Dockerized Temporal
> Enable IdentityInPendingActivityTest for Dockerized Temporal

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
Use ReplayAwareScope for metric reporting to address #759
Remove duplicate STICKY_CACHE_THREAD_FORCED_EVICTION reporting to address #201
Closes #759 
Closes #201
> Use ReplayAwareScope to don't double report completion on replays, fix STICKY_CACHE_THREAD_FORCED_EVICTION double reporting

- build.gradle
- temporal-sdk/build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
Upgrade gson dep to the last version and switch to using a version range.
Rework `WorkflowExecutionHistory` onto using deprecated APIs but that support a much larger range of versions.
> Upgrade gson dep to the last version and switch on using a version range

- temporal-kotlin/build.gradle
Changes the dependency in temporal-kotlin on temporal-sdk to be `api` instead of `implementation`
To prevent needing to define both dependencies explicitly as a user.
> Updates temporal-sdk dep in temporal-kotlin

- README.md
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/cancellation/CancellingScheduledActivityTest.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Add a test covering a situation when activity is getting to be canceled when it's just scheduled, but not picked up yet.
Fixing a bug in test service state machines to handle this situation correctly without throwing an exception.
> Fix test service state machines to handle situation when activity get cancelled from SCHEDULED state before being picked up

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowExecutorCache.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/workflow/ExecutionInfoStrategy.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/workflow/WorkflowMethodThreadNameStrategy.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerCacheTests.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/TracingWorkerInterceptor.java
Adds workflow id and run id into workflows method names
Added logging to trace WorkflowExecutionCache state
This needs to investigate a user report of workflow thread pool getting filled with open workflows which are yielding, but not getting evicted.
Also having workflowId and runId in the workflow thread names can benefit all users who need to look into thread dumps.
> Adds workflow id and run id into workflows method names

- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
This makes minor improvements to resource cleanup on close()
1. If TestWorkflowService gets instantiated with an in-process gRPC server, shut it down during close()
2. Wait for the forkJoinPool to terminate during close()
3. Add a 'no gRPC service at all' mode. This is secretly prep for resetting state via a long-lived API, which will make the test service more usable to other languages.
This is a prereq for the external gRPC API that resets the test service state. This API will make it easier to isolate tests when one uses the test service from other languages.
1. Closes [none]
Existing units pass
No.
> Memory/resource leak improvements in TestWorkflowService

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
WorkflowThreadContext has some code paths that are hard to comprehend, especially with premature switching to DONE and unswitching from it that should never happen. 
This PR polishes the statuses behavior and also simplifies destroy thread logic removing the need to implement it two ways - through a flag check and through a "coroutine" invocation simplifying and unifying threads destruction.
> Polish WorkflowThreadContext thread status switching

- temporal-sdk/src/main/java/io/temporal/internal/replay/QueryResult.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/QueryReplayHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
Fix thread leak in legacy query path
Refactor replay functionality into a separate class to keep clear from the main code path and worker code
Closes #880
> Fix thread leak in legacy query path

- temporal-sdk/src/test/java/io/temporal/testUtils/Signal.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/cancellation/WorkflowCancellationRunningActivityTest.java
Add more specific checks into WorkflowCancellationRunningActivity to make clear what happens with a running activity when the workflow gets cancelled.
> Adds more details into WorkflowCancellationRunningActivityTest

- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentTest.java
This changes a GRPC::Unknown to a GRPC::NotFound, which makes the test service match the behavior of the real thing.
The test service should behave similarly to the real thing =)
1. Closes (none)
There's a new unit test that fails without the change.
No.
> Fix the type of an exception from the test service

- docker/buildkite/docker-compose.yaml
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
Disable grpc idleTimer as a temporary solution to race condition in gRPC-java
Improve connection management related documentation on WorkflowServiceStubsOptions
It's a remedy for issue #863 unit gRPC-java bug is fixed or Temporal removes the code manually triggering `ManagedChannel#enterIdle`. 
See Issue #863 for details. Now we can get a broken worker because of a race condition in gRPC-java.
> Disable grpc idleTimer as a temporary solution to race condition in gRPC-java

- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncActivityRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowRetryTest.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironment.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
`getWorkflowExecutionHistory` implementation was moved from JUnit4 Test Rule into TestWorkflowEnvironment to expose it to users not using JUnit 4 or not using our Test Rule.
> Exposes getWorkflowExecutionHistory on TestWorkflowEnvironment

- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/test/java/io/temporal/internal/common/WorkflowExecutionHistoryTest.java
- temporal-testing/build.gradle
- temporal-testing/src/main/java/io/temporal/testing/WorkflowHistoryLoader.java
- temporal-testing/src/main/java/io/temporal/testing/WorkflowReplayer.java
Now the methods to read history from files exist only in internal package and can be used as a part of WorkflowReplayer only.
To provide better flexibility for our users, if they want to use `worker.replayWorkflowExecution` directly, for example, the methods are moved under `WorkflowExecutionHistoryLoader`class available for testing only.
> Expose methods for loading history from files as WorkflowExecutionHistoryLoader

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerTaskHandlerTests.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityRetryOnTimeoutTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ParallelLocalActivitiesTest.java
WFT handling counters gathered in `WorkflowWorker` instead of being spread between `WorkflowWorker` and `WorkflowTaskHandler`
Added logging in case of successful handling o WFT on the worker, but failing to report to the server.
Cleanup usage of tags and Scopes to remove inconsistent and duplicate tagging.  
Closes #900
> Rearrange WFT handle logging and metrics to accommodate all failure modes

- temporal-sdk/src/main/java/io/temporal/workflow/SignalMethod.java
Improve documentation on the Signal method to emphasize the possibility of getting a signal before the first workflow task.
Closes #864
> Improve documentation on the Signal method

- temporal-opentracing/src/main/java/io/temporal/opentracing/SpanCreationContext.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ActionTypeAndNameSpanBuilderProvider.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/SignalWithStartTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/SpanContextPropagationTest.java
- temporal-sdk/src/main/java/io/temporal/internal/external/GenericWorkflowClientExternalImpl.java
Fix `signalWithStart` integration with tracing
Pass a supplied header during `signalWithStart` client call
Issue #912
> Fix signalWithStart integration with tracing

- build.gradle
- gradle/dependencyManagement.gradle
- temporal-testing/README.md
- temporal-testing/build.gradle
- temporal-testing/src/main/resources/META-INF/native-image/io.temporal/temporal-testing/native-image.properties
This PR provides some adjustments and documentation about how to use GraalVM native-image tool to build Temporal Java Test Service into a native binary.
> Doc describing building test-server into a native binary using GraalVM native-image

- .buildkite/pipeline.yml
- build.gradle
- docker/buildkite/Dockerfile
- docker/buildkite/copyright-and-code-format.sh
- temporal-sdk/build.gradle
CI docker image has been updated to use the latest jdk8 image
CI scripts have been revisited for a switch from alpine to slim-bullseye Linux baseimage.
Closes #918
> Upgrade grpc version to 1.42.1

- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ExecutorThreadFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NoopSuspendableWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollTaskExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollWorkflowTaskDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ShutdownManager.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Shutdownable.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkerThreadsNameHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanWorkerShutdownHeartBeatingActivityTest.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanWorkerShutdownInvalidatesWorkflowCacheTest.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/determinism/NonDeterministicWorkflowPolicyFailWorkflowTest.java
A shutdown of WorkflowFactory now invalidates the workflow cache.
Full rework and polishing of a graceful worker shutdown to be actually graceful.
`ShutdownManager` is introduced to be able to represent shutdown as a sequence of `CompletableFuture` steps.
`CleanWorkerShutdownInvalidatesWorkflowCacheTest` - Test verifying that an awaiting workflow gets `DestroyWorkflowThreadError` during shutdown.
Closes #914
> Shutdown of WorkflowFactory now invalidates the workflow cache

- temporal-testing/src/main/java/io/temporal/testing/TestEnvironmentOptions.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java
This exposes a setting in TestEnvironmentOptions that people can use to disable timeskipping.
https://github.com/temporalio/sdk-java/pull/813 fixed a bug that was load-bearing for a customer's test that assumed timeskipping was off. This PR should unblock their test by letting them formally disable timeskipping.
1. Closes (no issue)
There's a new unit test. Because of how it has to rely on the actual passage of time to make its assertions, I'm not a fan of it, but it proves the feature works. I am very open to not committing it.
No
> Allow disabling timeskipping on TestWorkflowEnvironment

- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOActivityImplMetadata.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/ActivityTestingTest.java
`POJOActivityImplMetadata` now uses guava to find all activity interfaces for a given activity impl class. Inspiration - https://stackoverflow.com/questions/6616055/get-all-derived-interfaces-of-a-class
https://github.com/temporalio/sdk-java/issues/929
1. Closes https://github.com/temporalio/sdk-java/issues/929
2. How was this tested?
Added a test. All existing tests pass.
3. Any docs updates needed? 
I don't think this needs any doc updates.
> Fix POJOActivityImplMetadata not being able to handle activity impl that uses inheritance

- temporal-sdk/src/main/java/io/temporal/activity/Activity.java
- temporal-sdk/src/main/java/io/temporal/activity/ActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityInfoInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/CurrentActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContext.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/POJOActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkerThreadsNameHelper.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Code duplication between `POJOActivityImplementation` and `POJOLocalActivityImplementation` is cleaned up by unifying the code base and moving the difference out as a `ActivityExecutionContextFactory executionContextFactory`.
Abstracted `executionContextFactory` is reused in `DynamicActivityImplementation` to correctly supporting local mode.
`POJOActivityTaskHandler` before contained a large code duplicate in `POJOActivityImplementation` and `POJOLocalActivityImplementation` classes implemented a difference between local and regular activities. This also led to the fact that `DynamicActivityImplementation` was not handling local/regular mode correctly because there was only one version.
Closes #948
> Refactor a local/regular activities difference out from POJOActivityTaskHandler

- temporal-testing/src/main/java/io/temporal/internal/testservice/TaskQueue.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStore.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
Connects gRPC context cancellation up to the threads performing
long-polls on task queues so that when a client exits/dies and the
attendant connections go away, the polling threads are broken out of
their blocking polls.
To reuse a test server process across multiple test cases without having 
to wait for the 60s long-poll timeout.
1. Closes 
> Cancel pollers when client disconnects

- temporal-opentracing/src/main/java/io/temporal/opentracing/SpanOperationType.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ActionTypeAndNameSpanBuilderProvider.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ContextAccessor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowClientCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/ContinueAsNewTest.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/ActivityInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkerInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ContinueAsNewWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/ContinueAsNewOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Interception of  continue-as-new is fixed,  continue-as-new headers are passed to the server now instead of discarding
Test Service implementation of continue-as-new regarding headers is also fixed and brought in agreement with an actual Temporal server
Context Propagation for continue-as-new is implemented
OpenTracing span propagation for continue-as-new is implemented
Unit test for OpenTracing span connectivity, propagation, and structure for a workflow containing continue-as-new.
Closes #844
> Fix continue-as-new wiring, interception, context propagation and OpenTracing integration

- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
This PR fixes absent workflow statuses in TestService#listOpenWorkflowExecutions return value
It's not according to the current strategy [TestSerice and the real dockerized temporal server are used for SDK tests themselves]. It will be covered with SDK test though once we expose listOpenWorkflowExecutions as SDK API call (not just a service client call).
Closes #842
> Fix absent workflow statuses in TestService#listOpenWorkflowExecutions

- CONTRIBUTING.md
- temporal-sdk/src/main/java/io/temporal/common/converter/AbstractProtobufPayloadConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/DefaultDataConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/EncodingKeys.java
- temporal-sdk/src/main/java/io/temporal/common/converter/ProtobufJsonPayloadConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/ProtobufPayloadConverter.java
- temporal-sdk/src/test/java/io/temporal/common/converter/ProtoPayloadConverterTest.java
In `ProtobufPayloadConverter` and `ProtobufJSONPayloadConverter`, I added a second `metadata` attribute, `mesageType`, with the full proto message name:
```
metadata: 
encoding: binary("json/protobuf"),
messageType: binary("foo.bar.MyMessage")
data: ...
```
1. Support decoding protobuf payloads in languages that don't have the ability to get the types of a given function's parameters at runtime (see TS SDK [PR](https://github.com/temporalio/sdk-typescript/pull/430) and [design doc](https://github.com/lorensr/sdk-node/blob/binary/protobuf/docs/protobuf-libraries.md)).
2. Support decoding binary protobuf payloads in the UI (https://github.com/temporalio/ui-server/issues/79).
Added `ProtoPayloadConverterTest.testProtoMessageType()` to check that an execution payload …
> Add metadata.messageType to protobuf payloads

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/SimpleSslContextBuilder.java
Fix bug where TLS certificate streams are read twice, Causing java.lang.IllegalArgumentException: Input stream not contain valid certificates.
> Fix bug where TLS certificate streams are read twice

- gradle/publishing.gradle
- temporal-sdk/build.gradle
Remove "Resolved versions" dependencies resolution strategy during Nexus publishing
This will switch a resolution to "Declared versions" (default).
See https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies
Closes #964
> Remove "Resolved versions" dependencies resolution strategy during Nexus publishing

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
Provide a note that the total client-server interaction is not limited by `rpcTimeout`
> Improve WorkflowServiceStubsOptions#setRpcTimeout javadoc

- build.gradle
Updated com.google.protobuf:protobuf-java-util version to 3.19.2 as there is CVE in current pinned version.
This is causing  Could not resolve com.google.protobuf:protobuf-java-util:3.19.1 in code which uses google-cloud libraries latest version with fix for CVE
1. Closes 
Yes. Standard gradle build unit tests.
New release needed.
> Upgrade protobuf-java-util for CVE-2021-22569

- build.gradle
- temporal-opentracing/build.gradle
- temporal-serviceclient/build.gradle
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/SimpleSslContextBuilder.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
Added
- WorkflowServiceStubsOptions#channelInitializer mimicking Netty's addChannelInitializer 
- SimpleSslContextBuilder#configure() mimicking GrpcSslContexts
that provide a more flexible approach to configuration.
Previously users were able to either use basic config functionality of WorkflowServiceStubsOptions OR a fully custom channel. This works fine until users need to tweak or change some exotic parameter of the gRPC channel. To do that they have to fall back to a fully custom channel and stop using the whole Temporal built-in configuration.
Now users can use the full standard Temporal configuration and tune some parameters of the channel right before it gets built using a listener.
> Provide configuration hooks extending usage of standard SDK configuration functionality

- temporal-sdk/src/main/java/io/temporal/internal/activity/POJOActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/metrics/MetricsType.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
Some activity metric names are brought in sync with GoSDK and Core.
temporal_local_activity_failed, temporal_local_activity_canceled, temporal_activity_canceled are deprecated
> Synchronize activity metric names with Core and GoSDK, old names are deprecated

- build.gradle
- gradle/dependencyManagement.gradle
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
Remove deprecated name.remal.check-updates plugin
We use Dependabot for updates
Closes #321
> Remove deprecated name.remal.check-updates plugin

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollTaskExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTaskFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/MetricsType.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerMetricsTag.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/MetricsTag.java
Add worker_task_slots_available metric providing information about the count of available executor threads and worker_type tag for worker-level metrics.
Closes #986
> Add worker_task_slots_available metric and worker_type tag

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-sdk/src/test/java/io/temporal/workflow/GetCronScheduleFromWorkflowInfoTest.java
- temporal-test-server/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
exposes WorkflowInfo.getCronSchedule so can get the defined cron schedule inside workflow code
> Expose WorkflowInfo.getCronSchedule

- .github/workflows/README.md
- .github/workflows/native-images.yml
- .github/workflows/native-testserver-images.yml
A GH action that will build the test server native image on linux/amd64,
macOS/amd64, and windows/amd64. Build outputs are stored with the
workflow execution for 1 day and optionally attached to a user-supplied
GH release.
Missing from this work is a matrix build entry for macOS/aarch64 as
we don't have build machines for that platform yet.
The tgz and zip files that are ultimately released are modeled on
https://github.com/cli/cli/releases/tag/v2.4.0
Cross-platform native builds of the test server
1. Closes 
> Introduce GH actions for native-image builds

- temporal-kotlin/src/main/kotlin/io/temporal/worker/WorkflowImplementationOptionsExt.kt
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkflowImplementationOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/activity/ActivityTestOptions.java
- temporal-sdk/src/test/java/io/temporal/activity/DefaultActivityOptionsOnWorkflowNotSetTest.java
- temporal-sdk/src/test/java/io/temporal/activity/DefaultActivityOptionsSetOnWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/activity/LocalActivityMethodOptionsTest.java
- temporal-sdk/src/test/java/io/temporal/activity/LocalActivityTest.java
- temporal-sdk/src/test/java/io/temporal/activity/LocalActivityTestImpl.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestOptions.java
Added `localActivityOptions` and `defaultLocalActivityOptions` fields and relevant setters/getters to `WorkflowImplementationOptions`, `SyncWorkflowContext`, and `Workflow`, so that in `Workflow.newLocalActivityStub`, any local activity options received from the workflow are merged with options in WorkflowImplementationOptions. 
Following existing WorkflowImplementationOptions.setActivityOptions, allow user to define local activity options for different types of activities instead of defining them in workflow code. This would be applied to `Workflow.newLocalActivityStub`.
1. Closes [Issue #975](https://github.com/temporalio/sdk-java/issues/975)
Duplicated existing tests for merging regular Activity Options for merging Local Activity Options. …
> Add WorkflowImplementationOptions.setLocalActivityOptions (#975)

- .github/workflows/native-testserver-images.yml
This value needs to be a string and yaml treats `no` as a boolean. Turns out the `type: boolean` on input parameters is just a hint for how to render the user interface and not an indication of an actual type system.
yaml
1. Closes 
Running this workflow via `gh workflow run` _without_ specifying the `clobber` parameter fails. This fixes the failure.
> Workflow input defaults should be strings

- .github/workflows/native-testserver-images.yml
Require windows-2019 for native image builds rather than windows-latest
GraalVM doesn't have an SDK for Windows Server 2022 yet so the native
executable build fails if we catch an updated builder. Windows 2022 is
becoming the default for `windows-latest` "real soon now" so pin the
version in use to 2019.
More context at actions/virtual-environments#4856
1. Closes 
> Prevent Windows 2022 being used for native-images

- temporal-sdk/src/main/java/io/temporal/activity/ActivityInfo.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityInfoImpl.java
Expose ActivityInfo#getCurrentAttemptScheduledTimestamp in addition to the activity execution scheduled timestamp on the ActivityInfo.
Can be useful for user metrics
> Expose ActivityInfo#getCurrentAttemptScheduledTimestamp

- temporal-sdk/src/main/java/io/temporal/workflow/Promise.java
- temporal-sdk/src/main/java/io/temporal/workflow/package-info.java
- temporal-sdk/src/test/java/io/temporal/workflow/PromiseAllowsBlockingTemporalCodeTest.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestOptions.java
Improve Promise and io.temporal.workflow javadocs.
Add a test for Promise handler calling a sleeping activity.
Currently Promise handlers doc states that it can't contain blocking calls, while in reality, this code has all the same limitations as a regular workflow code.
> Improve Promise and io.temporal.workflow javadocs

- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/package-info.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerIsNotGettingStartedTest.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerPollerThreadCountTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/LocalAsyncCompletionWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityPollerPrefetchingTest.java
Synchronization of similar option names helps to keep guides and docs less cluttered with references between different SDKs.
> Unify worker pollers options naming between GoSDK and JavaSDK

- build.gradle
- temporal-serviceclient/build.gradle
- temporal-test-server/build.gradle
Switch to specific versions for dependencies with Platforms to make release Maven compatible.
This is required as a temporary workaround for a long time Maven bug that should be addressed in Maven 4.0.0 that Is still to be released.
Closes #1033
> Switch to specific versions for dependencies with Platforms to make release Maven compatible

- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityAndQueryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/WaitingWorkflowQueryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
Provide the simplest query test that may be used as a starting point to allow easy investigation/reproduction of query-related issues.
There are some existing tests that use queries, but they use them as a tool instead of being focused on them.
> Add a trivial query test

- temporal-sdk/src/main/java/io/temporal/internal/common/HistoryJsonUtils.java
- temporal-sdk/src/test/java/io/temporal/internal/common/WorkflowExecutionHistoryTest.java
- temporal-sdk/src/test/resources/simpleHistory1.json
- temporal-sdk/src/test/resources/simpleHistory1_withAddedNewRandomField.json
Use the same JSON_PATH_CONFIGURATION during history serialization as we use during deserialization. It allows ignoring exceptions caused by the absence of the path intended for conversion in the source Json.
JsonPath upgrade performed in #1020 brought an incompatible change that requires specifying of JsonPath config to achieve an old behavior of JsonPath (ignoring an absence of a path intended for transformation). This config was originally applied in #1020 only history deserialization and left serialization broken in some cases.
Added a unit test for bidirectional transformation to make sure the history serialization/deserialization works in both directions and preserves the result.
> Use correct JsonPath config on history serialization

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/test/java/io/temporal/workflow/DeadlockDetectorTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/WaitingWorkflowQueryTest.java
> Deps upgrade

- temporal-opentracing/src/main/java/io/temporal/opentracing/OpenTracingOptions.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingActivityInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/ExceptionIgnoredTest.java
Adds a Predicate as a new option on the OpenTracingOptions, which controls whether or not the tested exception should be considered an error for the purposes of the span. If the predicate returns false, the exception will not be attached to the span; otherwise it will. By default, the predicate simply returns true.
Specifically, the use case that I'm solving is this: for Activities which have to periodically poll an external service, the general best practice is to throw an exception if the polled service isn't ready to respond yet (a request isn't finished for instance). In this case, the normal retry logic will kick in and periodically try again. There are surely other instances where one might throw an exception in order to repeat an Activity without it being considered abnormal. …
> Allow OpenTracing interceptor to ignore certain exceptions

- temporal-sdk/src/main/java/io/temporal/internal/common/HistoryJsonUtils.java
- temporal-sdk/src/test/java/io/temporal/internal/common/WorkflowExecutionHistoryTest.java
- temporal-sdk/src/test/resources/complexHistory1.json
WorkflowExecutionHistory implementation is updated to convert some more rarely used history enums in a way compliant with tctl history format
Unit test from a complex workflow using child workflows and verifying that deserialization-serialization cycle by JavaSDK preserves the same history
> Include more enums transformation into history json transformation

- .github/workflows/prepare-release.yml
This change uses step outputs rather than step outcomes to determine
whether or not a release already exists.
The Github web ui sees the (intentional) failure of the check_release
step and generates a Big Red X warning on associated workflow runs. This
occurs even though we're indicating that an error for this step is
ok/expected via the `continue-on-error` tag. The error indication is
troubling because (a) nothing went wrong and (b) someoneone unfamiliar
with the details of the workflow might think that there's a problem.
1. Closes 
> Avoid spurious error notification from prep-release

- temporal-serviceclient/src/main/java/io/temporal/internal/testservice/GRPCServerHelper.java
- temporal-serviceclient/src/main/java/io/temporal/internal/testservice/InProcessGRPCServer.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/GrpcDeadlineInterceptor.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/GrpcTracingInterceptor.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/OperatorServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/OperatorServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/OperatorServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-test-server/build.gradle
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
WorkflowServiceStubsImpl was refactored to reduce code duplication
Allow users to register search attributes using sdk
Refactoring of WorkflowServiceStubs to reduce code duplication
Closes #882
> Expose OrchestratorServiceStubs

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SingleWorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
Fix for potential pollers deadlock if suspendPolling called twice.
Refactorings that make the code around Polling easier to follow.
> Code cleanup around Pollers

- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryerUtils.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcSyncRetryer.java
This is mostly a refactoring of GrpcSyncRetryer and GrpcAsyncRetryer that keeps the codebase unified (especially in relation to preserving "last meaningful exception"). 
LOG level for non-terminal exceptions is INFO now for both. Previously WARN in Sync and DEBUG in Async Retryer, which doesn't make much sense.
> Synchronize GrpcSyncRetryer and GrpcAsyncRetryer behavior, make non-final exceptions INFO level

- temporal-sdk/src/test/java/io/temporal/workflow/serialization/OptionalJsonSerializationTest.java
This test was written without a consideration that the signal may be reordered before the first workflow task
> Fix flake with dockerized temporal when signal gets reordered with the first workflow task

- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
Small change to comments for newUntypedExternalWorkflowStub methods
> Fix comments for newUntypedExternalWorkflowStub

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/common/ProtobufTimeUtils.java
- temporal-sdk/src/test/java/io/temporal/workflow/GrpcRetryerFunctionalTest.java
- temporal-serviceclient/build.gradle
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-test-server/build.gradle
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestOperatorService.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestService.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestServicesStarter.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/main/java/io/temporal/serviceclient/TestServiceStubs.java
- temporal-test-server/src/main/java/io/temporal/serviceclient/TestServiceStubsImpl.java
- temporal-test-server/src/main/java/io/temporal/serviceclient/TestServiceStubsOptions.java
- temporal-test-server/src/main/java/io/temporal/testserver/TestServer.java
- temporal-test-server/src/main/proto/Makefile
- temporal-test-server/src/main/proto/api-linter.yaml
- temporal-test-server/src/main/proto/buf.yaml
- temporal-test-server/src/main/proto/dependencies/gogoproto/gogo.proto
- temporal-test-server/src/main/proto/temporal/api/testservice/v1/request_response.proto
- temporal-test-server/src/main/proto/temporal/api/testservice/v1/service.proto
- temporal-test-server/src/test/java/io/temporal/worker/WorkflowCachingTest.java
- temporal-testing/src/main/java/io/temporal/testing/IdempotentTimeLocker.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TimeLockingInterceptor.java
Test Service gRPC service is added with time-skipping methods.
JavaSDK is fully reworked to use Time Skipping gRPC Stubs instead of accessing the in-memory TestService internal instances and classes directly when time skipping functionality is needed, reducing coupling between SDK test classes and test-server implementation.
Native Test Service default starting behavior changed to start with locked (disabled) time-skipping to behave closer to a real Temporal Server by default.
> Time Skipping Service

- gradle/java.gradle
Related to:
https://stackoverflow.com/questions/53732632/gradle-javadoc-search-redirects-to-undefined-url
> Fix Search in Javadocs

- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerOptionsTest.java
WorkerOptions Builder now uses the correct value to initialize maxConcurrentLocalActivityExecutionSize inside the partial `build()` method.
Note: `validateAndBuildWithDefaults` worked correctly and is not affected by this change.
Closes #1080
> Fix for WorkerOptions Builder using maxConcurrentActivityExecutionSize for local activities in partial build()

- temporal-sdk/build.gradle
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOActivityInterfaceMetadata.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/POJOActivityInterfaceMetadataTest.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/testclasses/ActivityInterfaceWithOneNonAnnotatedMethod.java
Exclude synthetic and static methods from Activity Interface Hierarchy
Refactor POJOActivityInterfaceMetadata for easier reading
Closes #977
> Exclude synthetic and static methods from Activity Interface Hierarchy

- temporal-test-server/src/main/java/io/temporal/testserver/TestServer.java
Right now the native test server returns code 130 on signing because of the absent shutdown hook.
This PR adds a clean exit on SIGINT.
> Add shutdown hook for a clean server exit

- temporal-sdk/src/test/java/io/temporal/workflow/DescribeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/DescribeWorkflowAsserter.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
This makes the implementation of DescribeWorkflowExecution in the test service aware of calls to Workflow.upsertSearchAttributes.
The test service's describe method had a bug that impacted any workflow that upserted search attributes.
1. Closes (nothing)
```
cd temporal-sdk
USE_DOCKER_SERVICE=false ../gradlew test --tests io.temporal.workflow.DescribeTest
USE_DOCKER_SERVICE=true ../gradlew test --tests io.temporal.workflow.DescribeTest
```
None.
> Add support for UpsertSearchAttributes to describe in the test service

- temporal-sdk/src/main/java/io/temporal/internal/common/GrpcUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
Now workers during shutdown may throw 
```io.grpc.StatusRuntimeException io.grpc.StatusRuntimeException: UNAVAILABLE: Subchannel shutdown invoked```
This PR improves handling of gRPC exceptions during shutdown
> Swallow "Subchannel shutdown" gRPC errors during worker shutdown

- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
Replace cryptic unhelpful anonymous class name with an actual class of the polling task in `Poller` shutdown log.
> Improve Poller's shutdown log message with a poll task class

- .whitesource
- whitesource.config
Added a local .whitesource and whitesource.config files, to exclude Gradle test scopes.
Test scopes are:
1. Not expected to be in the classpath at runtime
2. Not included into dependencies descriptor of the jar publishing into maven central repos
3. Not used for compilation of the sources that end up in the target jar.
> Added local whitesource config files

- temporal-sdk/src/test/java/io/temporal/workflow/interceptors/SignalWorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionInSignalOnReplayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionInSignalTest.java
Adds a couple of tests verifying that getVersion call can be used inside a signal handler
> Tests verifying that getVersion inside a signal handler works correctly

- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/RepeatedWorkflowTaskFailuresTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/common/TestWorkflows.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/timeskipping/TimeSkippingFromAnActivityTest.java
To match the new behavior of the real server, Test Server now times out a workflow task if the workflow task failed and the attempt is >=2.
See https://github.com/temporalio/temporal/pull/2548
New unit test verifying the behavior across the test and real server.
> Test Server times out workflow task in case of workflow task failure after the second attempt

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/PotentialDeadlockException.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactoryOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- Potential Deadlock detection firing time
- The time when SDK was able to obtain a stacktrace of a potentially deadlocked thread
- A timestamp when a thread dump of other threads was taken 
could be different because of JVM safepoints. To make it more clear to the investigator, timestamps are now included in the Potential Deadlock message.
> Improve PotentialDeadlockException message with timestamps

- temporal-sdk/src/main/java/io/temporal/internal/common/DebugModeUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/deadlockdetector/DeadlockBeforeActivityCallTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/deadlockdetector/DeadlockDetectorTest.java
State machines are now checking if the workflow thread destruction has been requested and if it is, the thread gets killed.
Before this changes "Operation allowed only while eventLoop is running" is thrown if detection of deadlock is followed by some state machines change by the workflow thread.
Covered by the new unit test that fails on the current master.
Closes #1066
> Fix "Operation allowed only while eventLoop is running" exception if deadlock is detected

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/RepeatedWorkflowTaskFailuresTest.java
Facing some edge cases with timing out WFTs on subsequent UNHANDLED_COMMAND, Temporal Server will stop doing the new behavior for UNHANDLED_COMMAND in 1.17
Incorporate the new change in Java Test Server early to mitigate facing these edge cases in stress tests
> Don't time out WFT in case of subsequent UNHANDLED_COMMAND failures

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/workflow/ExecutionInfoStrategy.java
Now if we truncate workflowId before we append it to the workflow thread name, we truncate it and it may be unclear and misleading in some cases. Add a clear marker at the end of workflowId if we indeed truncate.
> Fix workflow thread name strategy to append a clear marker of truncation

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
- temporal-testing/src/main/java/io/temporal/testing/TestEnvironmentOptions.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowExtension.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowRule.java
`setMetricsScope` is wired into test rules
Guidance about Scope mocking for unit tests is provided
> setMetricsScope is wired into test rules

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/MetricsType.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTaskFailureBackoffTest.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
Moved NO_COMPLETION counter reporting to an expected area of code.
The current (before this change) location of the metric reporting looks off (it's probably outdated because the logic of when SDK "doesn't report a failure to the server" changed in the past) and doesn't work as expected.
Provided an assertion for the metric in the unit test.
> Moved NO_COMPLETION counter reporting to handle all cases

- temporal-sdk/src/main/java/io/temporal/failure/FailureConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowExecuteRunnable.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerCacheTests.java
It's a purely refactoring and cleanup PR that improves the code structure, decreases copy-pasted similar code, adds or refreshes the javadocs.
It's the first of the PRs focused on simplifying the error handling logic. 
Code in this area right now is quite convoluted and spread across several classes, it's safer to make smaller changes that are easier to verify.
> Refactor and cleanup "exception to failure" conversion code

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/PotentialDeadlockException.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
PotentialDeadlockException now includes the original stack trace from where it was thrown.
A stack trace of the thread that triggered the exception is getting collected in the same place as the thread dump of other workflow threads and it gets populated into the exception message instead of the stack trace.
Right now PotentialDeadlockException hides an original stack trace where it was thrown and replaces it with the stack trace of the method that triggered it. While this solution may seem elegant, it's proven to cause confusion in some situations.
This also brings us closer to implementing and fixing #1125 by taking all the workflow threads stacktraces in one place.
> Rework PotentialDeadlockException to don't override the original stacktrace

- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowRunLockManager.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowRunLockManagerTest.java
WorkflowRunLockManager was reimplemented in a safe way. Now unlock for a runId can be called only from a thread that acquired the lock.
See #1146. The current API and implementation of WorkflowRunLockManager may lead to a lock for a runId being released by a thread that is not eligible for that.
Closes #1146
> Reimplemented WorkflowRunLockManager to fix design flaw with an unsafe unlock

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NoopSuspendableWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerSuspendTest.java
`Worker#isSuspended` now behaves correctly.
NoopSuspendableWorker#isSuspended now returns true.
NoopSuspendableWorker#isSuspended returned false which messed with the `Worker#isSuspended` final result.
Now it always returns true which is technically correct.
Closes #1114
> Fix for Worker#isSuspended not returning the correct state

- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestOperatorService.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/DescribeNamespaceTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/DescribeWorkflowExecutionTest.java
Add trivial describeNamespace test server implementation.
This implementation returns a trivial REGISTERED response about any namespace describe request. The test server currently doesn't need a namespace to be registered.
Closes #1158
> Add trivial describeNamespace test server implementation

- temporal-opentracing/src/main/java/io/temporal/opentracing/StandardTagNames.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
- temporal-opentracing/src/test/java/io/temporal/worker/WorkflowEvictionTest.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DestroyWorkflowThreadError.java
Workflow evictions are not logged as errors in opentracing spans anymore.
Closes #1162
> Evictions are not logged as errors in opentracing anymore

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
Rework `#setChannelInitializer` method for easier access, remove old deprecated classes and methods.
Before this change, the old API was already deprecated and the new API was hard to access.
> Rework #setChannelInitializer method for easier access, remove old deprecated classes and methods

- .buildkite/pipeline.yml
- build.gradle
- docker/buildkite/docker-compose.yaml
- gradle/jacoco.gradle
- temporal-sdk/src/test/java/io/temporal/workflow/StartTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTest.java
Add Jacoco configuration that produces reports for each module.
Some tests refactoring to remove flakes caused by increased execution times with instrumentation for code coverage.
> Add per-module Jacoco config

- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/test/java/io/temporal/testing/TestEnvToleratesLongTestServerCalls.java
Fix test service stubs throwing DEADLINE_EXCEEDED
Calls to the test server shouldn't enforce the standard rpcTimeout and throw DEADLINE_EXCEEDED 
It's safe to don't limit these calls
> Fix test service stubs throwing DEADLINE_EXCEEDED

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
Improve the exception message that users get if custom interceptors return an illegal object from `newThreadX` methods.
> Improve illegal custom interceptors error reporting

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
Unify the limit on gRPC incoming message across SDKs to 128Mb.
GoSDK change: https://github.com/temporalio/sdk-go/pull/796
> Unify the limit on gRPC incoming message across SDKs to 128Mb

- temporal-kotlin/src/main/kotlin/io/temporal/serviceclient/WorkflowServiceStubsExt.kt
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/test/java/io/temporal/testUtils/HistoryUtils.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerStressTests.java
- temporal-sdk/src/test/java/io/temporal/workerFactory/WorkerFactoryTests.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/OperatorServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/OperatorServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/HealthCheckTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/main/java/io/temporal/serviceclient/TestServiceStubs.java
- temporal-test-server/src/main/java/io/temporal/serviceclient/TestServiceStubsImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowCachingTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/timeskipping/TimeSkippingFromAnActivityTest.java
- temporal-testing/src/main/java/io/temporal/internal/docker/RegisterTestNamespace.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
Add and Implemented `ServiceStubs#healthCheck()`, make eager health check during client creation disabled by default.
Closes #828
Corresponded GoSDK change: https://github.com/temporalio/sdk-go/pull/795
> Explicit methods for lazy and eager connecting client, new #healthCheck method on stubs

- build.gradle
- temporal-sdk/src/main/java/io/temporal/activity/ActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/activity/ManualActivityCompletionClient.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/CompletionAwareManualCompletionClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/ActivityClientHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/ManualActivityCompletionClientFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/ManualActivityCompletionClientFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowClientInternal.java
Add documentation to ManualActivityCompletionClient, fix absent service call retries.
One code path didn't have service retries which were fixed.
`ManualActivityCompletionClientFactory` was refactored to make the lifecycle of the factory instances saner.
The public user-facing ManualActivityCompletionClient interface was completely undocumented.
Work towards #752 scope
> Add documentation to ManualActivityCompletionClient, fix absent service call retries

- temporal-kotlin/src/main/kotlin/io/temporal/serviceclient/WorkflowServiceStubsExt.kt
* move options lambda to the last argument of the function to support DSL-like usage
* add a variation that accepts `java.time.Duration` timeout
* make timeout optional and nullable
This change adapts the `ConnectedWorkflowServiceStubs` method that was introduced in SDK 1.11.0 to Kotlin idioms.
1. In order for the method to work as a "DSL" its lambda argument has to be the last. E.g. the existing method could be called as
```kotlin
ConnectedWorkflowServiceStubs({
setTarget("myhost")
}, 30.seconds)
```
however if the options lambda is moved as the last argument it could be called as
```kotlin
ConnectedWorkflowServiceStubs(30.seconds) {
setTarget("myhost")
}
```
2. The underlying `WorkflowServiceStubs.newConnectedServiceStubs` method supports a `null` value of `timeout` but the Kotlin …
> Polish ConnectedWorkflowServiceStubs method

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/test/java/io/temporal/common/reporter/TestStatsReporter.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/PromiseTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalDeprecatedQueueTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalQueueTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DeterministicRunnerWrapper.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Abstract WorkflowThreadExecutor instead of using a broad thread pool in WorkflowThread class. WorkflowThread needs only the regular `submit` method.
Initialize WorkflowThreadExecutor in WorkerFactory to use the root worker metric scope.
WorkerThread doesn't need to log the worker_active_thread metric. This metric belongs to `WorkerFactory` level scope and logging of this metric should be performed on that level.
Closes #1179
> Fix workflow_active_thread_count, abstract WorkflowThreadExecutor instead of using a broad thread pool

- temporal-sdk/src/main/java/io/temporal/internal/sync/PotentialDeadlockException.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/GrpcMetricsInterceptor.java
Now GrpcMetricsInterceptor tolerates incorrectly implemented user interceptor that throws from onClose (onClose grpc method contract prohibits throwing from it).
Also includes a small optimization avoiding the creation of a map of tags for each request failure.
If a user has incorrectly implemented custom interceptor that throws in some situation, Temporal SDK will fail logging request level metrics potentially complicating detection of the problem.
> Fix absent request level metrics not logging with incorrectly implemented custom grpc interceptor

- build.gradle
- temporal-kotlin/build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/LocalActivityAndQueryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/QueryCausingReplayWithLocalActivityInLastWFTTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
Add a unit test for a specific corner case of a direct query after completion of local activity.
Align Test Server behavior with real Temporal Server for such a direct query.
The current unexpected behavior of Temporal Test Server causes state machine problems.
Closes #1190
> Align Test Server direct query behavior with the real server

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/LocalActivityStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityWorkflowTimeUpdateTest.java
Now Local Activities when updating workflow task timestamp uses the workflow task timestamp when it was scheduled and a time elapsed in the execution instead of System.currentTimeMillis
Local Activity updating time should respect the server time of the workflow task and don't use the local time of the worker host as a source of truth.
Closes #1187
> Local Activity uses Server time and elapsed period to update workflow task timestamp

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollAsyncHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientRequestFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowClientInternal.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/LongPollUtil.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/MetricsTest.java
Refactored WorkflowClientLongPollHelper and WorkflowClientLongPollAsyncHelper to simplify implementation and
use the same parameters for performing long polls.
Add a framework for testing client metrics behavior in isolation from the worker metrics.
This PR also prepares the ground for https://github.com/temporalio/sdk-java/issues/1203 and https://github.com/temporalio/sdk-java/issues/1177
Closes #1197
> Rework async long poll to use the same configuration as the main long poll

- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollAsyncHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientLongPollHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowHistoryIterator.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryerUtils.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcSyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/RpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubLongPollRpcRetryOptions.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcAsyncRetryerTest.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcSyncRetryerTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/GetResultsAsyncOverMaximumLongPollWaitTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/GetResultsOverLongPollTimeoutTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/GetResultsSyncOverMaximumLongPollWaitTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/GetResultsTimeoutTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/HealthCheckTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/MetricsTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/common/TestWorkflows.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStore.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
Make getResult methods to throw `TimeoutException` as the method contract states instead of raw gRPC DEADLINE_EXCEEDED.
getResultAsync now respects the timeout.
Unit tests are added that are covering different kinds of timeouts and retries of the long poll.
Closes #1177
Closes #988
Partially addresses #1203
> Make getResult methods to throw TimeoutException instead of raw gRPC DEADLINE_EXCEEDED

- .buildkite/pipeline.yml
- CONTRIBUTING.md
- README.md
- build.gradle
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/cancellation/AbandonActivityFinishesAfterCancellingTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/cancellation/AbandonOnCancelActivityTest.java
This test verifies that an Activity started with {@link ActivityCancellationType#ABANDON} can be canceled after starting by the workflow and can successfully finish later. And this combination doesn't cause a problem with workflow state machines.
> Add unit test verifying behavior of finishing Activity with CancellationType=ABANDON if it was canceled by the workflow

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/resources/logback-test.xml
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcSyncRetryer.java
This PR addresses the verbose logging made by GrpcRetryer. The client code of GrpcRetryer should be responsible for dealing with the exceptions, including not logging and not reacting to them at all because they may be not a problem.
Closes #1208
> Deescalate GrpcRetryer logging to trace level

- temporal-kotlin/src/test/kotlin/io/temporal/activity/ActivityExecutionContextExtTest.kt
- temporal-kotlin/src/test/kotlin/io/temporal/client/WorkflowClientExtTest.kt
- temporal-sdk/src/test/java/io/temporal/activity/ActivityOptionsTest.java
- temporal-sdk/src/test/java/io/temporal/activity/LocalActivityMethodOptionsTest.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/ActivityTestingTest.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityTimeoutTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Test Server responds NOT_FOUND if the activity is in an incorrect state for a worker trying to finish the activity.
Timeouts are also added to the tests that don't use SDK Test Rule.
Partially addresses #1081
> Test Server responds NOT_FOUND if the activity is in incorrect state

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/VersionStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/LocalActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/VersionStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/DefaultVersionNotSupportedDuringReplayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/VersionNotSupportedWithConflictingRangesExecutionTest.java
Fix Version State Machine ignoring range check during replay if the history was unversioned.
Unit test verifying situation when getVersion check is added during replay and wasn't there during the original execution.
Closes #1239
> Fix Version State Machine ignoring range check during replay if the history was unversioned

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkerInterceptor.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryerUtils.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/RpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubLongPollRpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubServiceOperationRpcRetryOptions.java
- temporal-testing/src/test/java/io/temporal/testing/functional/TimeLockingInterceptorAsyncTest.java
Make Temporal standard non-retryable gRPC codes not configurable. Users can't make Temporal non-retryable code retryable after this PR, users can still add own code/failure types pairs.
Improve documentation around retrying of query rpc requests and generally around `RpcRetryOptions`.
> Make Temporal standard non-retryable gRPC codes not configurable

- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowExecutorCache.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThread.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityTimeoutTest.java
`DeterministicRunner#close` now returns always after the closing is fully completed.
Previous behavior may be causing rejected executions from the cache because the threads were not actually released yet even when the executions are gone from the cache.
Unit test executes two `#close` in parallel and checking that they return only when the workflow thread is finished which fails on a current master.
> Make DeterministicRunner#close always block until the closing is done

- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowExecutorCache.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
Invalidate cached workflow state if Worker fails to send the result to the server
If the server goes down, a worker may finish processing workflow tasks and fail to report the advancement to the Temporal Server.
If this happens, if the server goes up and dispatches the WFT to the same worker, the worker has more advanced execution in its cache than the Temporal Server is aware of. 
This change needs to be thoroughly tested, but there is no framework for such testing right now in place in JavaSDK.
Follow-up task to implement the absent testing functionality and the test: https://github.com/temporalio/sdk-java/issues/1266
> Invalidate cached workflow state if worker fails to send the result to the server

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
Add an exception that guards against situations when new events may be applied to an outdated state machine.
This is theoretically possible if Worker on a sticky queue receives a partial history and has an outdated cached workflow instance.
In practice, this should never happen according to the sticky queues design, but it's safer to have a guard in place.
> Guard against applying new events to workflow state machines if there is a gap

- temporal-sdk/src/main/java/io/temporal/failure/CanceledFailure.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ChildWorkflowStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowCancellationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowImmediateCancellationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/StartChildWorkflowWithCancellationScopeAndCancelParentTest.java
One of the state machine internal branches (modes) of cancelation was throwing a trivial NulPointer.
Unit test covering this scenario of child workflow cancelation
Closes #1037
> Fix state machines NullPointerException during one of the modes of child workflow cancellation

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/InternalWorkflowTaskException.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityPollTask.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/VersionStateMachineTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubLongPollRpcRetryOptions.java
Rework LocalActivities waiting code to use nanoseconds
Some other refactorings improving comprehension
System.currentTimeMillis shouldn't be used for timeouts and it's non monotonic
> Rework LocalActivities waiting code to use nanoseconds

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
One of the previous changes introduced a bunch of excessive logging during the forced worker shutdown.
Improve handling of interrupted exceptions
> Cleanup forced worker shutdown from interrupted exceptions in the log

- temporal-sdk/src/main/java/io/temporal/internal/sync/AsyncInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-test-server/build.gradle
Add log warning if workflow eviction / closure is taking too long time to close.
Add guards making sure all threads are drained.
> Add log waring if workflow eviction / closure is taking too long time to close

- temporal-sdk/src/test/java/io/temporal/common/reporter/TestStatsReporter.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityTimeoutTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachine.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Fix use of thread in test server leading to parent workflow observing the completion of child workflows before the start in some cases.
Closes #1288
> Fix test server publishing the Completion of child workflows before the Start sometimes

- temporal-sdk/src/main/java/io/temporal/internal/Config.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityGettingScheduledRightBeforeWorkflowTaskHeartbeatTest.java
- temporal-testing/src/main/java/io/temporal/internal/Issue.java
Fixed situations when we didn't drain outstanding local activity requests which led to incorrect outstanding local activities counter value and erroneous closing of workflow tasks instead of performing a heartbeat.
Closes #1262
See #1262 for details
> Fix erroneous closing of workflow tasks instead of heartbeating in some edge cases

- temporal-sdk/src/main/java/io/temporal/common/converter/DefaultDataConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/common/SearchAttributePayloadConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
Currently, before the change, stacktrace query uses user-defined data converter to serialize its result.
After the change a standard default converter will always be used for serialization of stacktrace query result.
Stacktrace query is a built-in query for UI and tctl usage, hence a default converter should be used.
> Make stacktrace query result to be serialized using standard data converter only

- build.gradle
- temporal-test-server/build.gradle
By using ranges we were trying to relax requirements for users who were stuck on older lib versions by providing clear boundaries of supported versions.
Dependency version ranges create too many troubles with Maven users if some Temporal SDK dependency releases postfixed versions that are broken or incompatible and there is no existing solution to the problem. Maven supports either a range or a specific version, but not both. Which is a worse problem than the original problem we were having. It's time to move on.
> Switch from dependency version ranges to specific versions

- build.gradle
- temporal-sdk/src/test/java/io/temporal/activity/ActivityOptionsTest.java
- temporal-sdk/src/test/java/io/temporal/activity/LocalActivityMethodOptionsTest.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/ActivityTestingTest.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Fix TestActivityEnvironmentInternal#close preventing subsequent usages of the class by shutting down static members in the instance #close method.
Closes #928 #1133
> Fix TestActivityEnvironmentInternal#close preventing subsequent usages of the class

- temporal-kotlin/src/main/kotlin/io/temporal/common/metadata/WorkflowMetadata.kt
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOActivityInterfaceMetadata.java
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowImplMetadata.java
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowInterfaceMetadata.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ChildWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ContinueAsNewWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ExternalWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInvocationHandler.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/POJOWorkflowMetadataTest.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/testclasses/WorkflowInterfaceWithOneWorkflowMethod.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowExtension.java
This PR ports fix made for Activity Interface metadata resolution made in https://github.com/temporalio/sdk-java/pull/1083 into Workflow Interface metadata resolution logic.
Closes #1331
> Port static and jacoco synthetic methods fix from Activity interfaces to Workflows interfaces

- temporal-serviceclient/build.gradle
- temporal-test-server/build.gradle
Unfortunately, protobuf compiler continues to be haunted by problems with Apple Silicone. Upgrade to the latest release  to address problems like:
https://github.com/protocolbuffers/protobuf/issues/10136
https://github.com/protocolbuffers/protobuf/issues/9893
This change only affects builds executed on Apple Silicone and will not be applied to JavaSDK releases. We keep these dependencies as outdated as possible to provide the best backward compatibility for users.
> Upgrade protoc for Apple Silicone builds

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/ServiceStubsAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/TestServerAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/TestWorkflowEnvironmentAdapterImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ClientTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/NamespaceTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/TestWorkflowEnvironmentAdapter.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
Bring a level of indirection to don't require test framework classes to be in classpath for non-test functionality
Solves
```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [io.temporal.spring.boot.autoconfigure.ServiceStubsAutoConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc]
[12:25](https://temporaltechnologies.slack.com/archives/D029WJKUN15/p1660926322965759)
Caused by: java.lang.NoClassDefFoundError: io/temporal/testing/TestWorkflowEnvironment
at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[na:na]
at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309) ~[na:na]
at …
```
> Spring Boot Autoconfiguration doesn't require temporal-testing module to be in classpath anymore

- build.gradle
- temporal-kotlin/build.gradle
- temporal-kotlin/src/main/kotlin/io/temporal/common/converter/KotlinObjectMapperFactory.kt
- temporal-sdk/src/main/java/io/temporal/common/converter/JacksonJsonPayloadConverter.java
Code is reorganized in a way that the same basic Jackson config is used in java and kotlin modules. This also brings `mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)` to default kotlin config that may help prevent non-deterministic problems in case the replaying host has a different time zone than the original executor.
> Port config of default Jackson timestamp deserialization to kotlin

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/test/resources/logback-test.xml
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Test Server doesn't reset sticky queue if timeout fired for an outdated workflow task
> Test Server doesn't reset sticky queue if timeout fired for an outdated workflow task

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
Sets larger `maxInboundMetadataSize = MAX_INBOUND_MESSAGE_SIZE / 8` to accommodate unbounded Server error messages
Closes #1396
> Set larger maxInboundMetadataSize to accommodate unbounded Server error messages

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ServiceWorkflowHistoryIterator.java
After this change, workflow history iteration exceptions never fail workflow executions.
Even if `Throwable` is set on the failWorkflowExceptionTypes.
It's likely never an intention or expectation of the user that a workflow will start to fail on such internal machinery as workflow iterations and because of a temporary unavailable or a slow server. Also, workflow iteration exceptions are not like the state machine's `NonDeterministicException`, they are always retryable and recoverable. So it seems like failing a workflow execution on history iteration failures because of connectivity issues is always a bad idea. Instead, a Workflow Task should be failed.
> History iteration should never ever fail a workflow execution

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubsTemplate.java
Fixes guard clause in spring-boot-autoconfig to allow passing key and cert chain as strings.
> Fix guard clause to allow passing key and cert chain as strings

- build.gradle
- temporal-kotlin/src/main/kotlin/io/temporal/worker/WorkerExt.kt
- temporal-sdk/src/main/java/io/temporal/common/converter/CodecDataConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/payload/codec/ZlibPayloadCodec.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
Before this change `addWorkflowImplementationFactory(Class workflowInterface, Func<R> factory)` had a surprising behavior: it sets `WorkflowImplementationOptions.Builder#setFailWorkflowTypes` to `Throwable`. This leads to Workflow Execution failures on every exception that is thrown from the Workflow code (not just `TemporalFailures`). No other workflow implementation registration methods behave like that. Neither an overloaded `addWorkflowImplementationFactory` nor `registerWorkflowImplementationTypes`.
`addWorkflowImplementationFactory(Class workflowInterface, Func<R> factory)` is deprecated and replaced with `registerWorkflowImplementationFactory`. New method doesn't set `WorkflowImplementationOptions.Builder#setFailWorkflowTypes` to `Throwable`. …
> Deprecate addWorkflowImplementationFactory and give a register* alternative with an expected contract

- temporal-sdk/src/main/java/io/temporal/internal/worker/PollTaskExecutor.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
Change thread inactivity timeout from 1 second to 1 minute
Based on perf tests, thread churning for executors is real with the current settings.
> Reduce threads churn by increasing pool timeouts

- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowExecutorCache.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerCacheTests.java
Short-term fix for an elevated lock contention on workflow cache.
The long-term solution will be to remove `inProcessing` collection from the cache completely
> Reduce contention on workflow cache

- temporal-sdk/src/main/java/io/temporal/internal/worker/StickyPoller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
For matching performance optimizations of Temporal Server it's important to know if the poll comes for a sticky or a normal queue. Because sticky queues have only 1 partition, no forwarding is needed.
> Provide task queue kind in long polls for workflow tasks

- temporal-sdk/src/main/java/io/temporal/worker/ActiveThreadReportingExecutor.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
`ThreadPoolExecutor#getActiveThreads` implementation is taking a pool-wide lock and implements an actual counting inside this lock. This PR replaces it with an explicit counter to remove the points of threads serialization.
> Rework workflow threads reporting from using blocking ThreadPoolExecutor#getActiveThreads

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-spring-boot-autoconfigure-alpha/build.gradle
Now Workflow Task pollers reserve executor slots before attempting to perform a long poll.
This behavior is now aligned with the same mechanic for activities and what happens in GoSDK & Core.
Towards #998
> Implement executor slots reservation for workflow tasks

- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOActivityInterfaceMetadata.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInvocationHandlerBase.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/LocalActivityInvocationHandler.java
Reduce eagerly executed work needed to create an `ActivityStub`.
`ActivityStub`s are lighter to create. 
Currently, during the creation of an activity stub we eagerly prepare all of its methods to be called.
It leads to a huge amount of stubs preparation work every time JavaSDK creates a workflow instance.
Most of this work is lost because not all methods are called. Also if instances get evicted from the cache, it's also repetitive throwaway work. It also increases the amount of memory needed for each retained workflow instance.
> Reduce eagerly executed work needed to create an ActivityStub

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/StatusUtils.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Rework some reflection out of Test Server to help Graal
Graal doesn't like `Any.pack()` which goes into reflection to fetch a Descriptor.
Closes #1220
> Rework some reflection out of Test Server to help Graal

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
Trivial optimization that reduces reentry into the deterministic lock in WorkflowThread context.
> Reduce deterministic runner lock reentrance

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/StickyQueueBalancer.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkerThreadsNameHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerIsNotGettingStartedTest.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerPollerThreadCountTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
This PR brings behavior similar to GoSDK that balances the number of sticky pollers based on the knowledge of the sticky queue backlog received from the server
After looking at the behavior of workers in the high throughput scenario, it's clear that the static sticky:normal ratio is prone to the following scenario:
Under a high volume of Workflow Tasks workers continue to pull tasks from the normal queue when the sticky queue is already backlogged. This leads to the growth of sticky queues even more which in turn leads to the expiration of sticky workflow tasks and workflow cache churn. This effectively causes a snowballing effect causing more replays and decreasing of Workers throughput. The worker should pull less from a normal task queue if it can't manage its sticky queue.
Closes #998
> Implement dynamic sticky queue polling based on the reported backlog

- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
After #1438 `WorkerOptions.Builder#setMaxConcurrentWorkflowTaskPollers(1)` became an illegal configuration leading a worker to listen only on a sticky task queue. In this PR worker will override 1 to 2 and log a warning about it.
> SDK doesn't allow a single WorkflowTask poller and forces the value to '2' if specified

- docker/buildkite/docker-compose.yaml
- temporal-sdk/src/main/java/io/temporal/internal/worker/EagerActivityDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/EagerActivitySlotsReservation.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
Recently added eager activity dispatch leads to a leaky semaphore. If an activity is actually eagerly dispatched, the semaphore gets incremented twice.
Eager activity dispatch functionality needs better tests for potential semaphore leaks.
> Fix leaking Eager Activity Reservation

- temporal-sdk/src/main/java/io/temporal/internal/Config.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/EagerActivitySlotsReservation.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/EagerActivityDispatchingTest.java
Some workflow executions may cause a lot of activity invocations. With eager activity dispatch, all of these activity invocations may be dispatched to one worker causing an imbalance in workers' load.
Limit the activities that may be eagerly dispatched in one workflow task completion to 3 for now.
It's an open question if this should be configurable.
> Limit eager activity dispatch for one workflow task completion

- temporal-remote-data-encoder/build.gradle
- temporal-spring-boot-autoconfigure-alpha/build.gradle
- temporal-testing/build.gradle
`json-path` is included in `temporal-sdk` module as optional with `compileOnly` scope. It's not needed for most users because it's required only for operations with Temporal History jsons.
To make things easier for users, it's helpful for the testing module to bring this dependency transitively as most users work with history jsons in tests.
> testing module now brings json-path as a transitive dependency

- gradle/versioning.gradle
Rewrite the way the gradle build script determine the version number.
Previous logic would produce incorrect version number if git tag was of the form `1.17.0-RC1-2`, which would cause further build to fail.
See: https://buildkite.com/temporal/java-sdk-public/builds/1877#01838a2b-de0c-42e7-b44a-fe541f1e4570/791-853
> Fix incorrect handling of -RC suffix in version

- temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowCachingTest.java
Adds a diagnostic output for `taskTimeoutWillRescheduleTheTaskOnTheGlobalList` that has been caught flaking
> Add diagnostic output for flaky taskTimeoutWillRescheduleTheTaskOnTheGlobalList

- gradle/linting.gradle
- temporal-kotlin/.editorconfig
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowExecutorCache.java
- temporal-sdk/src/main/java/io/temporal/worker/MetricsType.java
- temporal-sdk/src/test/java/io/temporal/common/reporter/TestStatsReporter.java
- temporal-sdk/src/test/java/io/temporal/worker/StickyWorkerTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/MetricsTag.java
Cleanup WorkflowExecutorCache from the old pieces that are not relevant anymore after recent optimizations.
Rearrange checks in a flaky `StickyWorkerTest::whenStickyIsEnabledThenTheWorkflowIsCachedChildWorkflow` test.
Add notes regarding `sticky_cache_total_forced_eviction` being unusable in its current shape in java-sdk.
> Cleanup WorkflowExecutorCache

- build.gradle
- gradle/errorprone.gradle
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
- temporal-sdk/src/main/java/io/temporal/activity/LocalActivityOptions.java
- temporal-sdk/src/test/java/io/temporal/activity/DefaultActivityOptionsSetOnWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/activity/LocalActivityMethodOptionsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MemoTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/searchattributes/SearchAttributesTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestActivities.java
- temporal-serviceclient/build.gradle
- temporal-spring-boot-autoconfigure-alpha/build.gradle
- temporal-spring-boot-starter-alpha/build.gradle
- temporal-test-server/build.gradle
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestVisibilityStoreImpl.java
Update dependencies
Adapt the code to comply with new error-prone
Add a direct dependency to `org.springframework.boot:spring-boot-dependencies` BOM in temporal-spring-boot-starter-alpha to fix the problem with Maven not picking up platforms from the transitive dependencies.
Closes #1479
> Dependency updates and spring-boot-starter pom fix for Maven

- build.gradle
- docker/buildkite/Dockerfile-JDK11
- docker/buildkite/Dockerfile-JDK18
- docker/buildkite/Dockerfile-JDK8
openjdk DockerHub repo is Deprecated.
Moving from openjdk:x-slim to eclipse-temurin:x-jammy as a most compatible replacement
> Upgrade CI docker images from openjdk to eclipse-temurin

- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollerOptions.java
- temporal-serviceclient/src/main/java/io/temporal/internal/BackoffThrottler.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryerUtils.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcSyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/RpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubLongPollRpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubServiceOperationRpcRetryOptions.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcAsyncRetryerTest.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcSyncRetryerTest.java
Added longer retry interval on gRPC failures of type `RESOURCE_EXHAUSTED`. This interval delay is configurable by the user, but defaults to 1000 ms.
This failure code indicates the server is having a hard time. Aggressive retry will worsen the situation and could lead to more serious outage. See https://github.com/temporalio/sdk-features/issues/96
> Use longer retry interval on RESOURCE_EXHAUSTED

- docker/buildkite/docker-compose.yaml
Earlier a specific server version was fixed because of the regression in heartbeat behavior in the main branch. The problem is fixed, restoring the usage of the latest server build for CI/CD.
> Switch to the latest server in CI/CD

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/DescribeWorkflowExecutionTest.java
Test Server now doesn't default the last heartbeat time to the activity start time. Instead, the last heartbeat time will not be published if no heartbeats were made.
This is a port of a Temporal Server change that happened in https://github.com/temporalio/temporal/pull/3361
> Port a server fix for the last heartbeat time being defaulted to the activity started time

- build.gradle
- gradle/gatherDependencies.gradle
Adds `gatherRuntimeDeps` gradle task that creates `build/runtimeDeps` folder in each module. This folder contains all the dependencies that need to be in the runtime classpath of the module.
Helps to use java-sdk in projects that check out github repo and build the project from sources instead of using the released versions from Sonatype Rep.
> Add gatherRuntimeDeps task

- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestEnvironmentOptions.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/test/java/io/temporal/testing/junit5/TestActivityExtensionTest.java
Both `TestActivityEnvironment` and `TestWorkflowEnvironment` are accepting custom metricsScope from two sources: `TestEnvironmentOptions#metricsScope` and `TestEnvironmentOptions#workflowServiceStubsOptions#metricsScope`, where it is overridden by the user.
Both environments had several bugs in how `TestEnvironmentOptions#workflowServiceStubsOptions#metricsScope` is treated, `TestActivityEnvironment` was respecting `TestEnvironmentOptions#metricsScope` only for `WorkflowClientOptions` purposes, but not passing it as activity custom metrics scope.
Closes #1412
> Test Environments now respect metricsScope passed in TestEnvironmentOptions and ServiceStubOptions

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ActivityStateMachine.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityTimeoutTest.java
- temporal-spring-boot-autoconfigure-alpha/build.gradle
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
This PR adds more test cases verifying the behavior across TestServer and a real Temporal Server for Activity Timeout Failures.
One of the tests shows strange behavior of the real server, which was mimicked in the Test Server with a TODO, showing that this behavior is inconsistent and looks like a bug. This needs further investigation and maybe more tests to be sure what happens there.
This PR is a continuation of the work started in #1514
Depends on #1524 to be merged first
Prerequisite for: #1004 #1507
> More activity timeout failure compliance tests and improvements

- build.gradle
- temporal-sdk/src/main/java/io/temporal/activity/ActivityOptions.java
- temporal-sdk/src/main/java/io/temporal/activity/LocalActivityOptions.java
- temporal-sdk/src/main/java/io/temporal/common/RetryOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/common/RetryOptionsUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ExecuteLocalActivityParameters.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/LocalActivityStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityAttemptTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityResult.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkerThreadsNameHelper.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/test/java/io/temporal/internal/common/RetryOptionsUtilsTest.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/OutdatedDirectQueryReplayWorkflowRunTaskHandlerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/LocalActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityTimeoutTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LongLocalActivityWorkflowTaskHeartbeatBufferedEventTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LongLocalActivityWorkflowTaskHeartbeatTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowCancellationTest.java
This PR implements a timer thread that independently of the local activity executors performs lifecycle management of local activities and allows to enforce timeouts.
The interface between LA workers and workflow code / state machines is reworked to allow LA workers to communicate different failure reasons / retry back to the workflow.
`startToClose` timeout and `scheduleToClose` timeout supports are implemented.
The ground is prepared for adding scheduleToStart timeout for local activities #1512
The workflow/LA interface is improved to prepare for #1261
Previously Local Activities scheduling and management code were trivial.
One thread executes the activities, waits with sleep until the next attempt, and executes the next attempt.
While being simple, there is a bunch of Cons to this …
> Rework Local Activity scheduling

- temporal-serviceclient/build.gradle
Add generated proto classes info into javadoc jar, aligning it's content with sources jar.
This will add docs generated from api repo comments into javadocs.
Closes #1532
> Add generated proto classes info into javadoc jar

- temporal-test-server/src/main/proto/temporal/api/testservice/v1/request_response.proto
- temporal-test-server/src/main/proto/temporal/api/testservice/v1/service.proto
Update namespace/package for Ruby/C# to `Temporalio` instead of `Temporal`.
Like https://github.com/temporalio/api/pull/251, we are changing these namespaces in these SDKs.
> Update C# and Ruby namespace/package for test server protos

- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingActivityInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowClientCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
There is no big reason to use workflow time in spans. It actually may be confusing even during replay to get spans "started in the past".
Usage of Workflow Time creates problems for users that attempt to use span structures and data for profiling, especially on the milliseconds level.
> Remove usage of Workflow time from tracing spans

- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironment.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/test/java/io/temporal/testing/TestActivityEnvironmentHeartbeat.java
Adds a `setHeartbeatDetails` method to `TestActivityEnvironment`. This will make the provided details object available with the next activity execution's call to `ActivityExecutionContext#getHeartbeatDetails`. The details object is cleared when it is applied to an activity execution.
As written this only applies to Activity Executions, not Local Activity Executions. My understanding is that Local Activities do not support heartbeating; if I'm wrong here it is trivial to extend support.
Activities can send a "details" object when heartbeating, and that details object is made available to the next run of that activity, should it need to be retried. One of the obvious applications of this as a progress marker; e.g., an activity which is performing a number of tasks can potentially use the …
> Set heartbeat details for TestActivityEnvironment

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityResult.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/LocalActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityThrowingApplicationFailureTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityThrowingErrorTest.java
- temporal-spring-boot-autoconfigure-alpha/build.gradle
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironment.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
Now if a Local Activity throws an `Error`, it will lead to WFT failure, not a failure of activity execution.
Closes #1533
> Fail WFT if Local Activity execution experienced an Error

- gradle/licensing.gradle
- temporal-sdk/src/main/java/io/temporal/internal/replay/BasicWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowMutableState.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/OutdatedDirectQueryReplayWorkflowRunTaskHandlerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/WorkflowMutableStateTest.java
- temporal-serviceclient/build.gradle
- temporal-test-server/build.gradle
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Exposing an ability to fail WorkflowTask for any callback in executor code
Refactored a clean separate WorkflowMutableState.
After this change, `ReplayWorkflowContext` has a clean logic over two complementary mutable entities - `WorkflowStateMachines` and `WorkflowMutableState`. Workflow mutable state fields are not scattered over the workflow control (executor) codebase anymore.
This also creates a solid ground to migrate `WorkflowMutableState` into states of state machines in `WorkflowStateMachines` (defining WorkflowStateMachine)
> Exposing an ability to fail WorkflowTask for any callback in executor code

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Added ActivityOutput.activityId. 
The ActivityOutput is used by interceptors, and knowing `activityId` is important for some use cases.
The change is not backward compatible if an interceptor uses ActivityOutput constructor. I believe that there are very few (if any) interceptors that create ActivityOutput explicitly.
> Added ActivityOutput.activityId

- build.gradle
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/test/java/io/temporal/client/functional/QueryAfterStartFollowsRunsChainTest.java
Previously if workflow stub was created and used to start a workflow, query on this stub was targeting the specific runId that was created by this stub and didn't follow the chain of runs.
Now the workflow stub follows the chain of runIds until it is explicitly created for a specific runId.
This PR also cleans up the messy internals that provided potentially outdated runIds in logs of operations that were not targeting a specific runId.
Closes #1601
> Now query on workflow stub that was was used for start follows runIds 

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowExecutionHandler.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityApplicationFailureNonRetryableTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/DirectQueryReplaysDontSpamLogWithWorkflowExecutionExceptionsTest.java
TemporalFailure thrown from Signal method now fails Workflow Execution.
With this change, an exception thrown from a signal method is getting treated the same way as an exception thrown in the workflow method.
Closes #1615
> TemporalFailure thrown from Signal method now fails Workflow Execution

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/AutoConfigurationUtils.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/MetricsScopeAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/ServiceStubsAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/TestServerAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ClientTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/NamespaceTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/resources/META-INF/spring.factories
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/CustomDataConverterTest.java
Sprint Boot TestWorkflowEnvironment now respects configured MetricsRegistry, Tracer, DataConverter
Closes #1463
> Sprint Boot TestWorkflowEnvironment now respects configured MetricsRegistry, Tracer, DataConverter

- temporal-remote-data-encoder/src/main/java/io/temporal/rde/httpserver/DataEncoderHandler.java
Added OPTIONS HTTP call support and CORS headers into Remote Data Encoder Server sample implementation
To reduce friction with Web browsers for users who may want to use our sample implementation directly
> Add CORS headers to the RDE Server sample implementation

- .buildkite/pipeline.yml
- build.gradle
- docker/buildkite/Dockerfile-JDK18
- gradle/java.gradle
- temporal-kotlin/build.gradle
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/ConnectionProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/NamespaceProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/TemporalProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/TestServerProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkersAutoDiscoveryProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Fix incompatibilities with Sprint Boot 3.
Add `edgeDepsTest` profile that is going to use the latest dependencies versions for compatibility testing.
Closes #1619
> Spring Boot 3 support

- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-spring-boot-autoconfigure-alpha/README.md
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/ActivityImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/WorkflowImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/AutoDiscoveryByTaskQueueTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/AutoDiscoveryByWorkerNameTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/CustomDataConverterTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/ExplicitConfigTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/WorkersAreNotStartingBeforeContextTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/bytaskqueue/TestActivity.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/bytaskqueue/TestActivityImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/bytaskqueue/TestWorkflow.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/bytaskqueue/TestWorkflowImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/TestActivity.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/TestActivityImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/TestWorkflow.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/TestWorkflowImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/test/resources/application.yml
Added a concept of Worker Name. Worker Name defaults to Worker Task Queue, but can be explicitly set. Worker Name can be used by auto-discovery annotations instead of Task Queues. 
Application that incorporates [Task Queue based Versioning strategy](https://community.temporal.io/t/workflow-versioning-strategies/6911) may choose to use explicit Worker names to reference because it adds a level of indirection. 
This way Task Queue name is specified only once in the config and can be easily changed when needed, while all the auto-discovery annotations reference the Worker by its static name.
> Add auto discovery binding strategy by worker name to Spring Boot

- build.gradle
- temporal-kotlin/build.gradle
- temporal-spring-boot-autoconfigure-alpha/README.md
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/TemporalOptionsCustomizer.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/WorkerOptionsCustomizer.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/ServiceStubsAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/TestServerAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ClientTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/NamespaceTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerFactoryOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowClientOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/OptionsCustomizersTest.java
Add TemporalOptionsCustomizer to allow users to modify the options constructed by Spring Boot Auto Configuration
Supported `*Options.Builder` classes for customization:
- `WorkerOptions.Builder`
- `WorkerFactoryOptions.Builder`
- `WorkflowServiceStubsOptions.Builder`
- `WorkflowClientOptions.Builder`
- `TestEnvironmentOptions.Builder`
Closes #1394
> Add TemporalOptionsCustomizer to allow users to modify the options constructed by Spring Boot Auto Configuration

- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-spring-boot-autoconfigure-alpha/README.md
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/TestServerAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/NamespaceProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/TemporalProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerFactoryOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowClientOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/OptionalWorkerOptionsTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/resources/application.yml
Wire into Spring Boot Configuration:
- workflow cache size
- worker executors
- worker pollers
- worker rate limiting properties
Closes #1488
> Wire some WorkerFactoryOptions and WorkerOptions properties to Spring Boot Configuration

- .buildkite/pipeline.yml
- build.gradle
- docker/buildkite/Dockerfile-JDK19
- docker/buildkite/docker-compose.yaml
- gradle/linting.gradle
- temporal-kotlin/.editorconfig
- temporal-serviceclient/build.gradle
- temporal-test-server/build.gradle
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
Make Apple Silicone build to use the same protoc and protoc-gen-grpc-java versions as Temporal JavaSDK uses for publishing release artifacts
Update temporal/api protos
Move Edge build profile onto Java 19
Use new #namespace on AddSearchAttributes request
> Update protos, use #namespace in register SA request, use old protoc on M1 

- temporal-sdk/src/main/java/io/temporal/client/EagerPaginator.java
Use `ByteString.EMPTY` instead of `ByteString.empty()` in `EagerPaginator`
The `empty()` method appears to have been introduced in protobuf 3.20.0-rc1 ([blame](https://github.com/protocolbuffers/protobuf/blame/b1109ff985b4f6382981a16cc6e46a5fb4704800/java/core/src/main/java/com/google/protobuf/ByteString.java#L241)). Using `EMPTY` instead allows the Temporal SDK to work with older versions of the protobuf library, going back to the minimum supported 3.10.0.
Moreover, this method does not seem to be listed in the [proto Javadoc](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/ByteString.html).
1. Closes 
n/a
- Existing tests run with `./gradlew test` continue to pass
- Used this change in a Java workflow worker service running …
> Use ByteString.EMPTY in EagerPaginator

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NoopWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Startable.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Suspendable.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkerLifecycleState.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkerWithLifecycle.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-spring-boot-autoconfigure-alpha/build.gradle
`isStarted` method was removed from internal Workers because of the potential duality of its meaning.
Internal SDK workers got explicit states in addition to `isX` methods.
Eager Activity Dispatch was fixed to be requested if Activity Worker is in an ACTIVE state.
Needed to correctly implement #1646 and #1230 
The current `isStarted` method already caused at least one potentially incorrect usage that may lead an eager dispatch to be requested for a suspended worker.
> Fix Eager Activity Dispatch Worker state check, rework states of internal Workers

- gradle/publishing.gradle
- temporal-shaded/build.gradle
temporal-shaded descriptor is getting published with `<packaging>pom</packaging>` which requires to include both the pom and the jar as a separate artifact. This PR fixes that.
> Fix temporal-shaded packaging type

- temporal-shaded/build.gradle
Currently, GSON is getting relocated, but not supplied in the final shadow jar.
This PR adds specificity to relocation for `com.google` to avoid GSON relocation.
> Don't relocate com.google.gson during shadowing

- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/test/java/io/temporal/client/functional/GetExecutionAfterStartTest.java
WorkflowStub#getExecution now returns started execution after `signalWithStart`
Change https://github.com/temporalio/sdk-java/pull/1612 introduced a bug with WorkflowStub not returning execution anymore after signalWithStart.
Closes #1667
> Fix WorkflowStub#getExecution returning null after signalWithStart

- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LongLocalActivityFailsWhileHeartbeatingMeteringTest.java
Closes https://github.com/temporalio/sdk-java/issues/1672
This test is timing sensitive in terms of which retries end up in which tasks - the main thing is to ensure that the not-first WFTs contain the attempts.
> Fix overly sensitive count checks in la metering test

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowIdReusePolicyTest.java
Terminates any existing execution in the test service when the terminate-if-running workflow ID reuse policy is specified. A new test has been added for this case, but also some basic workflow ID reuse policy test cases.
Starting a workflow with this policy when another is already running throws `WorkflowExecutionAlreadyStarted` rather than the existing execution being terminated and a new run being started.
1. Closes https://github.com/temporalio/sdk-java/issues/1682
New unit tests in `temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowIdReusePolicyTest.java`
> Support terminate-if-running workflow ID reuse policy in test server

- temporal-sdk/src/main/java/io/temporal/failure/DefaultFailureConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityTaskHandlerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/common/env/ReflectionUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DynamicSyncWorkflowDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/resources/temporal-sdk/reflect-config.json
The initialization of stacktrace cutoff lines was reworked from static Strings using reflection and the new approach will guarantee that even after future changes the constants will contain the correct values.
Stacktrace cutoff points were hardcoded and got out of sync during SDK refactorings
> Fix stacktrace cutoff methods initialization

- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ShutdownManager.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityTimeoutTest.java
Now Workflow and Activity workers will wait for the release of all worker slots during a graceful shutdown.
This improvement allows graceful shutdown to respect all existing eager dispatch handles, so it doesn't happen that a WorkflowClient gets an eager task from the Server, but there is nowhere to dispatch it already.
An added beneficial side effect: this allows us to detect and make sure in our testing framework that there are no executor slot leaks happening. Leaking executor slots will lead to long / unlimited graceful shutdowns.
> Wait for worker slots to be fully released in the graceful worker shutdown

- releases/v1.19.1
Fixes native test server distribution not working correctly if search attributes are used.
JavaSDK users don't need to upgrade to this release until they build their own native test server distribution.
2023-03-23 - 5d980b3b - Fix location of graal descriptors and a missing reflection reference for temporal-sdk module (#1713)
> Release v1.19.1

- temporal-sdk/src/main/java/io/temporal/internal/replay/BasicWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
While adding `getOriginalExecutionRunId` method in the previous release I made a mistake by copying `getContinuedExecutionRunId` signature and made the return value `Optional<String>`.
This is an incorrect type and makes users think that they should account for situations when this value is not present.
This change is backward incompatible for users of `getOriginalExecutionRunId` method and will require a trivial refactoring. I expect the number of users to be affected as close to 0, because this method is not just very new and silently added for a specific user, but also most users should never use it and go for `getFirstExecutionRunId` instead.
> Fix getOriginalExecutionRunId return value and add explicit @NonNull annotations

- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
User-facing method was deprecated without an appropriate explanatory and replace-with comment.
> Add comment on Workflow#newQueue

- build.gradle
- gradle/jacoco.gradle
- temporal-sdk/src/main/java/io/temporal/common/converter/CodecDataConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/DataConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityTaskExecutors.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/QueryDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SignalDispatcher.java
- temporal-sdk/src/test/java/io/temporal/common/converter/JsonDataConverterTest.java
- temporal-spring-boot-autoconfigure-alpha/build.gradle
`DataConverter` interface got a new method `fromPayloads` that convert all the payloads at once with default implementations that uses one-by-one conversion.
`CodecDataConverter` implements the new method in a way that avoids calling the codec several times for each Payload.
Closes #1345
> Data Converters now have method deserializing all the Payloads at once

- temporal-sdk/src/main/java/io/temporal/internal/sync/UpdateDispatcher.java
`arrayFromPayloads` was deprecated between opening the original PR and merging it, but out CI build did not catch this on rebase.
> Remove use of deprecated API

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/ActivityImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/WorkflowImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/AutoDiscoveryByTaskQueueResolverTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/bytaskqueue/TestActivityImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/bytaskqueue/TestWorkflowImpl.java
- temporal-spring-boot-autoconfigure-alpha/src/test/resources/application.yml
Make WorkerTemplate implement `EnvironmentAware` so that it can use the Spring environment to resolve property placeholders in task queue names to allow more dynamic naming while utilizing the `workers-auto-discovery`
To enable more dynamic usage when utilizing the @WorkflowImpl and @ActivityImpl annotations, along with the workers-auto-discovery feature, this allows the task queue name values to be Spring property placeholder that will be resolved and populated by Spring at runtime.
1. Closes #1759 
Added additional integration tests checking both for when the property value exists in the configuration and when the value does not exist
Javadoc was updated to indicate that the values can utilize the property placeholder syntax but no …
> Allow task queue names to use property placeholders

- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateRetryException.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateWithLocalActivity.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateWithSignalAndQuery.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableState.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Add support for sync update to the test server.
> Add support for update to the Java test server

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/RunnerLocalInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThread.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadLocalInternal.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowLocalsTest.java
See https://github.com/temporalio/sdk-java/pull/1777 for background/most thoughts. This is the more ambitious fix that tries to resolve the "not set"/"null" ambiguity.
Closes #1761 
Nested `Optional` didn't feel great, but I preferred it over the other solutions like "an `Optional` that is also nullable".
> Issue 1761 fix supplier reuse

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/LongPollUtil.java
Treat `UpdateWorkflowExecution` as a long poll.
See also https://github.com/temporalio/sdk-go/pull/1123
> Treat UpdateWorkflowExecution as a long poll

- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
added info about setting to 0 causes using the default value for the following methods:
- setMaxConcurrentWorkflowTaskPollers
- setWorkflowPollThreadCount (deprecated)
- setMaxConcurrentActivityTaskPollers
- setActivityPollThreadCount (deprecated)
I had to look up the code to find out about this behaviour. For other methods, the behaviour of setting to 0 was documented, e.g.
- setMaxConcurrentWorkflowTaskExecutionSize(1)
- setMaxConcurrentActivityExecutionSize(1)
> WorkerOptions extend javadocs for default values

- temporal-sdk/src/main/java/io/temporal/failure/DefaultFailureConverter.java
- While rehydrating Protobuf Failures to Java Exception objects, don't NPE on malformed/truncated stack traces
> Avoid NPE on malformed/truncated failure stack traces

- releases/v1.20.0
This version adds support for the schedule API to help users run workflows periodically.
Note: the following two features will require support from the Temporal server, to be available in release v1.21.0.
This version adds support for our new Worker Versioning feature. Please note that this feature's API is subject to
change. This feature allows you to assign build identifiers to workers, and ensure that workers operating on a task
queue do not receive tasks that they will be incompatible with. You declare the relative [in]compatibility of build
identifiers. We will be publishing documentation on this feature soon (and these notes will be updated with a link).
This version adds support for Workflow update. Workflow update is another way to interact with a running workflow along
with …
> Release v1.20.0

- temporal-sdk/src/main/java/io/temporal/activity/ActivityInfo.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityInfoImpl.java
Expose started time in `ActivityInfo`
closes https://github.com/temporalio/sdk-java/issues/1797
> Expose started time in ActivityInfo

- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Add support for SDK metadata to the test server and reflect that in system info. Needed to implement SDKFlags
close https://github.com/temporalio/sdk-java/issues/1746
> Add support for SDK metadata to test server

- gradle/dependencyManagement.gradle
- gradle/gatherDependencies.gradle
- gradle/java.gradle
- gradle/licensing.gradle
- gradle/linting.gradle
- gradle/publishing.gradle
- settings.gradle
- temporal-bom/build.gradle
Added a `temporal-bom` subproject that publishes a bom using Gradle's [java-platform plugin](https://docs.gradle.org/current/userguide/java_platform_plugin.html).
Most of the script plugins (`dependencyManagement.gradle`, `java.gradle`, etc) are built around the assumption each module is a java module. I excluded this project by name for this change.
BOMs are useful for keeping versions aligned, especially when they are brought in only as transitive dependencies.
Example without a bom:
```
runtimeClasspath
+--- org.example:some-library:1.0.0
|    +--- io.temporal:temporal-serviceclient:1.15 (misaligned)
\--- io.temporal:temporal-sdk:1.20
```
Other examples of java libraries producing similar boms: [junit-bom](https://repo1.maven.org/maven2/org/junit/junit-bom/5.9.3/junit-bom-5.9.3.pom), …
> Generate bom using java-platform plugin

- temporal-sdk/src/main/java/io/temporal/common/converter/DataConverter.java
Add default methods for `exceptionToFailure` and `failureToException`
closes:
https://github.com/temporalio/sdk-java/issues/1808
> Add default methods for exceptionToFailure and failureToException

- releases/v1.20.1
Default implementation for exceptionToFailure and failureToException to fix an unintentional breaking change
in the DataConverter interface.
2023-06-27 - 57cb086f - Add support for SDK metadata to test server (#1800)
2023-06-27 - c6aadda8 - Expose started time in ActivityInfo (#1798)
2023-06-29 - 9a457157 - Generate bom using java-platform plugin (#1796)
2023-07-03 - 15337d9a - Add Semgrep scanning (#1775)
2023-07-10 - 25387be8 - Add default methods for exceptionToFailure and failureToException (#1809)
> Release 1.20.1

- temporal-bom/build.gradle
sonatype requires a description of all packages to upload.
Somehow the snapshot builds where able to upload fine...
> Add description to bom project

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/TestServerAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ClientTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/NamespaceTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowClientOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/ClientOnlyTest.java
Adds support to autowire ScheduleClient.
Schedule apis are not yet implemented for test env so if you have idea what other test can be added please let me know.
Closes https://github.com/temporalio/sdk-java/issues/1812
> ScheduleClient for SpringBoot

- temporal-sdk/src/main/java/io/temporal/internal/common/SdkFlag.java
- temporal-sdk/src/main/java/io/temporal/internal/common/SdkFlags.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowTaskResult.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/VersionStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/OutdatedDirectQueryReplayWorkflowRunTaskHandlerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerCacheTests.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncActivityRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionAfterScopeCancellationInMainWorkflowMethodTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionInSignalOnReplayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionMultithreadingTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionTest.java
- temporal-sdk/src/test/resources/testGetVersionDefaultMultithreadingHistory.json
- temporal-sdk/src/test/resources/testGetVersionHistory.json
- temporal-sdk/src/test/resources/testGetVersionInSignalHistory.json
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Fix a possible source of non determinism in `GetVersion` calls. Since `GetVersion` can block on a future adding a call to it in a workflow can lead to non determinism so we need to avoid doing so in a backwards compatible way.
I tried to refactor the Version state machine to avoid ever blocking, but found the work too complicated for the benefit since due to backwards compatibility we can never remove the old state machine.
closes https://github.com/temporalio/sdk-java/issues/1430
> Make GetVersion more deterministic

- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ChildWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ChildWorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ExternalWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ExternalWorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/LocalActivityInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/LocalActivityStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/test/java/io/temporal/workflow/BadMutableSideEffectTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/BadSideEffectTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateBadValidator.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Block calling most mutating workflow functions in read only context. This includes update validators and side effects.
Note: This does not include queries because queries are not run in a workflow thread
> Block mutating workflow state in a read only context

- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowWorkerTest.java
Add test to verify the workflow worker hold a lock when processing a WFT, including reseting event ID
> Add unit test for concurrent WFT

- docker/buildkite/dynamicconfig/development.yaml
Fix test failures like https://buildkite.com/temporal/java-sdk-public/builds/2754
> Adjust MaxBufferedQueryCount

- temporal-sdk/src/main/java/io/temporal/internal/client/RootScheduleClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
Wrap exceptions from the `ScheduleClient`. Add some tests to show the exception is wrapped
> Properly wrap exceptions from schedule client

- releases/v1.21.0
Release Java SDK 1.21.0
Making a new minor version because of the read only protections
> Release 1.21.0

- .github/workflows/prepare-release.yml
Use `buildjet-2vcpu-ubuntu-1804` to build the test server.
GitHub deprecated the 18.04 runners, which we need to support older versions of glibc.
My editor automatically ran prettier on the yaml file, I can revert that if reviewer has an issue.
> Build test server on ubuntu 18

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/VersionStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionDefaultInSignalTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionMultipleCallsDefaultTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionMultipleCallsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionOutOfOrderFailTest.java
- temporal-sdk/src/test/resources/testGetVersionMultipleCallsHistory.json
- temporal-sdk/src/test/resources/testGetVersionMultipleCallsHistoryDefault.json
- temporal-sdk/src/test/resources/testGetVersionOutOfOrderFail.json
Fix a bug in `VersionStateMachine` causing `DEFAULT_VERSION` to get returned incorrectly if the same change ID was read multiple times in a Workflow. This was missed in the original [fix](https://github.com/temporalio/sdk-java/commit/6054c315e934f4a9b295f2da85c8ae003851c4d7) because we lacked some basic tests of the `VersionStateMachine`
> Fix bug in VersionStateMachine causing wrong version to get returned

- .github/workflows/prepare-release.yml
When we updated our build runner, github started complaining about unbound variable `attempts `. Removing it because it doesn't provide much value.
The reason this code retries at all is because there is a human in the loop to publish the release.
> Remove unbound variable

- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleActionStartWorkflow.java
- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleDescription.java
- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleOptions.java
- temporal-sdk/src/main/java/io/temporal/common/SearchAttributeKey.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootScheduleClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/common/SearchAttributePayloadConverter.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleWithTypedSearchAttributesTest.java
Fix typed search attributes in java schedules by:
* Adding typed search attributes to `ScheduleOptions`
* Documenting old `SearchAttributes` do not work when creating a schedule
* Allow for untyped search attributes in the `SearchAttributes` container through a special key type
closes https://github.com/temporalio/sdk-java/issues/1847
> Reconcile typed search attributes with schedules

- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/StickyQueueBacklogTest.java
Reset sticky queue backlog on an empty or failed response. This fixes a bug where the worker gets stuck only polling the stick task queue if all the pollers are polling the sticky queue and all the WFT get moved to the normal task queue since the worker will then never update its' backlog count.
This aligns with how the [Go SDK works](https://github.com/temporalio/sdk-go/blob/b7931cbfb1de6e5797a0dded2163b63d8a5836e8/internal/internal_task_pollers.go#L770)
closes https://github.com/temporalio/sdk-java/issues/1858
> Reset sticky queue backlog on empty response

- temporal-opentracing/src/main/java/io/temporal/opentracing/SpanOperationType.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ActionTypeAndNameSpanBuilderProvider.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowClientCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/SignalWithStartTest.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ChildWorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ExternalWorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/QueryDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SignalDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/UpdateDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowExecutionHandler.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerCacheTests.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/QueryDispatcherTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
Improve support for tracing signals, queries, and updates.
Our team encountered issues with tracing not being supported across workflow signals, queries, and updates when using temporal. I am proposing a proof of concept to address this, and if it is accepted, I will handle the necessary improvements and tests.
Note:
I have manually tested this in our test environment, and it appears to be working. However, as mentioned earlier, I will add tests after the initial review.
> Tracing support improvements

- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowWorkerTest.java
A user noticed that if their workflow task failed with `UnableToAcquireLockException` their worker would not be able to shutdown. Root cause was on `UnableToAcquireLockException` we didn't call `task.getCompletionCallback().apply();` because the exception was outside the `finally` block. 
Note: this will change the timing of `WORKFLOW_TASK_EXECUTION_TOTAL_LATENCY` to include the time waiting for the run lock, but this metric is java specific and is undocumented, and arguably should include the run lock.
close https://github.com/temporalio/sdk-java/issues/1870
> Release WF slot on UnableToAcquireLockException

- releases/v1.21.2
> Release Java SDK v1.21.2

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/OptionalWorkerOptionsTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/resources/application.yml
Expose worker versioning via spring boot autoconfig
https://github.com/temporalio/sdk-java/issues/1856
> Expose worker versioning via spring boot autoconfig

- temporal-sdk/src/main/java/io/temporal/internal/context/ContextThreadLocal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/RunnerLocalInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadLocalInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowLocal.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowThreadLocal.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowLocalsTest.java
Reverted caching changes made to WorkflowLocal/WorkflowThreadLocal, which broke backwards compatibility and accidentally shared values between Workflows/Threads. Re-implemented caching as an optional feature, and deprecated the factory methods that created non-caching instances.
The current implementation both broke backwards compatibility, and did not function correctly; it shared values between Workflows and Threads when it should not have. See https://github.com/temporalio/sdk-java/issues/1876 for details.
1. Closes #1876 
Unit tests
I don't think `WorkflowLocal`/`WorkflowThreadLocal` are documented outside of Javadocs, so no.
> Fix caching in WorkflowLocal/WorkflowThreadLocal (#1876)

- gradle/java.gradle
Added the `-parameters` compiler argument for several classes, addressing the `MissingParametersCompilerArgumentException` during native image compilation in projects using Temporal.
This change is critical to enable users to compile their projects into native images without encountering `MissingParametersCompilerArgumentException`. It facilitates smoother and error-free native compilations, especially for projects relying on Temporal’s classes for constructor injection. By ensuring the parameter names are available at runtime via reflection, it mitigates runtime issues and enhances the user experience in native environments.
1. Closes 
#1840
The project was built and tested locally, and the `MissingParametersCompilerArgumentException` error was no longer present. …
> Support Spring Boot 3 native image build

- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/test/java/io/temporal/workflow/EagerWorkflowTaskDispatchTest.java
Disable eager start by default because it does not interact with worker versioning well.
> Disable eager start by default

- temporal-sdk/src/main/java/io/temporal/internal/replay/ServiceWorkflowHistoryIterator.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ServiceWorkflowHistoryIteratorTest.java
It is valid behaviour for the server to respond to `GetWorkflowExecutionHistory` with no events, but a next page token, and that page token may point to a page with more events for the SDK to process. Before this change the SDK would stop looking if it saw a page with no events without also checking if the next page token was populated.
> Only rely on next page token for pagination

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateWithSignalAndQuery.java
On a rejected speculative WFT we also need to reset `lastHandledEventId` so we don't accidentally skip new workflow tasks.
```
public void handleEvent(HistoryEvent event, boolean hasNextEvent) {
long eventId = event.getEventId();
if (eventId <= lastHandledEventId) {
// already handled
return;
}
...
``` 
We also should delete any new state machines created by the speculative task
closes https://github.com/temporalio/sdk-java/issues/1880
> Reset lastHandledEventId on speculative WFT

- build.gradle
Update Spring Boot to mitigate a few CVEs. Note we aren't directly exposed to any of those.
closes https://github.com/temporalio/sdk-java/issues/1768
> Update Spring Boot to v2.7.12

- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowWorkerTest.java
Avoid incrementing WFT failure metric on respond failure. This aligns Java with other SDKs.
closes https://github.com/temporalio/sdk-java/issues/1885
> Avoid incrementing WFT failure metric on respond failure

- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientRequestFactory.java
- temporal-sdk/src/test/java/io/temporal/client/functional/SignalTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/StartTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Add start delay
closes https://github.com/temporalio/sdk-java/issues/1863
> Add start delay

- temporal-sdk/src/main/java/io/temporal/client/WorkflowExecutionMetadata.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootScheduleClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/ScheduleProtoUtil.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/payload/context/HasWorkflowSerializationContext.java
- temporal-sdk/src/test/java/io/temporal/functional/serialization/WorkflowIdSignedPayloadsTest.java
Add data converter context to memo, lastFailure and schedules.
Schedules don't interact well with `WorkflowContext` because the full workflow ID (only a prefix) is not available when serializing the input. The workflow ID may also be changes after the input is serialized. The workflow ID will also be wrong on APIs like getting the previous result or failure.
closes https://github.com/temporalio/sdk-java/issues/1895
> Apply data converter context in more places

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerTaskHandlerTests.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
Verify history is replayed up to StartedEventId. Previously the Java SDK did not verify it repalyed up to StartedEventId sent on the poll request when processing a workflow task. This lead to the Java SDK not replaying the full workflow history if it was fetching history using GetWorkflowExecutionHistory after receiving a partial history with no cached execution and hitting a stale history node.
Go SDK also has a similar check: https://github.com/temporalio/sdk-go/blob/3cccbdd5f47d640fffe6651e4f49c236a4803a47/internal/internal_task_handlers.go#L383
closes https://github.com/temporalio/sdk-java/issues/1915
> Verify history is replayed up to StartedEventId

- temporal-sdk/src/main/java/io/temporal/internal/sync/ReadOnlyException.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateBadValidator.java
Based on previous discussions ReadOnly exceptions in update validators should still fail the WFT instead of the update
> ReadOnly Exception in update validator fail WFT

- docker/buildkite/dynamicconfig/development.yaml
- temporal-sdk/src/main/java/io/temporal/client/BuildIdReachability.java
- temporal-sdk/src/main/java/io/temporal/client/WorkerTaskReachability.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowClientInternalImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/test/java/io/temporal/client/functional/BuildIdVersionSetsTest.java
Add getWorkerTaskReachability API
closes  https://github.com/temporalio/sdk-java/issues/1862
> Add getWorkerTaskReachability API

- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityInTheLastWorkflowTaskTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalWithLocalActivityInTheLastWorkflowTaskTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateWithLocalActivityInTheLastWorkflowTaskTest.java
Add some test coverage to running async local activities while trying to continue as new
> Test continue as new with local activities

- temporal-sdk/src/main/java/io/temporal/workflow/ChildWorkflowOptions.java
Similar to https://github.com/temporalio/sdk-typescript/pull/1193. 
Fixing the inline comments where `AllowDuplicate` should be noted as the default policy.
> Update Workflow ID reuse policy for java doc

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalContinueAsNewNonDeterminism.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalContinueAsNewWFTFailure.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateContinueAsNewNonDeterminism.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateContinueAsNewWFTFailure.java
Treat signal after workflow complete as NonDeterministicException. I see this exception confusing users as they think their is something wrong with the temporal service or the SDK when it is normally their workflow code.
> Treat signal after workflow complete as NonDeterministicException

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/KeepAliveTest.java
Enable TCP keep alive by default. Settings take from https://github.com/temporalio/features/issues/123
closes https://github.com/temporalio/sdk-java/issues/1872
> Enable TCP keep alive by default

- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/MetricsTag.java
This PR adds a tag to `workflow_task_execution_failed` called `failure_reason` that can be equal to `WorkflowError| NonDetermismError` depending on why the workflow task failed.
closes https://github.com/temporalio/sdk-java/issues/1929
> Tag workflow_task_execution_failed with error type

- temporal-sdk/src/main/java/io/temporal/internal/common/ProtobufTimeUtils.java
- temporal-sdk/src/test/java/io/temporal/internal/common/ProtobufTimeUtilsTest.java
Fixes https://github.com/temporalio/sdk-java/issues/1938 aka SDK-1319.
Eliminate risk of ArithmeticException due to `long` overflow in `toJavaDuration`.
Make the API exception-safe for extreme duration values, especially for values which are legal in the protobuf wire format but not for Java's `Duration` type.
1. Closes [GitHub Issue #1938](https://github.com/temporalio/sdk-java/issues/1938).
2. How was this tested: created new tests in temporal-sdk module that captured existing behavior with small values to prove that the visible behavior was unchanged for already-legal values.
> Fix ArithmeticException in toJavaDuration.

- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Removed hardcoded 10-second timeout for TestActivityEnvironment.
We want to support unit testing activities that take longer than 10 seconds.
Reported at https://community.temporal.io/t/activities-run-in-tests-using-testactivityenvironment-intermittently-fails-with-java-util-concurrent-timeoutexception/10397/3
> Removed heardcoded 10 second timeout for an activity under test

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-sdk/src/test/java/io/temporal/worker/BuildIdVersioningTest.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Add the BuildID of the current workflow task to info.
Useful
1. Part of https://github.com/temporalio/features/issues/253
Added IT
> Add build id to workflow info

- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateLongPollTest.java
Unwrap ExecutionException on sync update. We shouldn't return the `ExecutionException` to caller since they aren't expecting an ExecutionException on a sync update.
closes https://github.com/temporalio/sdk-java/issues/1973
> Unwrap ExecutionException on sync update

- temporal-spring-boot-autoconfigure-alpha/README.md
Clarify local connection option behaviour. If users want to specify connection options and not use the local service stubs default they can always specify target as "localhost:7233" and set all the options they want themselves
closes https://github.com/temporalio/sdk-java/issues/1815
> Clarify local connection option

- temporal-sdk/src/main/java/io/temporal/internal/sync/PotentialDeadlockException.java
- temporal-sdk/src/main/java/io/temporal/worker/NonDeterministicException.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/VersionStateMachineTest.java
Add a couple of https://github.com/temporalio/rules references as error prefixes
> Prefix some errors with rule identifiers

- temporal-sdk/src/main/java/io/temporal/internal/sync/DynamicSyncWorkflowDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/test/java/io/temporal/functional/serialization/WorkflowIdSignedPayloadsTest.java
Apply serialization context to Dynamic Workflows
Serialization context should be applied inside a workflow even if it is dynamic 
1. Closes https://github.com/temporalio/sdk-java/issues/1982
Added new integration test to cover dynamic workflow and activity
No
> Apply serialization context to Dynamic Workflows

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
Update to WorkersTemplate to expose registered workflow and activity class info per task queue. 
Allows users to build custom actuator endpoints that display this.
Sample that uses this info to create a custom actuator endpoint https://github.com/temporalio/samples-java/pull/576
> SpringBoot - Add registered workflow and activity impl info to workers template

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/RpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubLongPollRpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubServiceOperationRpcRetryOptions.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcSyncRetryerTest.java
* Update default initial interval for non-poll retries to 100ms (from 50ms)
* Update default maximum interval for non-poll retries to 5s (was 6s)
* Update default backoff factor for non-poll retries to 1.7 (was 2.0)
* Update default jitter factor for non-poll retries to 20% (was 10%)
* Update default initial interval for poll retries to 200ms (was 50ms)
* Update default maximum interval for poll retries to 10s (was 60s)
* Update default backoff factor for poll retries to 2.0 (was 1.2)
* Update default jitter factor for poll retries to 20% (was 10%)
* Code cleanups in argument validation code
* Default maximum interval is now computed from initial interval as documented (was hardcoded at 6s)
These changes bring the Java SDK's RPC retry options in line with those of the Core SDK, as the …
> Update Java SDK retry options for poll operations to match Core SDK.

- temporal-spring-boot-autoconfigure-alpha/README.md
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/properties/ConnectionProperties.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/MTLSWithServerNameOverrideTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/resources/application.yml
adds server-name to mtls config. allows to override authority on ChannelInitializer when using mtls
closes https://github.com/temporalio/sdk-java/issues/1996
> SpringBoot - add server-name to mtls config options

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/UnknownHistoryEventReplayerTest.java
- temporal-sdk/src/test/resources/testUnknownHistoryEventClean.json
- temporal-sdk/src/test/resources/testUnknownHistoryEventMayIgnore.json
- temporal-sdk/src/test/resources/testUnknownHistoryEventMayNotIgnore.json
* Unknown event types with `worker_may_ignore: true` are skipped
* All other unknown event types continue to throw
* Added new replay tests verifying that `worker_may_ignore` is handled correctly
The new `worker_may_ignore` flag is intended to mark events that can be handled as no-ops if the SDK doesn't know the event type.
1. Closes https://github.com/temporalio/sdk-java/issues/1945
2. How was this tested: added new unit tests to verify the new behavior before implementing it.
> Ignore history events with worker_may_ignore: true.

- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
Remove experimental flag from StartDelay
Remove experimental flag from StartDelay
To indicate the current state of StartDelay workflow option
> Remove experimental flag from StartDelay

- temporal-sdk/src/main/java/io/temporal/internal/worker/ShutdownManager.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SingleWorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/StickyQueueBalancer.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/StickyWorkflowDrainShutdownTest.java
Add an option to drain sticky task queue during graceful shutdown. Worker will stop polling on the normal task queue and only poll on the stick task queue to complete workflows while the worker is shutting down.
There is a lot  of follow up work we could do around here based on user demand and if the server adds some APIs. For know this is the minimal implementation  to avoid sticky workflow timeout for short workflow during graceful shutdown.
> Add StickyTaskQueueDrainTimeout

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/test/java/io/temporal/functional/serialization/WorkflowIdSignedPayloadsTest.java
Make sure task failures use a serialization context. User reported some places we serialized exceptions did not have a workflow context associated with them. This PR should hopefully address all these places.
> Make sure task failures use a serialization context

- temporal-sdk/src/main/java/io/temporal/internal/worker/StickyQueueBalancer.java
Make StickyQueueBalancer synchronized to avoid potential race where all initial calls to `makePoll()` all get assigned the same task queue.
> Make StickyQueueBalancer synchronized

- temporal-serviceclient/build.gradle
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/SystemInfoInterceptor.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/ChannelManagerTest.java
* Ensure that `ChannelManager.getServerCapabilities` follows the standard gRPC retry policy, even though it is called by `GrpcRetryer`.
In the course of writing new gRPC retry tests for the [features](https://temporalio/features) repo, it was discovered that any gRPC failures returned by the server in response to `WorkflowService.getSystemInfo` will cause an uncaught `io.grpc.StatusRuntimeException` that happens before the actual gRPC retry code gets the chance to run.
1. Closes internal JIRA issue SDK-1888.  (Sorry, I should have opened it as a GitHub issue and let it sync to JIRA instead, I didn't learn this until after the fact.)
2. How was this tested: using the new features repo tests in https://github.com/temporalio/features/pull/435 .
> Fix exception in GrpcRetryer.

- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleClientImpl.java
- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleClientOptions.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/ScheduleClientInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/ScheduleClientInterceptorBase.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/TracingScheduleInterceptor.java
This adds APIs for users to specify interceptors when creating a `ScheduleClient`. Previously there was interceptor infrastructure built into the internals of the client, but no public API to allow users to actually add them.
So that users can add interceptors as needed.
1. Closes #2048 
Unit tests
Not sure. The current docs don't talk about how `ScheduleClient` is created right now, so probably not?
> Add ScheduleClientInterceptor APIs (fixes #2048)

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WFTBuffer.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/TestHistoryBuilder.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/UpdateProtocolStateMachineTest.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
Add support for update admitted event. Required some modification to how the Java SDK batches event during replay because when the SDK processed an update admitted event while replaying it needs to know if it was accepted or not. Preciously the SDK batches events like [WFT started, WFT completed, Command events] and now it batches events like [Non command events, WFT scheduled, WFT started, WFT completed, Command events]
.
> Add support for update admitted event

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/UpdateProtocolStateMachineTest.java
Saw a feature test failure 
https://github.com/temporalio/sdk-java/actions/runs/9004033452/job/24736072159
```
15:03:44.177 [Workflow Executor taskQueue="features-update/worker_restart-53dad4af-01db-498a-85ac-53a6c668cb0e", namespace="features-ns-c0890b76-c01f-43dd-8085-0d5e86de9891": 1] WARN  i.t.i.r.ReplayWorkflowTaskHandler - Workflow task processing failure. startedEventId=12, WorkflowId=5a643741-9333-44cf-abd5-62703fc9ed51, RunId=12fc431a-f015-47f1-8cbe-525fa758ace1. If seen continuously the workflow might be stuck.
java.lang.UnsupportedOperationException: null
at java.base/java.util.Collections$UnmodifiableCollection.add(Collections.java:1060)
at io.temporal.internal.statemachines.WorkflowStateMachines.handleSingleEventLookahead(WorkflowStateMachines.java:360)
at …
```
> Fix UnsupportedOperationException in handleSingleEventLookahead

- temporal-sdk/src/main/java/io/temporal/internal/client/ScheduleProtoUtil.java
If the catchupWindow property is not set in SchedulePolicy, it is sent as a zero duration in the appropriate protobuf message. However, the server expects an unset value here. The previous behavior led to setting the actual catchupWindow on the server to the minimal value (10 seconds) instead of the default (1 year).
Schedules are created with wrong `catchupWindow`. That leads to missed runs
1. Closes  #2065
Tested in existing `ScheduleTest`
Nope
> Send unset catchupWindow in schedules if not specified

- .github/workflows/features.yml
- temporal-sdk/src/main/java/io/temporal/client/LazyUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/client/UpdateOptions.java
- temporal-sdk/src/main/java/io/temporal/client/UpdateWaitPolicy.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStub.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowUpdateStage.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
* Add admitted stage to wait policy
* Don't return update handle from startUpdate until the update is complete if the user specified that stage (not sure why they would, though, when using start)
* Retry submitting update to server until seen accepted
See https://github.com/temporalio/features/issues/432
1. Closes https://github.com/temporalio/sdk-java/issues/2002
Existing / new tests
> Don't return update handles until desired stage reached

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/UpdateProtocolStateMachine.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/UpdateProtocolStateMachineTest.java
Send original update request back in accept/reject response
close https://github.com/temporalio/sdk-java/issues/2073
> Send original update request back in accept/reject response

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
closes https://github.com/temporalio/sdk-java/issues/1997
Add shortcut to add an api key to a connection. Instead of 
```
WorkflowServiceStubsOptions.Builder stubOptions =
WorkflowServiceStubsOptions.newBuilder()
...
.addGrpcMetadataProvider(
new AuthorizationGrpcMetadataProvider(() -> "Bearer " + API_KEY))
```
Users can now set
```
WorkflowServiceStubsOptions.Builder stubOptions =
WorkflowServiceStubsOptions.newBuilder()
...
.addApiKey(
() -> API_KEY)
```
> Add shortcut to set API key

- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
Provides the ability to override worker identity specified in a WorkflowClient
1. Closes #2078 
2. How was this tested: manual tests
3. Any docs updates needed? 
It would be great to have a docs section about identities in the sdk docs, but there is no such yet
> Add identity to WorkerOptions

- temporal-sdk/src/main/java/io/temporal/internal/client/ScheduleProtoUtil.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
Fix schedule workflow action retry policy. Originally it was not being properly propagated from the action to the workflow options.
> Fix schedule workflow action retry policy

- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
Fix a few issues with the test:
* Was using `assertEquals` backwards
* Was not comparing before and after setting properly
> Fix a few issues with the describeSchedules test

- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalContinueAsNewNonDeterminism.java
Fix race in `testSignalContinueAsNewNonDeterminism` where the workflow may have not processed a signal before we started attempting to introduce non determinism.
> Fix signal CAN non determinism test

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WFTBuffer.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/DirectQueryReplaysDontSpamLogWithWorkflowExecutionExceptionsTest.java
Fix issue with isReplaying causing direct query to spam logs. When we are grouping events there is an edge case where the last event is also ending a workflow task.
closes https://github.com/temporalio/sdk-java/issues/2076
> Fix issue with isReplaying causing direct query to spam logs

- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/client/ScheduleProtoUtil.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientRequestFactory.java
- temporal-sdk/src/test/java/io/temporal/client/functional/WorkflowIdConflictPolicyTest.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleWithTypedSearchAttributesTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateContinueAsNewWFTFailure.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Add setWorkflowIdConflictPolicy
closes https://github.com/temporalio/sdk-java/issues/2033
> Add setWorkflowIdConflictPolicy

- temporal-sdk/src/main/java/io/temporal/client/UpdateOptions.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStub.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTestTimeout.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTestContinueAsNew.java
- temporal-testing/src/main/java/io/temporal/testing/TimeLockingInterceptor.java
Require `WaitForStage` in `StartUpdate`
closes https://github.com/temporalio/sdk-java/issues/2045
> Require WaitForStage in StartUpdate

- .github/workflows/prepare-release.yml
- Reverted some GHA actions back to their Node 16 based equivalent.
- The `build_native_images` job, part of the production release workflow, executes on a ubuntu-1804 runner to provide compatibility with older glibc systems (ubuntu-1804 uses glibc 2.27). However, Node 20, which is used by most recent GHA actions, require at least glibc 2.28, and therefore, can't run on Ubuntu 18.04 runners.
> Bump some GHA actions back due to glibc compatibility

- temporal-sdk/src/main/java/io/temporal/client/LazyUpdateHandleImpl.java
Fix caching in `LazyUpdateHandleImpl`. `setFromWaitCompleted` was not being used.
Note: Very likely I will refactor all these handlers as part of https://github.com/temporalio/sdk-java/issues/2094
> Fix caching in LazyUpdateHandleImpl

- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowWorkerTest.java
Didn't see any flakyness during the PR or when locally testing but this test started immediately failing in CI after being merged https://github.com/temporalio/sdk-java/actions/runs/9452261550/job/26035046059. I suspect the graceful worker shutdown is interacting weirdly with the mocks.
> Fix flake in resetWorkflowIdFromWorkflowTaskTest

- temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
Add integration test for reset with update now that the server supports it.
> Add integration test for reset with update

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerTaskHandlerTests.java
Fix `ConcurrentModificationException` in `LocalActivityMeteringHelper`. `newWFTStarting` was calling `remove` on `firstWftActivities ` in a for loop iterating over `firstWftActivities` which is not allowed.
closes https://github.com/temporalio/sdk-java/issues/2107
> Fix ConcurrentModificationException in LocalActivityMeteringHelper

- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/ContinueAsNewTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/common/TestWorkflows.java
Nothing, just added a test. Test can't repro the real problem, which is that only over real gRPC transport does this problem show up when the messages are set but contain empty strings. That is manually confirmed fixed.
1. Closes https://github.com/temporalio/sdk-java/issues/1424
It is a test bruh
> Add test verifying no-tq CaN command works

- build.gradle
- temporal-remote-data-encoder/build.gradle
- temporal-sdk/build.gradle
- temporal-testing/build.gradle
Update dependencies to address some CVE scans. Just upgrading dependencies with CVE issues, none directly effecting the Java SDK, but some tools will still warn just for having it as a dependency in some way. I plan to do a more through sweep of all dependencies when I add virtual thread support to the Java SDK.
> Update dependencies to address some CVE scans

- .github/workflows/prepare-release.yml
Change build_native_images mac runner to macos-13. `macos-latest` now points to `aarch64`. Funny enough this doesn't cause an error since out `graal` plugin we use only checks for `64` so still downloads the `x86_64` toolchain.
> Change build_native_images mac runner to macos-13

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowFailedMetricsTests.java
Make sure `workflow_failed` is incremented on `NonDeterministicException`
closes https://github.com/temporalio/sdk-java/issues/2103
> Make sure workflow_failed is incremented on NonDeterministicException

- .github/workflows/ci.yml
- .gitmodules
- temporal-sdk/src/main/java/io/temporal/client/CloudOperationsClient.java
- temporal-sdk/src/main/java/io/temporal/client/CloudOperationsClientImpl.java
- temporal-sdk/src/test/java/io/temporal/client/CloudOperationsClientTest.java
- temporal-serviceclient/build.gradle
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/CloudServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/CloudServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/CloudServiceStubsOptions.java
* Added api-cloud protos as new submodule and included in proto gen
* Added `io.temporal.serviceclient.CloudServiceStubs` and impl and options
* Added `io.temporal.client.CloudOperationsClient` as (currently) just a simple client that returns the raw service for use
* Added CI test
1. Closes #2059
> Experimental cloud operations client

- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerOptionsTest.java
Fixes a bug where the `identity` property was not being copied to the worker options `Builder` when it is created from an existing `WorkerOptions` instance.
Could not properly set the identity of the worker when using the `WorkerOptions`, instead the identity falls back to the one from the workflow client options.
1. N/A
2. Tested via unit test.
3. N/A
> Ensure identity copied to Builder from source WorkerOptions

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowUpdateTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/common/TestWorkflows.java
Align test server update APIs with real server update APIs. Key part is all the tests in temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowUpdateTest.java to ensure the test server and real server behave the same. Some tests may be disabled as I found bugs in the real server while writing these tests.
> Align Update API across test server and real server

- .github/workflows/features.yml
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/client/CompletedUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/LazyUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
Moved update polling to be inside of the interceptor a-la other SDKs
Consistent, allows interceptor to change things post-polling
1. Closes https://github.com/temporalio/sdk-java/issues/2094
Added an integ test using the interceptor
> Move workflow update polling inside of interceptor

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowLockImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowSemaphoreImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowLock.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowSemaphore.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalLockTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/WorkflowInternalSemaphoreTest.java
Add Workflow-friendly concurrency primitives. This PR adds a workflow safe `Mutex` and `Semaphore` based on the Java interfaces
* https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/Lock.html
* https://docs.oracle.com/javase%2F8%2Fdocs%2Fapi%2F%2F/java/util/concurrent/Semaphore.html
> Workflow-friendly concurrency primitives

- temporal-sdk/src/test/java/io/temporal/activity/ActivityNextRetryDelayTest.java
Enable next retry delay test for Server since the Server now supports next retry delay.
> Enable next retry delay test for server

- temporal-sdk/src/main/java/io/temporal/client/WorkflowUpdateTimeoutOrCancelledException.java
- temporal-sdk/src/main/java/io/temporal/internal/client/LazyUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTestTimeout.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateExceptionWrapped.java
Wrap GRPC::CANCELED and DEADLINE_EXCEEDED in new exception type `WorkflowUpdateTimeoutOrCancelledException`
closes https://github.com/temporalio/sdk-java/issues/2069
> Wrap GRPC::CANCELED and DEADLINE_EXCEEDED in new exception type

- temporal-serviceclient/build.gradle
Filter out third party protos
closes https://github.com/temporalio/sdk-java/issues/2150
> Filter out third party protos

- temporal-test-server/src/main/java/io/temporal/internal/testservice/CommandVerifier.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/NexusTaskToken.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/RequestContext.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestNexusEndpointStore.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestNexusEndpointStoreImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestServicesStarter.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableState.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStore.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusEndpointTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusWorkflowTest.java
Added test server support for Nexus operation commands, including sync completion, timeouts, failures, and retries. Added most of the stubs for implementing asynchronous operations in followup PRs.
The test server will only support worker targets, not external, so there is no added logic for making HTTP requests.
The implementation largely follows the same design as ActivityTasks.
> Implement test server support for sync Nexus operation commands

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- gradle/java.gradle
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
Java SDK test time was approaching 25 min, talked with Josh and we decided to try using larger runners to cut down on the test time for now.
> Improve test time and flaky schedule test

- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowWorkerTest.java
Hopefully make concurrentPollRequestLockTest less flakey.
address flakes like this https://github.com/temporalio/sdk-java/actions/runs/10409742551/job/28830050716
> Concurrent poll request lock test fix

- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivitySlotSupplierQueue.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/test/java/io/temporal/worker/LocalActivityWorkerNoneRegisteredNotStartedTest.java
- temporal-sdk/src/test/java/io/temporal/worker/LocalActivityWorkerNotStartedTest.java
Fixed a possible hang when shutting down a never-started worker, as well as normalized the shutdown of this slot queue to look more like other things.
Bugfix
1. Closes https://github.com/temporalio/sdk-java/issues/2194
Added tests, and there are a number of existing tests covering shutdown with running LAs
> Fix shutdown behavior of unstarted LA slot queue

- temporal-sdk/src/main/java/io/temporal/internal/logging/LoggerTag.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
Added a new LoggerTag for the Attempt number for LocalActivityWorker, ActivityWorker and WorkflowWorker.
When diagnosing logs it's quite useful to have this value, specially when executions may overlap each other.
1. Closes https://github.com/temporalio/sdk-java/issues/2192
Run tests locally, change is quite simple, I didn't do further testing.
I didn't find it required. Am I missing something?
> Adding attempt number into MDC context for better diagnosing

- .github/workflows/features.yml
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStub.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowUpdateHandle.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/client/CompletedWorkflowUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/LazyWorkflowUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTestTimeout.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateAllHandlersFinished.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateInfoTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
- temporal-testing/src/main/java/io/temporal/testing/TimeLockingInterceptor.java
Renamed `UpdateHandle` to `WorkflowUpdateHandle`.
This is a breaking change.
⚠️ Feature tests are failing; I can update them as a fast follow-up.
Consistency. (as discussed previously)
**How was this tested:**
Existing tests.
**Any docs updates needed?**
I checked https://docs.temporal.io/develop/java/message-passing and the `UpdateHandle` type isn't mentioned anywhere.
I also cannot see it in the samples repo ([search](https://github.com/search?q=repo%3Atemporalio%2Fsamples-java%20UpdateHandle&type=code))
The release docs will need to mention this change, though.
> Rename UpdateHandle to WorkflowUpdateHandle (💥 - incompatible change)

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/BasicWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowMutableState.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowPropertiesModifiedStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/workflow/upsertMemoTests/UpsertMemoTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateUtils.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/internal/TracingWorkerInterceptor.java
Add support for upsert memo to the Java SDK and test server.
closes https://github.com/temporalio/sdk-java/issues/623
> Add support for upsert memo

- temporal-sdk/src/main/java/io/temporal/workflow/DynamicUpdateHandler.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/DynamicUpdateTest.java
Fix Dynamic Update Handler return type to be consistent with all other `Dynamic*Handler`. The workflow code also expected Dynamic Update Handler to return an Object so no workflow side code changed.
> Fix Dynamic Update Handler return type

- temporal-test-server/src/main/java/io/temporal/internal/testservice/NexusOperationRef.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/NexusTaskToken.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableState.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStore.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusWorkflowTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/common/TestWorkflows.java
Added test server support for async Nexus operations
Refactored cancellation logic
Revised timeout / error handling
New functional tests
See also first implementation PR: https://github.com/temporalio/sdk-java/pull/2176
> Test server support for async Nexus operations

- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/ScheduleProtoUtil.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientRequestFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ChildWorkflowStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/StartChildWorkflowExecutionParameters.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/TimerStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/ChildWorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/TimerOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/OutdatedDirectQueryReplayWorkflowRunTaskHandlerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/LocalActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/MutableSideEffectStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/TimerStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/UpdateProtocolStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/VersionStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowMetadataTest.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/internal/TracingWorkerInterceptor.java
Add support for user metadata on workflows and timer events. Other events can be added in the future, just picked these events to match the Go SDK.
Note: This does NOT cover `__temporal_workflow_metadata`, that feature is tracked [here](https://github.com/temporalio/sdk-java/issues/2217) 
closes https://github.com/temporalio/sdk-java/issues/2216
> Add support for user meta data 

- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowImplMetadata.java
- temporal-sdk/src/main/java/io/temporal/internal/common/env/ReflectionUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DynamicSyncWorkflowDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowExecutionHandler.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInit.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInterface.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/POJOWorkflowImplMetadataTest.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/POJOWorkflowInterfaceMetadataTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/DynamicWorkflowInitTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowInitConstructorTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowInitRetryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowInitTest.java
Add workflow init support to allow users to run code before signal/update handlers:
* If the workflow implementation defines a no-arg constructor that is used to maintain backwards compatibility
* SDK checks if the workflow implementation defines a constructor annotated with `@WorkflowInit`
* SDK validates at registration time the constructor meets all requirments.
* If a constructor is  annotated with `@WorkflowInit` we treat exceptions thrown by as if they are thrown from the main workflow method
closes https://github.com/temporalio/sdk-java/issues/865
> Add workflow init support 

- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
Changed test server logic to not immediately record a failure if the next attempt schedule time would exceed an operation's schedule to close timeout.
Closes https://github.com/temporalio/sdk-java/issues/2215
> Test Server: Fix Nexus operation timeout during retry

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/internal/TracingWorkerInterceptor.java
Add `getMetricsScope` interceptor in `WorkflowOutboundCallsInterceptor`
closes https://github.com/temporalio/sdk-java/issues/2208
> Add getMetricsScope interceptor

- releases/v1.25.2
> Release v1.25.2

- temporal-sdk/src/main/java/io/temporal/worker/WorkflowImplementationOptions.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowSlotTests.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanNexusWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationCancelledTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationFailTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationStubTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationTimeoutTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/UntypedSyncOperationStubTest.java
- temporal-testing/build.gradle
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironment.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowExtension.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowRule.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
- temporal-testing/src/main/java/io/temporal/testing/internal/TestServiceUtils.java
- temporal-testing/src/test/java/io/temporal/testing/junit5/TestWorkflowExtensionTest.java
Add Nexus support to TestWorkflowExtension. This PR also adds support to automatically create a Nexus Endpoint in the `TestWorkflowExtension` to make testing easier.
closes: https://github.com/temporalio/sdk-java/issues/2235
> Add Nexus support to TestWorkflowExtension

- temporal-sdk/src/main/java/io/temporal/client/WorkflowException.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/OperationFailureConversionTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
Translate some well know errors like what we did with the Go SDK. This does not cover all possible SDK exception, just some we except users to throw in this initial release.
closes https://github.com/temporalio/sdk-java/issues/2209
> Nexus: Well know error translation

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusWorkflowTest.java
Making sure canceled failures have the correct cause for Nexus operations in the test server
> Test Server: Set CanceledFailureInfo for all canceled Nexus outcomes

- temporal-sdk/src/test/java/io/temporal/workflow/nexus/CancelAsyncOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncClientOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleFuncTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleProcTest.java
Add test coverage for cancelling an async operation. I also moved a few tests off of `BaseNexusTest`, hope to move all tests off but there is some challenges around replay.
> Add cancel async operation tests

- temporal-sdk/src/main/java/io/temporal/failure/DefaultFailureConverter.java
- temporal-sdk/src/main/java/io/temporal/failure/NexusOperationFailure.java
Include failure message in Nexus exception. This should line up better with how the Go SDK deserializes Nexus failures
> Include failure message in Nexus exception

- temporal-sdk/src/main/java/io/temporal/payload/context/SerializationContext.java
Add note on SerializationContext for Nexus. In my splitting up my Nexus work I lost this note on how `SerializationContext` are not supported for Nexus operations.
> Add note on SerializationContext for Nexus

- temporal-sdk/src/main/java/io/temporal/internal/logging/LoggerTag.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/test/java/io/temporal/workflow/LoggerTest.java
Add update info to MDC context
closes: https://github.com/temporalio/sdk-java/issues/2237
> Add update info to MDC context

- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
Resolving [this](https://github.com/temporalio/sdk-java/pull/2214#discussion_r1771361853) comment on the original Nexus worker PR. Also adding some more logging if a Nexus tasks failed, based on how the Java SDK logs activity failures.
> Improve nexus operation failure handling

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ActivityStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/EntityStateMachineInitialCommand.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
Fix memory leak of command inputs. Before this change the Java SDK was holding onto the input of various operations (activities, local activities, child workflow) after the operation had already started for two reasons: 
* The state machine was holding a strong reference to the command even after it had been sent to the server
* The output handle needed some of the type informations from the input, but that kept a reference to the input parameters as well
This could cause an OOM error if a lot of async operations were started in a specific workflow.
There is another memory leak in the SDK where the JVM cannot garbage collect complete state machines because they are being held by the cancellation callback in the CancellationScope. This PR does not address this issue because it is …
> Fix memory leak of command inputs

- temporal-kotlin/build.gradle
- temporal-sdk/build.gradle
- temporal-shaded/build.gradle
- temporal-spring-boot-autoconfigure/build.gradle
- temporal-test-server/build.gradle
- temporal-testing/build.gradle
mark the Nexus SDK as an `API` dep. instead of `implementation` since the SDK takes and returns types from the Nexus SDK
> mark the nexus sdk as an api dep.

- temporal-sdk/src/test/java/io/temporal/workflow/nexus/OperationFailureConversionTest.java
Avoid spamming retries in nexusOperationApplicationFailureFailureConversion when using the time skipping test server.
> Avoid spamming retries in nexusOperationApplicationFailureFailureConversion

- gradle/jacoco.gradle
Fix code coverage build. Some tests can't run under code coverage due to internal proxies breaking out expectations.
> Fix code coverage build

- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
Avoid warning from un-accessed operation promise. Currently the SDK will log a warning if the nexus operations promise is not accessed in some cases, even if the result promise is accessed. This PR will prevent the warning. We have similar logic for the child workflow execution promise.
> Avoid warning from un-accessed operation promise

- temporal-sdk/src/test/java/io/temporal/workflow/nexus/AsyncWorkflowOperationTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Fix test server operation timeout. Previously the test server was inconsistent with the real server an treated a zero timeout as immediate where the real server treats it as infinite.
> Fix test server operation timeout

- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationTimeoutTest.java
Avoid SyncOperationTimeoutTest spamming the test server
> Avoid SyncOperationTimeoutTest spamming the test server

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/nexus/PayloadSerializer.java
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowRunOperation.java
- temporal-sdk/src/test/java/io/temporal/internal/nexus/PayloadSerializerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/GenericListOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/ProtoOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/VoidOperationTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Fix proto decoding in a Nexus Operation. `type.getClass()` returns the class of `Type` not the class of the operation handler input as intended.
> Fix proto decoding in a Nexus Operation

- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NexusWorker.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/OperationFailMetricTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncClientOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationFailTest.java
Add failure_reason to nexus_task_execution_failed based on the Go SDK PR https://github.com/temporalio/sdk-go/pull/1671
closes https://github.com/temporalio/sdk-java/issues/2273
> Add failure_reason to nexus_task_execution_failed

- .github/workflows/ci.yml
- temporal-sdk/build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/task/ThreadConfigurator.java
- temporal-sdk/src/main/java/io/temporal/internal/task/VirtualThreadDelegate.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NexusWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollTaskExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollerOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SingleWorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/ActiveThreadReportingExecutor.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactoryOptions.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/main/java21/io/temporal/internal/task/VirtualThreadDelegate.java
- temporal-sdk/src/virtualThreadTests/java/io/temporal/worker/WorkerWithVirtualThreadsStressTests.java
- temporal-shaded/build.gradle
- temporal-spring-boot-autoconfigure/README.md
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/ConnectionProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/NamespaceProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerFactoryOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java
- temporal-testing/src/main/java/io/temporal/testing/internal/ExternalServiceTestConfigurator.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestWorkflowRule.java
Add support for virtual workflow threads
Closes https://github.com/temporalio/sdk-java/issues/1448
> Add support for virtual workflow threads

- temporal-sdk/src/main/java/io/temporal/activity/ActivityOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ActivityStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ExecuteActivityParameters.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/ActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityMetadataTest.java
Add activity summary
closes https://github.com/temporalio/sdk-java/issues/2268
> Add activity summary

- temporal-sdk/src/main/java/io/temporal/activity/LocalActivityOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ExecuteLocalActivityParameters.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/LocalActivityStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/OutdatedDirectQueryReplayWorkflowRunTaskHandlerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerTaskHandlerTests.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/LocalActivityStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityMetadataTest.java
Add support for local activity metadata, basically the same as https://github.com/temporalio/sdk-java/commit/c8a27ce9073164141fc1f08ac4c80456f48b3c1d but for local activities.
> Add support for local activity metadata

- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/AsyncWorkflowOperationTest.java
- temporal-sdk/src/test/resources/testAsyncWorkflowOperationTestHistory.json
Make sure workflow options from proxy call are propagated
> [Nexus] Make sure workflow options from proxy call are propagated

- temporal-sdk/src/test/java/io/temporal/worker/ResourceBasedTunerTests.java
Increase timeout of canRunWithResourceBasedTuner to try to fix flakes like seen here https://github.com/temporalio/sdk-java/actions/runs/11802877846/job/32883424690
> Increase timeout of canRunWithResourceBasedTuner

- temporal-sdk/src/main/java/io/temporal/internal/common/env/ReflectionUtils.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/POJOWorkflowImplMetadataTest.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/POJOWorkflowInterfaceMetadataTest.java
Validate with generic parameter types for workflow init
> Validate with generic parameter types for workflow init

- releases/v1.26.2
> Release v1.26.2

- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInvocationHandlerBase.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ChildWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ExternalWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/LocalActivityInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/NexusServiceInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/NexusServiceStubImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusServiceStub.java
Support `toString` on workflow proxy types.
closes https://github.com/temporalio/sdk-java/issues/1536
> Support toString on workflow proxy types

- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowInterfaceMetadata.java
- temporal-sdk/src/test/java/io/temporal/common/metadata/POJOWorkflowInterfaceMetadataTest.java
Do runtime check to ensure update validator has the same parameters as the update it validates.
closes https://github.com/temporalio/sdk-java/issues/2317
> Do runtime check to ensure update validator has the same parameters as the update it validates

- temporal-sdk/src/main/java/io/temporal/client/WorkflowUpdateHandle.java
- temporal-sdk/src/main/java/io/temporal/internal/client/CompletedWorkflowUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/LazyWorkflowUpdateHandleImpl.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/UpdateTestTimeout.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
Add `getResult` helper to `WorkflowUpdateHandle`
closes https://github.com/temporalio/sdk-java/issues/2212
> Add getResult to WorkflowUpdateHandle

- temporal-sdk/src/main/java/io/temporal/client/WorkflowExecutionDescription.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStub.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowDescribe.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-testing/src/main/java/io/temporal/testing/TimeLockingInterceptor.java
closes https://github.com/temporalio/sdk-java/issues/2265
> Add high-level workflow describe

- temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowClientInternalImpl.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowInvocationHandler.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestMultiArgWorkflowUpdateFunctions.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/TypedUpdateTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
Add type safe API to execute an async update workflow request.
Open questions we should resolve:
1. Is the name `executeUpdate` acceptable? We could also use `update` or `startUpdate` the Java SDK is not very consistent here
2. Is taking `UpdateOptions` OK or do we want a new type here? Reusing is nice since it reduces the number of types, but has some redundant fields like `name`, and type.
closes https://github.com/temporalio/sdk-java/issues/2181
> Add type safe API to execute an async update workflow request

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-snapshot.yml
- docker/native-image/dockerfile
Build the test server in an ubuntu 18 container
> Fix CI after GHA's drop of node16 actions

- temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowCachingTest.java
Skip taskTimeoutWillRescheduleTheTaskOnTheGlobalList because it is flaky. This test has been flaky for a long time (at least a year). I opened an issue to investigate, but for now we should skip it since it just makes doing releases slower.
> Skip flaky test

- temporal-sdk/src/main/java/io/temporal/client/WorkflowStub.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowUpdateHandle.java
- temporal-sdk/src/main/java/io/temporal/internal/client/CompletedWorkflowUpdateHandleImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/DynamicUpdateTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateInfoTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateWithStartTest.java
While reviewing update with start I noticed that the Java SDK was handling update failures a bit different then other SDKs. Other SDKs always return an update rejection or failure through the update handle. The Java SDK may have returned the update failure (as an exception) on `startUpdate` or `getResult` depending on the exact timing and `waitStage` the user selected. After this PR the Java SDK will always return the update failure by getting the result from the handle.
> Standardized update failure exception

- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
Make nexus header check case-insensitive. Nexus headers should be case insensitive so we use the map from the context that is case insensitive.
> Make nexus header check case-insensitive

- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationTimeoutTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Fix unbalanced locks in test server for Nexus. The issue was the attempt of the task was always using the current attempt not the attempt when the timer was creates as intended. 
```
08:43:47.767 [Timer task] ERROR i.t.i.t.SelfAdvancingTimerImpl - Failed to unlock the timer
java.lang.IllegalStateException: Unbalanced lock and unlock calls: 
Self Advancing Timer Lock Events:
2024-12-03 08:43:47.273	L	  1	TestService constructor
2024-12-03 08:43:47.629	L	    2	scheduleWorkflowTask
2024-12-03 08:43:47.642	L	      3	scheduleWorkflowTask
2024-12-03 08:43:47.645	U	    2	External Caller
2024-12-03 08:43:47.704	U	  1	completeWorkflowTask
2024-12-03 08:43:47.725	L	    2	processScheduleNexusOperation
2024-12-03 08:43:47.725	U	  1	completeWorkflowTask
2024-12-03 08:43:47.755	U	0	failNexusOperation …
```
> Fix unbalanced locks in test server for Nexus

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
Make headers in ExecuteNexusOperationInput case insensitive, this will align with other Nexus headers that are all case insensitive.
> Make headers in ExecuteNexusOperationInput case insensitive

- build.gradle
- releases/v1.27.0
- temporal-opentracing/src/main/java/io/temporal/opentracing/OpenTracingWorkerInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/SpanOperationType.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ActionTypeAndNameSpanBuilderProvider.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/ContextAccessor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingNexusOperationInboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/SpanFactory.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/NexusOperationTest.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/integration/JaegerTest.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/NexusOperationInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/NexusOperationInboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/NexusOperationOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/NexusOperationOutboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkerInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkerInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusOperationContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusServiceInterceptorConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/RootNexusOperationInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/RootNexusOperationOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/TemporalInterceptorMiddleware.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncNexusWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/nexus/NexusTaskHandlerImplTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/CancelAsyncOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncClientOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationFailTest.java
- temporal-testing/src/main/java/io/temporal/testing/internal/TracingWorkerInterceptor.java
Add Nexus Worker interceptor based on the Nexus Java SDK interceptors proposed here https://github.com/nexus-rpc/sdk-java/pull/14
> Add Nexus Worker interceptor

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
Set request Id on SignalWorkflowExecutionRequest
closes https://github.com/temporalio/sdk-java/issues/1655
> Set request Id on SignalWorkflowExecutionRequest

- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityTaskExecutors.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityTaskHandlerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContext.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/InternalActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextImpl.java
- temporal-sdk/src/test/java/io/temporal/activity/ActivityHeartbeatSentOnFailureTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
When an activity is heart-beating to record progress, heartbeats may be throttled to reduce load, if an activity fails with throttled heartbeats then those throttled heartbeats would not reach the server causing progress to be lost. This can be avoided if the SDK sets LastHeartbeatDetails on activity failure. Then the latest value won't be lost on failure even if it was being throttled.
closes https://github.com/temporalio/sdk-java/issues/1965
> Set LastHeartbeatDetails on activity failure

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableState.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusWorkflowTest.java
Added support to the test server for completing Nexus operations before the start response is received.
> Test server support for Nexus operation complete before start

- temporal-sdk/src/main/java/io/temporal/activity/ActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/ActivityExecutionContextBase.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SyncWorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityClientTest.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Add method to get workflow client from an activity.
closes https://github.com/temporalio/sdk-java/issues/2362
> Add method to get workflow client from an activity

- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-opentracing/src/test/java/io/temporal/opentracing/CallbackContextTest.java
This change allows the OpenTracing interceptor to transfer any active trace/span from
the point of invocation to the point of promise callback execution, thus preserving
the span within the callback.
Without this, spans become disjoint across Promise.thenCompose, due
to the nature of the deferring the execution of the .thenCompose to a callback thread.
Fixes #1962
1. Closes #1962
A unit test was developed first to confirm the issue.  The solution was iterated over until the unit test passed satisfactorily.  The unit-test is included in the MR for inclusion with the code-base
No.
> [#1962] Wrap returned promises in OpenTracingOutboundCallsInterceptor

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivitySlotSupplierQueue.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NexusWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollTaskExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/PollerOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactoryOptions.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/SlotSupplier.java
- temporal-sdk/src/test/java/io/temporal/worker/LocalActivitySlotThreadPoolTests.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ParallelLocalActivitiesTest.java
Avoid putting the worker into a useless state if submitting a local activity for execution fails (ex: OOM / other thread starting problems). 
Bad times when you don't know why your worker is stuck
1. Closes https://github.com/temporalio/sdk-java/issues/2349
Added an integration test with an executor service that fails intentionally
> Avoid lock up on unexpected ExecutorService errors while executing Local Activities

- temporal-sdk/src/main/java/io/temporal/activity/ActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/ActivityExecutionContextBase.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityTaskExecutors.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextFactoryImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DynamicSyncWorkflowDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOWorkflowImplementationFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowDefinition.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/workflow/GetInstanceTest.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Provide access to workflow/activity instance from their context. There is some subtly around when the workflow instance is created, I tried to document this in the user visible method.
Note: I did not do anything for Nexus here because the `OperationHandler` is already passed to the interceptor.
closes: https://github.com/temporalio/sdk-java/issues/2361
> Access to workflow/activity instance from context

- README.md
- build.gradle
- gradle/java.gradle
- temporal-sdk/build.gradle
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/ScheduleProtoUtil.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/TestHistoryBuilder.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/UpdateProtocolStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/DynamicUpdateTest.java
- temporal-serviceclient/build.gradle
- temporal-serviceclient/src/main/java/io/temporal/internal/common/ProtoUtils.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/RpcRetryOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/StatusUtils.java
- temporal-test-server/build.gradle
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestServiceRetryState.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusWorkflowTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowCachingTest.java
Update the Java SDK protoc and protobuf dependency to support proto-java 3.x and 4.x
See also: https://github.com/grpc/grpc-java/issues/11015#issuecomment-2560196695
closes https://github.com/temporalio/sdk-java/issues/2006
> Support Proto 3 and 4

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/UpdateProtocolStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/SpeculativeUpdateTest.java
Enable speculative workflow tasks
> Enable speculative workflow tasks

- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/ChildWorkflowOptions.java
Update docs for max workflow task timeout, see the bottom of https://docs.temporal.io/encyclopedia/detecting-workflow-failures#workflow-task-timeout
> Update docs for max workflow task timeout

- temporal-sdk/src/main/java/io/temporal/client/NamespaceInjectWorkflowServiceStubs.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowClientInternalImpl.java
- temporal-sdk/src/test/java/io/temporal/authorization/AuthorizationTokenTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateWithStartTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
Inject Namespace in grpc headers. Unfortunately I couldn't use gRPC interceptors as originally proposed because java's gRPC interceptors cannot modify the header based of the content of the message https://github.com/grpc/grpc-java/issues/4684#issuecomment-410315965
closes https://github.com/temporalio/sdk-java/issues/2058
> Inject namespace header

- releases/v1.27.1
Release v1.27.1, this fixes a bug prevent the Java SDK from being able to use Nexus with Temporal Server v1.26.2+
> Release v1.27.1

- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
Update max task timeout in the test server to match docs 
see also https://github.com/temporalio/sdk-java/commit/de33b3adeefbc0d605094657ee78867d49150bae
> Update max task timeout in Test Server

- temporal-spring-boot-autoconfigure/README.md
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/ConnectionProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/ApiKeyAuthTest.java
- temporal-spring-boot-autoconfigure/src/test/resources/application.yml
Add API key property to Springboot
closes https://github.com/temporalio/sdk-java/issues/2289
> Add API key property to Springboot

- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/workflow/determinism/NonDeterministicWorkflowPolicyBlockWorkflowTest.java
closes https://github.com/temporalio/sdk-java/issues/2418
> Make sure workflow_task_execution_failed always has a failure_reason

- temporal-sdk/src/main/java/io/temporal/internal/Config.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowTaskResult.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerTaskHandlerTests.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/TestHistoryBuilder.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/WorkflowStateMachinesTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WritesSDKNameVersionTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityGettingScheduledRightBeforeWorkflowTaskHeartbeatTest.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/Version.java
Write name and version to task completions
Parity 
1. Closes https://github.com/temporalio/sdk-java/issues/1838
Added unit tests
> Add sdk name/version to task completions when unset or changed

- .github/workflows/ci.yml
- temporal-sdk/src/main/java/io/temporal/client/OnConflictOptions.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientRequestFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/NexusOperationStateMachine.java
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowHandleFactory.java
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowRunOperation.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationFailTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncOperationTimeoutTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleFailOnConflictTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleUseExistingOnConflictCancelTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleUseExistingOnConflictTest.java
Add support for attaching to a running workflow.
See similar Go PR: https://github.com/temporalio/sdk-go/pull/1797
> Add support for attaching to a running workflow

- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleUseExistingOnConflictCancelTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleUseExistingOnConflictTest.java
Block using conflict policy UseExisting for Nexus WorkflowRunOperation
see also https://github.com/temporalio/sdk-go/pull/1845
> Block using conflict policy UseExisting for Nexus WorkflowRunOperation

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
Java doc in CapacityConfigurationProperties
```
maxConcurrentWorkflowTaskExecutors defines {@link
*     io.temporal.worker.WorkerOptions.Builder#setMaxConcurrentWorkflowTaskPollers(int)
```
But it is incorrect
https://github.com/temporalio/sdk-java/blob/49bd366af37343f1cba2bbec0fc7f61718fd5bb1/temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java#L56
> fix documentation in CapacityConfigurationProperties

- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/ApiKeyAuthTest.java
Fix some issues with API key auth:
* If the worker was not connected the SDK would try to make a health check call which is not namespaced so doesn't work well with API keys
* typo in the spring auto config
> Fix API key auth

- releases/v1.28.1
> Release v1.28.1

- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleUseExistingOnConflictCancelTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleUseExistingOnConflictTest.java
Unblock `UseExisting` conflict policy for Nexus `WorkflowRunOperation` (revert https://github.com/temporalio/sdk-java/pull/2428).
1. Closes 
> Unblock UseExisting conflict policy for Nexux WorkflowRunOperation

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/WorkflowIdReusePolicyTest.java
Fix logic handling workflow ID reuse policy and conflict policy.
Refactor the code, make it cleaner.
Reflect recent changes in Temporal Server in https://github.com/temporalio/temporal/pull/7097 and https://github.com/temporalio/temporal/pull/7099.
1. Closes 
> Fix workflow ID reuse policy and conflict policy handling

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/NexusOperationStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusOperationOptions.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/CancelNexusOperationStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/NexusOperationStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/NexusOperationMetadataTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Add Summary to Nexus Operations
closes https://github.com/temporalio/sdk-java/issues/2442
> Add Summary to Nexus Operations

- releases/v1.28.2
- temporal-sdk/src/main/java/io/temporal/workflow/NexusOperationOptions.java
> Release v1.28.2

- releases/v1.28.3
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowRunOperation.java
> Release v1.28.3

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivitySlotSupplierQueue.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NexusPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/TrackingSlotSupplier.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/FixedSizeSlotSupplier.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/ResourceBasedSlotSupplier.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/ResourceBasedTuner.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/SlotSupplier.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/SlotSupplierFuture.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/SlotSupplierTest.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowSlotsSmallSizeTests.java
- temporal-sdk/src/test/java/io/temporal/testUtils/CountingSlotSupplier.java
- temporal-sdk/src/test/java/io/temporal/worker/ResourceBasedTunerTests.java
- temporal-sdk/src/test/java/io/temporal/worker/tuning/FixedSizeSlotSupplierTest.java
Made the `reserveSlot` method on `SlotSupplier` interface async.
Note that, as it stands, this can actually slightly _increase_ the number of threads used because the slot suppliers have been changed in a way that they will not block the caller (which is the whole point) but in order to do that, the resource based one at least needs a couple threads that it didn't before. 
For the fixed size supplier, I think I've managed to come up with something that should always be non-blocking.
This is to support https://github.com/temporalio/sdk-java/issues/1456 where the pollers themselves will be made async, and thus will be able to take advantage of async slot reservation as well.
1. Closes 
Existing tests
> :boom: [Breaking] Asyncify slot suppliers

- .github/workflows/ci.yml
- temporal-sdk/src/main/java/io/temporal/activity/ActivityInfo.java
- temporal-sdk/src/main/java/io/temporal/activity/ActivityOptions.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/common/Priority.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/ScheduleProtoUtil.java
- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientRequestFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/common/PriorityUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/BasicWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/ChildWorkflowOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-sdk/src/test/java/io/temporal/workflow/PriorityInfoTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/PriorityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/searchattributes/SearchAttributesTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TaskQueue.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStore.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/searchattributes/IncorrectStartWorkflowSearchAttributesTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/searchattributes/IncorrectUpsertSearchAttributesTest.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Added priority annotations to starting workflows & activities
New feature!
1. Closes https://github.com/temporalio/sdk-java/issues/2399
> [!NOTE]
> No tests yet. Ideally will write integ tests if we make a CLI RC 
Will need docs for Priority generally
> Priorities for Workflows/Activities

- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/activity/ActivityHeartbeat.java
closes https://github.com/temporalio/sdk-java/issues/2459
> Ensure heartbeat details aren't cleared

- .github/workflows/ci.yml
- temporal-sdk/src/test/java/io/temporal/client/functional/StartDelayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowRetryTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Add support for start delay to the time skipping test server.
closes https://github.com/temporalio/sdk-java/issues/1692
> Add support for start delay to the time skipping test server

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-sdk/src/test/java/io/temporal/workflow/GetRootWorkflowExecutionTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
Align root workflow execution with real server. The real server does not set `rootWorkflowExecution` if a workflow is its own root in history. This change makes sure the test server respects that behaviour. Also change the API since it is more likely for a `null` value to be present. No backwards compatibility concerns since this API has not been release yet.
> Align root workflow execution with real server

- .github/workflows/ci.yml
- temporal-sdk/src/main/java/io/temporal/client/ActivityPausedException.java
- temporal-sdk/src/main/java/io/temporal/client/ActivityWorkerShutdownException.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContextImpl.java
- temporal-sdk/src/test/java/io/temporal/activity/ActivityPauseTest.java
closes https://github.com/temporalio/sdk-java/issues/2465
> Add support for activity pause

- temporal-sdk/src/main/java/io/temporal/internal/nexus/OperationTokenUtil.java
- temporal-sdk/src/test/java/io/temporal/internal/nexus/WorkflowRunTokenTest.java
Remove old workflow run operation token format
closes https://github.com/temporalio/sdk-java/issues/2423
> Remove old workflow run operation token format

- temporal-sdk/src/test/java/io/temporal/internal/testing/ActivityTestingTest.java
- temporal-testing/src/main/java/io/temporal/testing/ActivityRequestedAsyncCompletion.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironment.java
- temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java
Handle async completion in TestActivityEnvironment
> Handle async completion in TestActivityEnvironment

- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowMetadataTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
Make sure user metadata is set on WorkflowExecutionStartedEvent
closes https://github.com/temporalio/sdk-java/issues/2494
> Make sure user metadata is set on WorkflowExecutionStartedEvent

- temporal-sdk/src/main/java/io/temporal/failure/ApplicationErrorCategory.java
- temporal-sdk/src/main/java/io/temporal/failure/ApplicationFailure.java
- temporal-sdk/src/main/java/io/temporal/failure/DefaultFailureConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/common/FailureUtils.java
- temporal-sdk/src/test/java/io/temporal/failure/ApplicationFailureTest.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/ActivityFailedMetricsTests.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowFailedMetricsTests.java
Add `ApplicationFailure.Builder` to handle the growing number of options on `ApplicationFailure`
> Add ApplicationFailure.Builder

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/AutoDiscoveryByWorkerNameTest.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/TestDynamicWorkflowImpl.java
Add support for dynamics workflows to Springboot
closes https://github.com/temporalio/sdk-java/issues/1449
> Add support for dynamics workflows to Springboot

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/WorkflowImplementationOptionsCustomizer.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowImplementationOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/OptionsCustomizersTest.java
Support WorkflowImplementationOptionsCustomizer so users can customize workflow implementation options per type in Springboot
closes https://github.com/temporalio/sdk-java/issues/1984
> Support WorkflowImplementationOptionsCustomizer

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/AutoDiscoveryWithProfileTest.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/OtherTestActivityImpl.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/OtherTestWorkflowImpl.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/TestActivityImpl.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/byworkername/TestWorkflowImpl.java
- temporal-spring-boot-autoconfigure/src/test/resources/application.yml
Make sure `@Profile` works for `WorkflowImpl`
closes https://github.com/temporalio/sdk-java/issues/2121
> Make @Profile annotation work

- temporal-spring-boot-autoconfigure/README.md
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/AutoConfigurationUtils.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/NonRootBeanPostProcessor.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/TestServerAutoConfiguration.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/ClientTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/NamespaceTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/NonRootNamespaceTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerFactoryOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowClientOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/InterceptorsTest.java
Add interceptor support to Springboot integration. With this PR any interceptor bean will be automatically picked up and registered with the worker/client. Similar to Quarkus support for [interceptors](https://docs.quarkiverse.io/quarkus-temporal/dev/index.html#_interceptors) in Temporal.
Note: Currently not supported in multi namespace.
closes: https://github.com/temporalio/sdk-java/issues/1634
> Add interceptor support to springboot integration

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/NamespaceProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/NonRootNamespaceProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/TemporalProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
Spring boot fail creation if duplicate definitions detected. This matches the behaviour of the regular Java SDK and most other SDKs. Users can still disable this with a new config.
closes https://github.com/temporalio/sdk-java/issues/2434
> Spring boot: fail creation if duplicate definitions detected

- temporal-sdk/src/main/java/io/temporal/internal/common/SdkFlag.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/CancellationScopeImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/cancellationTests/WorkflowCancellationScopeDeterminism.java
- temporal-sdk/src/test/resources/cancellationScopeDeterminism.json
Make `CancellationScopeImpl` more deterministic, our use of `HashSet` is not deterministic since we iterate over the map and the order matters her. 
closes https://github.com/temporalio/sdk-java/issues/2473
> Make CancellationScopeImpl more deterministic

- temporal-sdk/src/test/java/io/temporal/workflow/cancellationTests/ExternalWorkflowCancelTest.java
Add test coverage for cancellation of external workflow
closes https://github.com/temporalio/sdk-java/issues/1709
> Add test coverage for cancellation of external workflow

- temporal-sdk/src/main/java/io/temporal/client/WorkflowStub.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/workflow/cancellationTests/WorkflowAwaitCancellationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/cancellationTests/WorkflowAwaitWithDurationCancellationTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-testing/src/main/java/io/temporal/testing/TimeLockingInterceptor.java
Wire reason parameter in workflow cancellation request. Not this does not cover wiring the cancellation reason on the workflow side. There is a different issue to track that work.
closes https://github.com/temporalio/sdk-java/issues/1350
> Wire reason parameter in workflow cancellation request

- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/workflow/ExternalWorkflowGetExecutionTest.java
Fix Workflow.getWorkflowExecution for ExternalWorkflowStub. The docs said this should work but it never has, now it will. Technically a backwards incompatible change, previously it just caused a task failure so this should be fine.
closes https://github.com/temporalio/sdk-java/issues/1237
> Fix Workflow.getWorkflowExecution for ExternalWorkflowStub

- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
Make asyncThrottlerExecutor use a daemon thread so the executor doesn't hold up JVM shutdown.
closes https://github.com/temporalio/sdk-java/issues/2450
> Make asyncThrottlerExecutor use a daemon thread

- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityExecutionContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityTaskExecutors.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContext.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/InternalActivityExecutionContext.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/LocalActivityExecutionContextImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityTimeoutTest.java
Cancel pending heartbeat when activity completes. This prevents the heartbeat from holding up worker shutdown and prevents heartbeating an already completed activity
closes: https://github.com/temporalio/sdk-java/issues/1256
> Cancel pending heartbeat when activity completes

- build.gradle
- temporal-test-server/build.gradle
> Bump some proto dep.

- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunnerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/QueryDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/RunnerLocalInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/QueryDispatcherTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/WorkflowInfoAndLocalInQueryTest.java
Add support for calling `Workflow.getInfo` from query handler. The problem is query handlers aren't run in workflow threads. Running them in workflow threads is not really a viable solution since they are run independently of the other workflow threads so I added a new path to pass the workflow context when in a query.
closes https://github.com/temporalio/sdk-java/issues/1120
closes https://github.com/temporalio/sdk-java/issues/294
> Add support for calling `Workflow.getInfo` from query handler

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/CurrentNexusOperationContext.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/InternalNexusOperationContext.java
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowRunOperationImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleUseExistingOnConflictTest.java
Use link from start workflow request for Nexus operations to match the changes we made to the Go SDK
see also: https://github.com/temporalio/sdk-go/pull/1934
closes https://github.com/temporalio/sdk-java/issues/2523
> Use link from start workflow request for Nexus operations

- temporal-sdk/src/main/java/io/temporal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/test/java/io/temporal/internal/common/WorkflowExecutionHistoryTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityAfterCancelTest.java
- temporal-sdk/src/test/resources/simpleHistory_withWorkflowId.json
> Issue #2057: parsing workflow id from WorkflowExecutionStartedEventAttributes

- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/test/java/io/temporal/common/converter/CodecDataConverterTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowMetadataTest.java
closes https://github.com/temporalio/sdk-java/issues/2426
> __temporal_workflow_metadata query responses should use "RawValue"

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/NamespaceProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
Fix `ignoreDuplicateDefinitions` to log only if we are ignoring
> Fix ignoreDuplicateDefinitions to log only if we are ignoring

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/AutoDiscoveryAndExplicitWithDuplicatesTest.java
- temporal-spring-boot-autoconfigure/src/test/resources/application.yml
Don't fail Springboot init. if a bean is specified twice. With explicit config and auto discovery it is possible a user specifies the same bean or class for auto-discovery, in this case we shouldn't fail init since while it is technically a duplicate registration it is an identical registration.
> Don't fail Springboot if a bean is specified twice

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/NamespacesPresentCondition.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/NonRootBeanPostProcessor.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/NonRootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/MultiNamespaceTest.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/StartWorkersTest.java
Fix some dependency issues with NonRootBeanPostProcessor. Also don't attempt to create `NonRootBeanPostProcessor` if we are not in a multinamespace config.
> Fix some dependency issues with NonRootBeanPostProcessor

- .github/workflows/build-native-image.yml
Fix build native image action to use the correct input
> Fix build native image action to use the correct input

- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/PollerBehavior.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/PollerBehaviorAutoscaling.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/PollerBehaviorSimpleMaximum.java
Make sure PollerBehavior is marked as Experimental
> Make sure PollerBehavior is marked as Experimental

- temporal-sdk/src/main/java/io/temporal/internal/worker/AsyncPoller.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/PollerBehaviorAutoscaling.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanNexusWorkerShutdownTest.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/OptionalWorkerOptionsTest.java
- temporal-spring-boot-autoconfigure/src/test/resources/application.yml
Add defaults for `PollerBehaviorAutoscaling` to match the Python SDK.
> Add defaults for PollerBehaviorAutoscaling

- gradle/publishing.gradle
Publish to Sonatype central since [ossrh](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/) is end of life
following this guide: https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/
> Publish to Sonatype central

- README.md
Update snapshot URL since we moved to sonatype central
> Update snapshot URL

- temporal-sdk/src/test/java/io/temporal/internal/worker/AsyncPollerTest.java
Fix flake in `testNullTaskReleasesSlot`. `testNullTaskReleasesSlot` Was sometime failing locally if the poller got called more then once, so this assertion would fail
```
assertEquals(1, slotSupplierInner.reservedCount.get());
```
Since 2 or more slots would have gotten reserved by that point. There is nothing wrong with that so relaxing the assertion.
> Fix flake in testNullTaskReleasesSlot

- temporal-sdk/src/main/java/io/temporal/failure/DefaultFailureConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/NexusOperationStateMachine.java
- temporal-sdk/src/test/java/io/temporal/internal/nexus/NexusTaskHandlerImplTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/CancelNexusOperationStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/NexusOperationStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusWorkflowTest.java
Update Proto API to v1.50.0. Removing some deprecated fields in the test server.
Note: Left support for Nexus operation ID in just the workflow code so we can continue to support old histories.
> Update Proto API to v1.50.0

- .github/workflows/ci.yml
- temporal-sdk/src/test/java/io/temporal/worker/WorkerVersioningTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/DescribeWorkflowExecutionTest.java
> Update test server to v1.4.0

- temporal-sdk/src/main/java/io/temporal/client/ActivityResetException.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/HeartbeatContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/test/java/io/temporal/activity/ActivityResetTest.java
Add support for activity reset
closes https://github.com/temporalio/sdk-java/issues/2488
> Add support for activity reset

- temporal-sdk/src/main/java/io/temporal/failure/ApplicationFailure.java
- temporal-sdk/src/main/java/io/temporal/failure/DefaultFailureConverter.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/ActivityFailedMetricsTests.java
Fix ApplicationFailure.Builder handling a null Category
closes https://github.com/temporalio/sdk-java/issues/2601
> Fix ApplicationFailure.Builder handling a null Category

- temporal-sdk/src/main/java/io/temporal/worker/tuning/ResourceBasedController.java
Correct PID controller config for Memory usage. Currently, pid controller for memory is using the config from CPU options
Resource base tuner currently running with wrong configuration
1. Closes 
2. How was this tested: Compile test
3. Any docs updates needed? No
> Fix using wrong config option for resource controller

- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/OperationFailureConversionTest.java
Align Nexus handler failure conversion with other SDKs
closes https://github.com/temporalio/sdk-java/issues/2612
> Align Nexus handler failure conversion with other SDKs

- temporal-sdk/src/main/java/io/temporal/failure/ApplicationFailure.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/testUtils/LoggerUtils.java
- temporal-sdk/src/test/java/io/temporal/workflow/GrpcMessageTooLargeTest.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcMessageTooLargeException.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryerUtils.java
- temporal-serviceclient/src/main/java/io/temporal/internal/testservice/GRPCServerHelper.java
- temporal-serviceclient/src/main/java/io/temporal/internal/testservice/InProcessGRPCServer.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcAsyncRetryerTest.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcSyncRetryerTest.java
- `GrpcRetryer` does not retry on gRPC error if the cause is message size limit, instead wraps the error in the new custom `GrpcMessageTooLargeException` and throws.
- `WorkflowWorker` catches `GrpcMessageTooLargeException` on reporting workflow task completion/failure, and reports task failure with this error. This does NOT prevent server-side retry of the workflow task, but it does record the error in event history for easier debugging.
Feature request: https://github.com/temporalio/features/issues/624
1. Closes #1585
2. How was this tested: added tests to `GrpcSyncRetryerTest`, `GrpcAsyncRetryerTest` and `GrpcMessageTooLargeTest`.
> Do not auto-retry gRPC-message-size-too-large errors

- temporal-sdk/src/main/java/io/temporal/common/converter/DataConverter.java
- temporal-sdk/src/test/java/io/temporal/common/converter/DataConverterTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/GenericParametersWorkflowTest.java
Fix adding a generic parameter failing.
Previously adding a new parameter of type List to a workflow input causes the data converter to fail.
From:
```
@WorkflowMethod
String execute(String name);
```
to :
```
@WorkflowMethod
String execute(String name, List<String> names);
```
closes https://github.com/temporalio/sdk-java/issues/2413
> Fix adding a generic parameter failing

- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowRunOperationImpl.java
Nexus - Only pass a completion callback if a completion URL is provided. Currently a completion URL is always provided, but once we add external callbacks a completion URL may not always be present.
closes https://github.com/temporalio/sdk-java/issues/2614
> Nexus - Only pass a completion callback if a completion URL is provided

- temporal-sdk/src/main/java/io/temporal/activity/ActivityInfo.java
- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityInfoImpl.java
- temporal-sdk/src/test/java/io/temporal/activity/ActivityInfoTest.java
- temporal-testing/src/main/java/io/temporal/testing/internal/SDKTestOptions.java
- Added retry options to ActivityInfo.
- Added ActivityInfo tests that check if it's populated properly.
Feature request: https://github.com/temporalio/features/issues/615
1. Closes #2481 
New test suite added.
> Added retry options to ActivityInfo. Added ActivityInfo tests.

- temporal-sdk/src/main/java/io/temporal/workflow/ChildWorkflowCancellationType.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusOperationCancellationType.java
Clarify that cancelling a Nexus operation can fail and how the SDK reacts to that.
> Clarify NexusOperationCancellationType

- .github/workflows/prepare-release.yml
For sonatype central we now need to close the repo as part of CI since it won't be visible in the UI to publish until closed
https://github.com/gradle-nexus/publish-plugin/issues/379
> Fix sonatype publish

- temporal-sdk/src/main/java/io/temporal/internal/worker/AsyncWorkflowPollTask.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
Make sure workflow_task_queue_poll_succeed is emitted for poller autoscaling
closes https://github.com/temporalio/sdk-java/issues/2644
> Make sure workflow_task_queue_poll_succeed is emitted

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/TemporalOptionsCustomizer.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/AutoConfigurationUtils.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/NonRootBeanPostProcessor.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/ServiceStubsAutoConfiguration.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/TestServerAutoConfiguration.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/ClientTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/NamespaceTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/NonRootNamespaceTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/ServiceStubsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerFactoryOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowClientOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowImplementationOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/OptionsCustomizersTest.java
Allow multiple customizers in Springboot
> Allow multiple customizers in Springboot

- docker/native-image-musl/dockerfile
- docker/native-image-musl/install-musl.sh
- temporal-sdk/src/main/java/io/temporal/common/interceptors/NexusOperationOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/NexusOperationOutboundCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/InternalNexusOperationContext.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/RootNexusOperationOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/TemporalInterceptorMiddleware.java
- temporal-sdk/src/main/java/io/temporal/nexus/NexusInfo.java
- temporal-sdk/src/main/java/io/temporal/nexus/NexusOperationContext.java
- temporal-sdk/src/main/java/io/temporal/nexus/NexusOperationInfo.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/NexusOperationInfoTest.java
Add `NexusInfo` to expose Temporal specific information to a Nexus handler
closes https://github.com/temporalio/sdk-java/issues/2657
> Add NexusInfo
