- docker/buildkite/docker-compose.yaml
bringing `docker-compose.yml` up to date w/our current docker image naming conventions.
> updating image name in docker-compose.yml

- src/main/java/io/temporal/internal/testservice/QueryId.java
- src/main/java/io/temporal/internal/testservice/StateMachines.java
- src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
The previous attempt was based on the original consistent query design and didn't take into account how consistent query implemented by the server.
> Fixed TestService consistent query

- src/main/java/io/temporal/internal/sync/ActivityInvocationHandlerBase.java
- src/main/java/io/temporal/internal/sync/WorkflowClientInternal.java
- src/main/java/io/temporal/internal/sync/WorkflowInternal.java
Fix for https://github.com/uber/cadence-java-client/issues/416
See [this stack overflow answer](https://stackoverflow.com/a/13379769/1664318) for explanation.
> Switched newProxyInstance to the correct class

- build.gradle
> micrometer 1.5.1

- build.gradle
Changes needed to successfully publish a release.
> Publishing to maven central fixed

- src/main/java/io/temporal/internal/statemachines/SideEffectStateMachine.java
- src/test/java/io/temporal/internal/statemachines/SideEffectStateMachineTest.java
Fixes side effect state machine failure on history replay.
> Side effect fix

- src/main/java/io/temporal/internal/metrics/MetricsType.java
Fix metrics name for consistency with other metrics and constant name.
> Fix metrics name

- src/main/java/io/temporal/activity/Activity.java
- src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
https://github.com/temporalio/java-sdk/issues/187
> Change type to `Throwable`

- src/main/java/io/temporal/failure/ApplicationFailure.java
- src/test/java/io/temporal/workflow/WorkflowTest.java
Validates that https://github.com/temporalio/java-sdk/issues/24 was fixed.
> Added getVersion marker validation

- README.md
- src/main/java/io/temporal/client/WorkflowClientOptions.java
It is useless anyway as gRPC still doesn't work without /etc/hosts modification.
> Removed mac-book identity override

- src/main/java/io/temporal/internal/statemachines/DynamicTransitionAction.java
- src/test/java/io/temporal/workflow/SideEffectRaceConditionTest.java
Fixing race condition in side effect state machine that caused multiple types of failures during performance runs.
> Fix race condition in side effect function.

- src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
> Fix typo in the failure event message

- .buildkite/pipeline.yml
- docker/buildkite/docker-compose.yaml
This change updates auto-setup to 1.1.1 and enables containerized docker build against real service.
> Enable build with real service backend

- temporal-sdk/src/main/java/io/temporal/common/RetryOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/common/CheckedExceptionWrapper.java
Prompted by https://community.temporal.io/t/retryoptions-setdonotretry-documentation-mismatch/1038/2
> Updated setDoNotRetry javadoc

- temporal-sdk/src/main/java/io/temporal/client/WorkflowClientOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/SingleWorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTaskFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/test/java/io/temporal/worker/StickyWorkerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowTest.java
Simply set binary checksum in WorkflowClientOptions
```
WorkflowClient client =
WorkflowClient.newInstance(
service, WorkflowClientOptions.newBuilder().setBinaryChecksum("12345").build());
```
> Adding binary checksum to WorkflowClientOptions

- temporal-sdk/src/main/java/io/temporal/common/converter/EncodedValues.java
- temporal-sdk/src/main/java/io/temporal/internal/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/AsyncActivityCompleteWithErrorTest.java
> Add a test for completion of async activity with error

- releases/v1.0.5
Releasing 1.0.5 version of java sdk.
> Release 1.0.5

- temporal-testing-junit5/src/main/java/io/temporal/testing/TestActivityExtension.java
- temporal-testing-junit5/src/main/java/io/temporal/testing/TestWorkflowExtension.java
- temporal-testing-junit5/src/test/java/io/temporal/testing/TestWorkflowExtensionTest.java
* Extend JUnit 5 `TestWorkflowExtensionTest` to illustrate activity calls from test workflows. See discussion at https://github.com/temporalio/sdk-java/pull/338#discussion_r573532550.
* Fix typos in Javadoc code examples
> Polish for JUnit 5 extension

- gradle/wrapper/gradle-wrapper.properties
- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
Some dependencies were way out of date. 
Eg lates version of Google's junit-toolbox contains very old libraries. Removed it and replaced with up to date libraries instead.
> Updated Gradle and dependencies.

- releases/v1.0.6
> Adding release notes for 1.0.6

- temporal-sdk/src/test/java/io/temporal/workflow/ActivityRetryWithMaxAttemptsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/AsyncActivityRetry.java
- temporal-sdk/src/test/java/io/temporal/workflow/DynamicWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/ParallelLocalActivitiesTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/TryCancelActivityTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/SDKTestWorkflowRule.java
Add addWorkflowImplementationFactory ability to the SDKTestWorkflowRule to support what DynamicWorkflowTest.
> AddWorkflowImplementationFactory for DynamicWorkflowTest

- temporal-sdk/src/main/java/io/temporal/common/interceptors/ActivityInboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ActivityInfoInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- temporal-testing-junit4/src/main/java/io/temporal/testing/TracingWorkerInterceptor.java
Partially addresses #373.
Header is added into ActivityInboundCallsInterceptor#execute method input.
> InboundActivityInterceptor now has an access to header

- releases/v1.0.7
> Release v1.0.7

- README.md
Links in the README were changed.
Page URLs in the docs have changed.
1. Closes issue:
N/A
N/A
N/A
> Updating links to docs in README

- .buildkite/pipeline.yml
- docker/buildkite/Dockerfile
- docker/buildkite/docker-compose.yaml
Add Fossa scans to buildkite
Adding license scans
> Add Fossa scans

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/activity/ActivityWorkerHelper.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/WorkflowTestingTest.java
Added context propagation for local actvities
Issue #489 
unit test for the issue provided in this PR
> Added context propagation for local activities

- releases/v1.0.9
Release v1.0.9:
- Fix health check attributes
> Release v1.0.9

- temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java
- temporal-sdk/src/test/java/io/temporal/worker/CleanWorkerShutdownTest.java
> Reverting Pull#469

- temporal-sdk/src/test/java/io/temporal/workflow/NonDeterministicWorkflowPolicyBlockWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/UUIDAndRandomTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionAddNewBeforeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionRemovedBeforeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionRemovedInReplayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionSameIdOnReplayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionSameIdTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionWorkflowRemoveTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionWorkflowReplaceCompletelyTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionWorkflowReplaceGetVersionIdTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/VersionNotSupportedTest.java
Fixed tests that passed without replaying. Added logic to make sure tests actually replay.
> Fixed tests that passed without replaying.

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
> Fix function naming for reset sticky

- temporal-serviceclient/src/main/java/io/temporal/conf/EnvironmentVariableNames.java
An absent license header has been added
> Fix license header on EnvironmentVariableNames

- temporal-sdk/src/main/java/io/temporal/internal/sync/POJOActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestActivities.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
> Local activity counter wasn't incremented

- build.gradle
- temporal-sdk/src/test/java/io/temporal/workflow/ExecuteTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/GetAttemptFromWorkflowInfoTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MemoTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/SagaTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/SearchAttributesTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/StartTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowIdReusePolicyTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildAsyncWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ParentWorkflowInfoInChildWorkflowsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/UntypedChildStubWorkflowAsyncInvokeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/UntypedChildStubWorkflowAsyncTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/UntypedChildStubWorkflowTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestMultiArgWorkflowFunctions.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestNoArgsWorkflowFuncParent.java
- temporal-testing-junit4/build.gradle
> Typos and shorter names

- temporal-kotlin/src/main/kotlin/io/temporal/internal/async/KotlinMethodReferenceDisassemblyService.kt
- temporal-kotlin/src/test/kotlin/io/temporal/workflow/KotlinAsyncCompanionFunctionTest.kt
- temporal-kotlin/src/test/kotlin/io/temporal/workflow/KotlinAsyncLambdaTest.kt
Add more unit tests for Kotlin `Async` support
Code in `KotlinMethodReferenceDisassemblyService` is restructured to handle Lambda cases more explicitly
> Add more unit tests for Kotlin Async

- temporal-sdk/src/main/java/io/temporal/common/converter/DefaultDataConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientHelper.java
- temporal-sdk/src/main/java/io/temporal/internal/common/HeaderUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
Refactored [HeaderUtils#intoPayloadMapWithDefaultConverter ](https://github.com/temporalio/sdk-java/blob/4bcb7afac686c075c5e64528e0cfec06aab136d8/temporal-sdk/src/main/java/io/temporal/internal/common/HeaderUtils.java#L48)to accept converter as parameter.
Memo serialization needs to use a user-defined converter
1. Closes #677
> Added converter parameter to HeaderUtils#intoPayloadMapWithDefaultConverter

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Just a small typo. Community request via Slack (https://temporalio.slack.com/archives/CTT84KXK9/p1631048635026200)
> Small typo in ReplayWorkflowTaskHandler

- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LongLocalActivityWorkflowTaskHeartbeatFailureTest.java
Improve LongLocalActivityWorkflowTaskHeartbeatFailureTest flakiness
Closes #672
> Improve LongLocalActivityWorkflowTaskHeartbeatFailureTest flakiness

- temporal-sdk/build.gradle
- temporal-serviceclient/build.gradle
> Update proto and micrometer dependencies

- temporal-sdk/src/main/java/io/temporal/activity/ActivityCancellationType.java
- temporal-sdk/src/main/java/io/temporal/activity/ActivityOptions.java
Improve ActivityCancellationType doc
Fix `ActivityOptions.Builder#setCancellationType`
> Improve javadocs around ActivityCancellationType

- README.md
Upgrade proto submodule to the latest server API: https://github.com/temporalio/api (v.1.6.0)
> Upgrade proto to the latest server API

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowExecutorCache.java
Improve trace telemetry about modifying of WorkflowExecutorCache
> Improve trace logging around WorkflowExecutorCache

- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
We allowed subsequent calls to `#newWorker` for a task queue that already has a worker associated with it. Old created worker gets silently discarded in that case. This behavior makes users think that it makes sense to register several workers under the same task queue for scaling purposes.
We ignore subsequent calls, logging a warning message.
> Adds warning log message in case of subsequent new worker calls for the same task queue

- temporal-sdk/src/main/java/io/temporal/common/RetryOptions.java
- temporal-sdk/src/test/java/io/temporal/common/RetryOptionsTest.java
Add validation for RetryOptions#maximumInterval vs RetryOptions#minimumInterval
Closes #898
> Add validation for maximumInterval vs minimumInterval

- temporal-sdk/src/main/java/io/temporal/internal/history/MarkerUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/history/VersionMarkerUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
Add a local activity type into a NonDeterministicException error message
> Improve an error message for an unexpected local activity marker event

- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
describeWorkflowExecution now grabs the lock before copying data from the StateMachine to the response object.
I observed an exception when a stripe user's test called describeWorkflowExecution when other threads were updating the contents of `this.activities`.
```
java.util.ConcurrentModificationException
at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1680)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(Referenc …
```
> Avoid ConcurrentModificationExceptions in describeWorkflowExecution

- CONTRIBUTING.md
- README.md
- gradle/publishing.gradle
- Rename temporal-java-sdk ➡️ sdk-java
- Condense README
I think this more concise format is easier to read/absorb.
Is the repo change in the gradle file safe?
> Condense README and rename to sdk-java

- temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Put the listener removal in a finally block 
So the listener is removed even when the get() call throws.
1. Closes 
> Guarantee context listener removal

- temporal-opentracing/src/main/java/io/temporal/opentracing/internal/OpenTracingWorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ShutdownManager.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/main/java/io/temporal/workflow/package-info.java
- temporal-sdk/src/main/java/io/temporal/workflow/unsafe/WorkflowUnsafe.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/Tracer.java
- temporal-sdk/src/test/java/io/temporal/workflow/UUIDAndRandomTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityRetryOptionsChangeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncActivityRetryOptionsChangeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/AsyncRetryOptionsChangeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/determinism/DeterminismFailingWorkflowImpl.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionAddNewBeforeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionRemovedBeforeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionRemovedInReplayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionSameIdOnReplayTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionSameIdTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionWithoutCommandEventTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionWorkflowRemoveTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionWorkflowReplaceCompletelyTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionWorkflowReplaceGetVersionIdTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/versionTests/VersionNotSupportedTest.java
- temporal-testing/src/main/java/io/temporal/testing/internal/TracingWorkerInterceptor.java
Added WorkflowUnsafe#isWorkflowThread
Relocated general Workflows javadoc from Workflow class onto `io.temporal.workflow.package-info`
Closes #955
> WorkflowUnsafe#isWorkflowThread

- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/LocalActivityWorkerTest.java
Fix a problem with LocalActivityWorker ignoring initial and maximum intervals
Closes #989
> Fix a problem with LocalActivityWorker ignoring initial and maximum intervals

- temporal-sdk/src/main/java/io/temporal/common/reporter/MicrometerClientStatsReporter.java
MicrometerReporter now retains references to all created guages to comply with Micrometer API requirements.
Closes #979
> Retain strong references to all Gauges

- .github/workflows/prepare-release.yml
- Made step and job naming consistent
- Removed TODO comment about needing gpg (we don't need it)
- Checkout the user-supplied ref when building the native executables
- General hygiene
- Ability to release from somewhere other than HEAD of master
1. Closes 
> Final prep release cleanup

- .buildkite/pipeline.yml
Retire Fossa instead of trying to get access to its portal.
Coordinated with @mcbryde
> Goodbye Fossa I Never Got Access To

- .whitesource
Changed the config URL to point to the raw GH file, not the site.
> Change Config URL

- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowExecutorCache.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
sticky_cache_size is broken for some time and is published only during eviction from the sticky cache.
This PR fixes it and covers with a test.
> Fix sticky_cache_size gauge behavior

- temporal-sdk/src/test/java/io/temporal/workflow/searchattributes/SearchAttributesTest.java
- temporal-testing/src/main/java/io/temporal/testing/TestEnvironmentOptions.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowExtension.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowRule.java
Just add more search attribute registering options: `TestEnvironmentOptions#registerSearchAttribute`
> Add TestEnvironmentOptions#registerSearchAttribute

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Allow query to come without a deadline in gRPC context, in this case, an unlimited timeout will be used.
The test server shouldn't error out if there is no deadline in the request.
Closes #1205
> Fix Test Server throwing on queries without a deadline

- temporal-testing/src/main/java/io/temporal/testing/IdempotentTimeLocker.java
Fix test rule not respecting `.setUseTimeskipping(false)`
During a past refactoring, I migrated the initial acquisition of the timeskipping lock onto using IdempotentTimeLocker not taking into account that it support only [unlock; lock] sequence, but doesn't support [lock; unlock] correctly.
> Fix test server with disabled time skipping mode

- temporal-sdk/src/main/java/io/temporal/client/WorkflowQueryConditionallyRejectedException.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowQueryRejectedException.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStub.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowStubImpl.java
- temporal-sdk/src/test/java/io/temporal/client/functional/CancelTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/GetResultsAsyncOverMaximumLongPollWaitTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/GetResultsOverLongPollTimeoutTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/GetResultsSyncOverMaximumLongPollWaitTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/GetResultsTimeoutTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/MetricsTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/TerminateTest.java
- temporal-sdk/src/test/java/io/temporal/client/functional/common/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
- temporal-testing/src/main/java/io/temporal/testing/TimeLockingInterceptor.java
Fix WorkflowStub#cancel and WorkflowStub#terminate exceptions contract
Align behavior of test server with the real one in some edge cases related to cancelations.
Closes #1198
> Fix WorkflowStub#cancel and WorkflowStub#terminate exceptions contract

- build.gradle
- gradle/linting.gradle
- temporal-kotlin/.editorconfig
- temporal-opentracing/build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowContext.java
- temporal-serviceclient/build.gradle
- temporal-test-server/build.gradle
State Machine Rewrite #172 left a couple of state machine code in the class that is not responsible for handling state transitions anymore and this code is not invoked.
> Cleanup dead state machines code

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/OperatorServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/SystemInfoInterceptor.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/GetServerCapabilitiesTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/HealthCheckTest.java
- temporal-test-server/src/main/java/io/temporal/serviceclient/TestServiceStubsImpl.java
Adds a new interceptor that fetches systemCapabilities before the first client call can be made.
Closes #1312
> Implement fetching server capabilities before the first server call is made

- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowHistoryIterator.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
Refactor step towards implementing #1315
No changes of behavior in this PR.
> Refactor GrpcRetryer to enforce usage of GrpcRetryerOptions

- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/ManualActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowHistoryIterator.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/WorkflowHistoryIteratorTest.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryerUtils.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcSyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/OperatorServiceStubsImpl.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubs.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsImpl.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcAsyncRetryerTest.java
- temporal-serviceclient/src/test/java/io/temporal/internal/retryer/GrpcSyncRetryerTest.java
- temporal-serviceclient/src/test/java/io/temporal/serviceclient/functional/GetServerCapabilitiesTest.java
- temporal-test-server/src/main/java/io/temporal/serviceclient/TestServiceStubsImpl.java
No retrying on INTERNAL gRPC errors with the new Server versions
Closes #1315
> No retrying on INTERNAL gRPC errors with new Server versions

- temporal-test-server/build.gradle
- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/jni-config.json
- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/native-image.properties
Upgrade Graal options for test-server build
Fix build warning messages and improve build speed
> Upgrade Graal options 

- temporal-sdk/src/main/java/io/temporal/failure/TemporalException.java
- temporal-sdk/src/main/java/io/temporal/failure/TemporalFailure.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowExecuteRunnable.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/DirectQueryReplaysDontSpamLogWithWorkflowExecutionExceptionsTest.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Replays of workflow failures caused by queries don't spam worker logs anymore
Closes #1348
> Replays of workflow failures caused by queries don't spam worker logs anymore

- temporal-sdk/src/main/java/io/temporal/internal/common/ProtoEnumNameUtils.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Align Test Server behavior with the real one if the workflow completion command is not the last command in the commands sequence of workflow task completion request.
Closes #1398
> Align Test Server behavior with the real one if completion command is not the last

- temporal-sdk/src/main/java/io/temporal/internal/worker/EagerActivitySlotsReservation.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
Eager activity dispatch is buried deep down inside `sendReply` method where it does not belong.
This creates a surprising behavior of `sendReply`, code that is harder to follow and modify in the future.
> Refactor WorkflowWorker to put eager activity dispatch in the right place

- .gitmodules
Upgrade Temporal Server API protos to 1.12
> Update API protos to 1.12

- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/test/java/io/temporal/internal/testing/WorkflowReplayerTest.java
- temporal-testing/src/main/java/io/temporal/testing/ReplayResults.java
- temporal-testing/src/main/java/io/temporal/testing/WorkflowReplayer.java
Added API to workflow replayer accepting multiple histories at once
Parity with changes to other SDKs
1. Closes https://github.com/temporalio/sdk-java/issues/1494
Added unit tests
> Mass replay API

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-sdk/src/test/java/io/temporal/workflow/GetHistoryLengthTest.java
- temporal-sdk/src/test/resources/testGetHistoryLength.json
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
`WorkflowInfo#getHistoryLength` is added that can be used to define when to call `continueAsNew`.
Closes #1300
> Add WorkflowInfo#getHistoryLength

- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalDuringLastWorkflowTaskTest.java
`SignalDuringLastWorkflowTaskTest` was broken since an incorrect refactoring done in #383 and was effectively a no-op
> Fix SignalDuringLastWorkflowTaskTest

- .github/workflows/sdk-features.yml
Depends on https://github.com/temporalio/sdk-features/pull/162
> Add sdk-features ci trigger

- build.gradle
- docker/buildkite/docker-compose.yaml
- gradle/errorprone.gradle
- temporal-sdk/src/main/java/io/temporal/client/ActivityCompletionClientImpl.java
- temporal-sdk/src/main/java/io/temporal/client/ListWorkflowExecutionIterator.java
- temporal-sdk/src/main/java/io/temporal/client/SignalWithStartBatchRequest.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowClientInternal.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowExecutionMetadata.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowStubImpl.java
- temporal-sdk/src/main/java/io/temporal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/test/java/io/temporal/client/functional/ListWorkflowExecutionsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-serviceclient/build.gradle
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcAsyncRetryer.java
- temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcRetryer.java
- temporal-test-server/build.gradle
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java
`WorkflowClient#listWorkflowExecutions` was added to provide an easy-to-use wrapper over the underlying `{WorkflowServiceStub#listWorkflowExecutions(ListWorkflowExecutionsRequest)}`
Closes #1552
> List workflow API

- .github/workflows/features.yml
Waiting on https://github.com/temporalio/sdk-features/pull/207
> Rename sdk-features to features

- temporal-sdk/src/main/java/io/temporal/internal/worker/Throttler.java
- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerFactory.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkflowImplementationOptions.java
Fix grammar and typo in documentation comments
Invalid grammar and typo 
NA
1. Closes 
NA
3. How was this tested:
NA
4. Any docs updates needed?
NA
> Fix grammar mistake and typo

- temporal-sdk/src/main/java/io/temporal/internal/replay/BasicWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Add `WorkflowInfo#getFirstExecutionRunId` and `WorkflowInfo#getOriginalExecutionRunId`. Add javadocs to `WorkflowInfo`.
Closes #1562
> Add WorkflowInfo#getFirstExecutionRunId and #getOriginalExecutionRunId

- temporal-sdk/src/main/java/io/temporal/internal/activity/ActivityTaskHandlerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/LocalActivityIsNotRegisteredTest.java
Unregistered Local Activity now fails Workflow Task
Closes #1561
> Unregistered Local Activity now fails Workflow Task

- releases/v1.18.2
- releases/v1.19.0
- Ability for users to encode/encrypt Failures. See CodecDataConverter#encodeFailureAttributes
- [GraalVM descriptors for core modules](https://github.com/temporalio/sdk-java/blob/ee86c34002c6d92dd5ec1227ad1b9ddc5e20c5a9/docs/AOT-native-image.md)
- [New temporal-shaded module that shades grpc, protobuf, guava](https://github.com/temporalio/sdk-java/blob/ee86c34002c6d92dd5ec1227ad1b9ddc5e20c5a9/temporal-shaded/README.md)
- Eager Workflow Task Dispatch. Requires Temporal Server 1.20+
- Fixes for some overly verbose exception traces in the history
- Experimental SerializationContext support in PayloadConverter and PayloadCodec
> Release v1.19.0

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/common/NonIdempotentHandle.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThread.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadScheduler.java
- temporal-sdk/src/main/java/io/temporal/workflow/unsafe/WorkflowUnsafe.java
- temporal-sdk/src/test/java/io/temporal/client/ListWorkflowExecutionsTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/deadlockdetector/DeadlockDetectorTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/deadlockdetector/PayloadConverterEscapingDeadlockDetectionTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/ExceptionInSignalTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalOrderingWorkflowTest.java
- temporal-test-server/build.gradle
Add `WorkflowUnsafe#deadlockDetectorOff` that allows running pieces of code with disabled deadlock detection
Closes #1301
> Allow Data Converter code to escape deadlock detection

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/UpdateProtocolStateMachine.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Avoids including the full initial request in the Acceptance and Rejection messages from the update protocol. 
Server has been updated to not expect these fields so save the bandwidth
1. Closes 
> Do not add accepted/rejected request to messages

- releases/v1.20.1
> Update release notes for 1.20.1

- gradle/jacoco.gradle
Fix code coverage action because `temporal-bom` has no code
> Fix jacoco code coverage

- releases/v1.21.1
> Release Java SDK v1.21.1

- temporal-spring-boot-autoconfigure-alpha/README.md
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/TemporalOptionsCustomizer.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/NamespaceTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkersTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkflowImplementationOptionsTemplate.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/OptionsCustomizersTest.java
Allow set `WorkflowImplementationOptions` using customizer 
https://github.com/temporalio/sdk-java/tree/master/temporal-spring-boot-autoconfigure-alpha#customization-of-options
1. Closes 
> add WorkflowImplementationOptions customizer

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowContextImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowTaskStateMachine.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInfoImpl.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowInfo.java
- temporal-sdk/src/test/java/io/temporal/workflow/GetHistorySizeTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/searchattributes/TypedSearchAttributesTest.java
- temporal-sdk/src/test/resources/testGetHistorySize.json
- temporal-testing/src/main/java/io/temporal/internal/sync/DummySyncWorkflowContext.java
Add new workflow info fields.
Note: This does not add support to the test server. I'll need to open another issue to add support there.
ref https://github.com/temporalio/features/issues/16
> Add new workflow info fields

- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/test/java/io/temporal/worker/WorkerOptionsTest.java
Fix https://github.com/temporalio/sdk-java/issues/1854
> Fix workflow options equality

- temporal-serviceclient/build.gradle
- temporal-test-server/build.gradle
Fix linux aarch64 build.
closes https://github.com/temporalio/sdk-java/issues/1883
> Fix build for Linux for aarch64

- releases/v1.21.2
- releases/v1.22.0
> Release Java SDK v1.22.0

- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
Add identity to Terminate call.
closes https://github.com/temporalio/sdk-java/issues/1893
> Add identity to Terminate call

- releases/v1.22.1
> Release Java SDK v1.22.1

- temporal-sdk/src/test/java/io/temporal/workflow/searchattributes/TypedSearchAttributesTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestVisibilityStoreImpl.java
Fix race condition in test server SA and register TemporalChangeVersion by default.
closes https://github.com/temporalio/sdk-java/issues/1802
> Fix race condition in test server SA

- releases/v1.22.2
> Release Java SDK v1.22.2

- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateTestContinueAsNew.java
Test continue as new in an update handler
> Test continue as new in an update

- temporal-shaded/build.gradle
Add proto-google-common-protos to temporal-shaded
closes https://github.com/temporalio/sdk-java/issues/1911
> Add proto-google-common-protos to temporal-shaded

- releases/v1.22.3
> Release Java SDK v1.22.3

- docker/buildkite/docker-compose.yaml
Switch from temporaliotest to temporalio
temporaliotest appears to have its setup changed and now doesn't work, need to follow up with the server team on this.
> Switch to temporalio/auto-setup

- temporal-spring-boot-autoconfigure-alpha/README.md
Add reference to build-id config, ScheduleClient, and link to samples for Spring Boot
> Small update to Spring Boot Readme

- temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java
- temporal-spring-boot-autoconfigure-alpha/src/test/java/io/temporal/spring/boot/autoconfigure/StartWorkersTest.java
- temporal-spring-boot-autoconfigure-alpha/src/test/resources/application.yml
fixes start-worker config.
closes https://github.com/temporalio/sdk-java/issues/1971
> Fix start-workers config

- build.gradle
closes https://github.com/temporalio/sdk-java/issues/1803
> Update Guava to v32.0.1

- releases/v1.23.0
> Release v1.23.0

- README.md
Switch build status badge to GH action
> Switch build status badge to GH action

- releases/v1.23.1
> Release v1.23.1

- .github/workflows/ci.yml
Fix github action environment variables so test server and docker runs use intended target
> Fix environment variables in CI github action

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-snapshot.yml
Update github actions to satisfy dependabot.
> Update github actions

- README.md
Add note on using snapshot releases.
> Add note on using snapshot releases

- .gitmodules
- gradle/licensing.gradle
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
> Update proto API to 1.32.0

- temporal-testing/src/main/java/io/temporal/testing/internal/TracingWorkerInterceptor.java
Fix recursion in TracingWorkerInterceptor
> Fix recursion in TracingWorkerInterceptor

- temporal-sdk/src/main/java/io/temporal/failure/ApplicationFailure.java
- temporal-sdk/src/main/java/io/temporal/failure/DefaultFailureConverter.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/test/java/io/temporal/activity/ActivityNextRetryDelayTest.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestServiceRetryState.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java
Add support for nextRetryDelay to :
* ApplicationFailure
* LocalActivities
* Time Skipping test server
> Add support for nextRetryDelay

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-snapshot.yml
Bump some GH action to latest versions to keep dependencies up to date
> Bump some GH action dependencies

- temporal-sdk/src/main/java/io/temporal/internal/sync/ChildWorkflowInvocationHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/ExternalWorkflowInvocationHandler.java
Add exception when calling an update handler on stub since it is not supported.
> Add exception for calling an update method on a stub

- temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java
- temporal-serviceclient/src/main/java/io/temporal/serviceclient/WorkflowServiceStubsOptions.java
closes https://github.com/temporalio/sdk-java/issues/2047
> Add toString to ServiceStubOptions

- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowStateMachines.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowTaskHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/TestHistoryBuilder.java
- temporal-sdk/src/test/java/io/temporal/internal/statemachines/UpdateProtocolStateMachineTest.java
- temporal-sdk/src/test/java/io/temporal/internal/sync/DeterministicRunnerTest.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowWorkerTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/DirectQueryReplaysDontSpamLogWithWorkflowExecutionExceptionsTest.java
Allow SDK to handle speculative workflow task with command events
> Allow SDK to handle speculative workflow task with command events

- releases/v1.24.0
> Release v1.24.0

- .github/workflows/prepare-release.yml
Switch checkout in prepare-release.yml to v3
> Switch checkout in prepare-release.yml to v3

- .github/workflows/features.yml
Point feature repo back to main
> Point feature repo back to main

- releases/v1.24.1
> Release v1.24.1

- releases/v1.24.2
> Release v1.24.2

- temporal-sdk/src/main/java/io/temporal/client/ListScheduleListDescriptionIterator.java
- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleClient.java
- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleClientImpl.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/ScheduleClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootScheduleClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
closes https://github.com/temporalio/sdk-java/issues/2139
> Add support for query in listSchedules

- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java
- temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SignalDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SignalHandlerInfo.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/UpdateDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/UpdateHandlerInfo.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowExecutionHandler.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/DynamicSignalHandler.java
- temporal-sdk/src/main/java/io/temporal/workflow/DynamicUpdateHandler.java
- temporal-sdk/src/main/java/io/temporal/workflow/HandlerUnfinishedPolicy.java
- temporal-sdk/src/main/java/io/temporal/workflow/SignalMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/UpdateMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerCacheTests.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandlerTaskHandlerTests.java
- temporal-sdk/src/test/java/io/temporal/internal/replay/WarnUnfinishedHandlers.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalAllHandlersFinished.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateAllHandlersFinished.java
- temporal-sdk/src/test/resources/logback-test.xml
Warn on dangling handlers and add method to help await on all handlers.
> Warn on dangling handlers and add method to help await on all handlers.

- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleUpdate.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootScheduleClientInvoker.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
- temporal-sdk/src/test/java/io/temporal/testUtils/Eventually.java
Ad support for updating schedule search attributes
closes https://github.com/temporalio/sdk-java/issues/2152
> Ad support for updating schedule search attributes

- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalAllHandlersFinished.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateAllHandlersFinished.java
Fix isEveryHandlerFinished doc string
> Fix isEveryHandlerFinished doc string

- temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowSlotsSmallSizeTests.java
- temporal-sdk/src/test/java/io/temporal/testUtils/CountingSlotSupplier.java
Don't use metrics here and instead rely on wrapper for counts
> Activity slot test flake

- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/jni-config.json
- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/predefined-classes-config.json
- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/reflect-config.json
- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/resource-config.json
- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/serialization-config.json
Add to Graal analysis. I think there is some duplication with other refection files, but I couldn't figure out a good way to automatically filter out duplicates
> Add to Graal bindings

- temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java
- temporal-sdk/src/test/java/io/temporal/internal/worker/WorkflowWorkerTest.java
closes https://github.com/temporalio/sdk-java/issues/2184
> Fix workflow start delay docs to say signal does not interrupt delay

- .github/workflows/features.yml
Remove feature repo tag now that `v1.25.0` is released
> Remove feature repo tag

- releases/v1.25.1
> Release v1.25.1

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/DescribeNamespaceTest.java
closes https://github.com/temporalio/sdk-java/issues/2227
> Fill in namespace capabilities in describe response

- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Update Test Server Capabilities to match recently added features
> Update Test Server Capabilities

- temporal-kotlin/build.gradle
- temporal-kotlin/src/main/kotlin/io/temporal/workflow/NexusOperationOptionsExt.kt
- temporal-kotlin/src/main/kotlin/io/temporal/workflow/NexusServiceOptionsExt.kt
- temporal-kotlin/src/test/kotlin/io/temporal/nexus/NexusOperationOptionsExtTest.kt
- temporal-kotlin/src/test/kotlin/io/temporal/nexus/NexusServiceOptionsExtTest.kt
- temporal-kotlin/src/test/kotlin/io/temporal/workflow/KotlinAsyncNexusTest.kt
- temporal-sdk/src/main/java/io/temporal/workflow/NexusOperationOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusServiceOptions.java
Add helper for Nexus to Kotlin Integration
> Add helper for Nexus to Kotlin Integration

- temporal-sdk/src/test/java/io/temporal/workflow/nexus/TerminateWorkflowAsyncOperationTest.java
Add terminate workflow nexus test
> Add terminate workflow test

- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusServiceOptions.java
Add some nexus option validation based on what we did in Go 
https://github.com/temporalio/sdk-go/pull/1661
> Add some nexus option validation

- temporal-sdk/src/main/java/io/temporal/internal/worker/NexusWorker.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/SyncClientOperationTest.java
Align with https://github.com/temporalio/sdk-go/pull/1664
> Change when nexus_task_execution_failed is emitted

- releases/v1.26.0
> Release v1.26.0

- temporal-sdk/src/main/java/io/temporal/internal/client/WorkflowClientRequestFactory.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/test/java/io/temporal/workflow/searchattributes/TypedSearchAttributesTest.java
Fix Null pointer exception on passing empty search attribute
closes https://github.com/temporalio/sdk-java/issues/2276
> Fix Null pointer exception on passing empty search attribute

- temporal-sdk/src/main/java/io/temporal/client/UpdateWithStartWorkflowOperation.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowInvocationHandler.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateWithStartTest.java
Pass workflow args - instead of update args - to workflow start.
Bug.
1. Closes https://github.com/temporalio/sdk-java/issues/2285
> Fix UpdateWithStart workflow args

- releases/v1.26.1
> Release v1.26.1

- .github/workflows/ci.yml
- build.gradle
- gradle/java.gradle
- temporal-kotlin/build.gradle
Bump Java edge dependency version to 21
> Bump Java edge dependency version to 21

- temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowOutboundCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowMethod.java
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowMethodMetadata.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/QueryDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SignalDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflow.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowContext.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/UpdateDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java
- temporal-sdk/src/main/java/io/temporal/workflow/DynamicQueryHandler.java
- temporal-sdk/src/main/java/io/temporal/workflow/DynamicSignalHandler.java
- temporal-sdk/src/main/java/io/temporal/workflow/DynamicUpdateHandler.java
- temporal-sdk/src/main/java/io/temporal/workflow/QueryMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/SignalMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/UpdateMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanActivityWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanNexusWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowMetadataTest.java
- temporal-testing/src/main/java/io/temporal/testing/internal/TracingWorkerInterceptor.java
Add workflow metadata query
https://github.com/temporalio/sdk-java/issues/335
> Add workflow metadata query

- .github/workflows/features.yml
> Remove feature branch

- gradle/jacoco.gradle
Fix jacoco coverage
https://docs.gradle.org/8.0/userguide/upgrading_version_7.html#report_and_testreport_api_cleanup
> Fix jacoco coverage

- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowHandle.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowHandleStubTest.java
Expose `WorkflowHandle.fromWorkflowStub`. I think I just forgot to expose it when merging all the Nexus work.
> [Nexus] Expose fromWorkflowStub

- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
Require workflow ID to be set for Nexus
> Require workflow ID to be set for Nexus

- build.gradle
- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
Add operation Id to callback headers. Similar to https://github.com/temporalio/sdk-go/pull/1710.
> Add operation Id to callback headers

- temporal-sdk/src/main/java/io/temporal/activity/ManualActivityCompletionClient.java
- temporal-sdk/src/main/java/io/temporal/client/ActivityCompletionClient.java
closes https://github.com/temporalio/sdk-java/issues/1233
> Add javadocs for ActivityCompletionClient

- gradle/java.gradle
Add details to manifest
closes https://github.com/temporalio/sdk-java/issues/2177
> Add details to manifest

- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ParallelLocalActivitiesTest.java
Split test into queued and not-queued versions & changed timeout kinds correspondingly
Test would flake due to slow CI
1. Closes 
> Split up & use more appropriate timeouts for parallel LAs test

- .github/workflows/ci.yml
- build.gradle
Upgrade some test dependencies
> chore: Upgrade some test dependencies

- temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/NexusPollTask.java
- temporal-sdk/src/main/java/io/temporal/internal/worker/WorkflowPollTask.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/WorkflowSlotInfo.java
> Update proto v1.44.0

- temporal-sdk/src/main/java/io/temporal/activity/ActivityMethod.java
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOActivityImplMetadata.java
- temporal-sdk/src/main/java/io/temporal/common/metadata/POJOWorkflowImplMetadata.java
- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/NexusTaskHandlerImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/QueryDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/SignalDispatcher.java
- temporal-sdk/src/main/java/io/temporal/internal/sync/UpdateDispatcher.java
- temporal-sdk/src/main/java/io/temporal/workflow/QueryMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/SignalMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/UpdateMethod.java
- temporal-sdk/src/main/java/io/temporal/workflow/WorkflowMethod.java
- temporal-sdk/src/test/java/io/temporal/workflow/WorkflowRestrictedNameTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/ActivityRestrictedNameTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/queryTests/QueryRestrictedNameTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalRestrictedNameTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/updateTest/UpdateRestrictedNameTest.java
Special behavior for Temporal built-in prefixes
closes https://github.com/temporalio/sdk-java/issues/2368
> Special behavior for Temporal built-in prefixes

- temporal-spring-boot-autoconfigure/README.md
Update readme for multi namespace support
> Update readme for multi namespace support

- temporal-spring-boot-autoconfigure/README.md
Add nexus configuration to spring boot readme
> Add nexus configuration to spring boot readme

- temporal-test-server/src/main/resources/META-INF/native-image/io.temporal/temporal-test-server/reflect-config.json
Add Graal reflection config for UwS. Generated by running UwS tests with tracing agent
> Add Graal reflection config for UwS

- temporal-opentracing/src/test/java/io/temporal/opentracing/NexusOperationTest.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/OperationToken.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/OperationTokenType.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/OperationTokenUtil.java
- temporal-sdk/src/main/java/io/temporal/internal/nexus/WorkflowRunOperationToken.java
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowRunOperationImpl.java
- temporal-sdk/src/test/java/io/temporal/internal/nexus/WorkflowRunTokenTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/AsyncWorkflowOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/TerminateWorkflowAsyncOperationTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/nexus/WorkflowOperationLinkingTest.java
- temporal-sdk/src/test/resources/testAsyncWorkflowOperationTestHistory.json
Change the operation token of a start workflow run from the workflow ID to a JSON struct
see also: https://github.com/temporalio/sdk-go/commit/22ebdc0dfafb71203ab20ebb191b007312e0a987#diff-0fbedb8a3b59e2b2542d81ddae097166bf3ffb124f1ee4c2837040609d779bc6
> Workflow run token

- temporal-sdk/src/test/java/io/temporal/workflow/nexus/HeaderTest.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/StateMachines.java
- temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
Add support for operation timeout header to the test server
> Add support for operation timeout header

- releases/v1.28.0
> Release v1.28.0

- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/ConnectionProperties.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/ApiKeyAuthTest.java
closes https://github.com/temporalio/sdk-java/issues/2443
> Fix spring boot api key enable https

- temporal-sdk/src/main/java/io/temporal/nexus/Nexus.java
- temporal-sdk/src/main/java/io/temporal/nexus/NexusOperationContext.java
- temporal-sdk/src/main/java/io/temporal/nexus/WorkflowRunOperation.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusOperationHandle.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusOperationOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusServiceOptions.java
- temporal-sdk/src/main/java/io/temporal/workflow/NexusServiceStub.java
- temporal-sdk/src/main/java/io/temporal/workflow/Workflow.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironment.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowExtension.java
- temporal-testing/src/main/java/io/temporal/testing/TestWorkflowRule.java
Remove experimental tag from Nexus for Nexus Java SDK GA.
> Remove experimental tag from Nexus

- releases/v1.28.4
> Release v1.28.4

- .github/workflows/gradle-wrapper-validation.yml
Update Gradle validation action, since `gradle/wrapper-validation-action` just proxies `gradle/actions/wrapper-validation`
> Update Gradle validation action

- temporal-sdk/src/main/java/io/temporal/common/converter/DataConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/DefaultDataConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/PayloadAndFailureDataConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/PayloadConverter.java
- temporal-sdk/src/main/java/io/temporal/common/converter/RawValue.java
- temporal-sdk/src/test/java/io/temporal/common/converter/CodecDataConverterTest.java
- temporal-sdk/src/test/java/io/temporal/common/converter/ProtoPayloadConverterTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/activityTests/TestRawValueActivity.java
- temporal-sdk/src/test/java/io/temporal/workflow/shared/TestActivities.java
Add RawValue support
closes https://github.com/temporalio/sdk-java/issues/2425
> Add RawValue support

- temporal-sdk/src/main/java/io/temporal/client/schedules/ScheduleDescription.java
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
Fix NPR getting a non existent memo from a schedule.
> Fix NPR getting a non existent memo from a schedule.

- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ActivityStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/CancelExternalStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/CancelWorkflowStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ChildWorkflowStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/CompleteWorkflowStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/ContinueAsNewWorkflowStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/FailWorkflowStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/LocalActivityStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/MutableSideEffectStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/SideEffectStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/SignalExternalStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/TimerStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/UpdateProtocolStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/UpsertSearchAttributesStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/VersionStateMachine.puml
- temporal-sdk/src/main/java/io/temporal/internal/statemachines/WorkflowTaskStateMachine.puml
Update proto v1.49.0
1. Closes 
> Update proto v1.49.0

- .github/workflows/ci.yml
- build.gradle
- temporal-sdk/build.gradle
- temporal-sdk/src/test/java/io/temporal/client/schedules/ScheduleTest.java
- temporal-serviceclient/build.gradle
Bump Java SDK test version to make sure we are testing with the latest Java SDK
> Bump edge Java SDK test version

- temporal-sdk/src/main/java/io/temporal/internal/common/InternalUtils.java
- temporal-sdk/src/main/java/io/temporal/internal/common/LinkConverter.java
- temporal-sdk/src/test/java/io/temporal/internal/common/LinkConverterTest.java
- temporal-test-server/src/test/java/io/temporal/testserver/functional/NexusWorkflowTest.java
Support for `RequestIdReference` link and setting the links in the Nexus callback
1. Closes 
> Set links in Nexus callback

- CONTRIBUTING.md
Remove license check from header
> Remove license check from header

- temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowClientInternalImpl.java
- temporal-sdk/src/main/java/io/temporal/client/WorkflowExecutionCount.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptor.java
- temporal-sdk/src/main/java/io/temporal/common/interceptors/WorkflowClientCallsInterceptorBase.java
- temporal-sdk/src/main/java/io/temporal/internal/client/RootWorkflowClientInvoker.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClient.java
- temporal-sdk/src/main/java/io/temporal/internal/client/external/GenericWorkflowClientImpl.java
- temporal-sdk/src/main/java/io/temporal/internal/common/SearchAttributesUtil.java
- temporal-sdk/src/test/java/io/temporal/client/CountWorkflowsTest.java
Add API to count workflows
closes https://github.com/temporalio/sdk-java/issues/1685
> Add API to count workflows

- temporal-sdk/src/main/java/io/temporal/worker/Worker.java
- temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/PollerBehaviorAutoscaling.java
- temporal-sdk/src/main/java/io/temporal/worker/tuning/PollerBehaviorSimpleMaximum.java
- temporal-sdk/src/test/java/io/temporal/worker/PollerAutoScaleTests.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanActivityWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/CleanNexusWorkerShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/worker/shutdown/StickyWorkflowDrainShutdownTest.java
- temporal-sdk/src/test/java/io/temporal/workflow/MetricsTest.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/properties/WorkerProperties.java
- temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/autoconfigure/template/WorkerOptionsTemplate.java
- temporal-spring-boot-autoconfigure/src/test/java/io/temporal/spring/boot/autoconfigure/OptionalWorkerOptionsTest.java
- temporal-spring-boot-autoconfigure/src/test/resources/application.yml
Add poller autoscaling options for Springboot. I also did some renaming for make it more standard.
closes https://github.com/temporalio/sdk-java/issues/2552
> Add poller autoscaling options for Springboot

- releases/v1.30.0
> Release Java SDK v1.30.0

- releases/v1.30.1
> Release Java SDK v1.30.1

- .github/workflows/build-native-image.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-snapshot.yml
- build.gradle
> Bump dependencies
